### ISSUE TITLE
sensible_browser_position.patch

### ISSUE THREAD

**Issue by 4nd3r** [neomutt/neomutt#1]
please consider merging (and maybe refactor?) this patch:
http://anonscm.debian.org/cgit/pkg-mutt/mutt.git/tree/debian/patches/features/sensible_browser_position.patch

also big thanks for your effort!

**Comment by flatcap** [comment]
> please consider merging (and maybe refactor?) this patch:

[sensible_browser_position.patch.txt](https://github.com/neomutt/neomutt/files/164364/sensible_browser_position.patch.txt) (local copy)

It was on one of my "less-important" todo lists, but that's because I'd only glanced at the name and not understood what the patch meant.  I'll see what I can do.

> also big thanks for your effort!

You're welcome.

**Comment by flatcap** [comment]
@4nd3r 
I've had a look through the code and the mailing list thread.
Hmm... It works, yes, but it's limited to IMAP connections.
It really needs to work for **all** browser use.

There was one person who didn't want the feature because he had his folders sorted by count.
So, the patch needs extending:
- [X] Remember IMAP folder
- [ ] Remember local folder
- [ ] Disable if browser list is not sorted alphabetically

This is a useful idea, but it's not ready in its current form.
I don't, yet, have the time to fix it.

If anyone would like to help, let me know.

**Comment by flatcap** [comment]
I've pushed the current patch to NeoMutt:
https://github.com/neomutt/neomutt/tree/feature/sensible-browser

**Comment by pickfire** [comment]
What does this do?

**Comment by flatcap** [comment]
@pickfire 
It makes the mailbox/directory browser behave as you would expect.
When you change directory to the parent (..), the old directory should be selected.

Using these folders:
```
.
├── apple
│   ├── blue
│   ├── green
│   └── red
├── banana
│   ├── cyan
│   ├── magenta
│   └── yellow
└── cherry
    ├── orange
    ├── pink
    └── teal
```
If I'm viewing the "**cherry/pink**" mailbox, and I press 'c' to \<change-folder\>, I'll see the list:

- **..**
- orange
- pink
- teal

dot-dot is highlighted, but it should be **pink**.
If I navigate to dot-dot (parent), I'll see the list:

- **..**
- apple
- banana
- cherry

Again, dot-dot is highlighted, but **cherry** should be.

The sensible-browser patch fixes Mutt's behaviour, but there's a bug.
It shouldn't select the old folder when the folder is not sorted alphabetically.

**Comment by pickfire** [comment]
Oh, I understand what it means now.

**Comment by flatcap** [comment]
I'm not quite happy with the code for this, so I'm going to reopen this for now.

**Comment by flatcap** [comment]
For reference, development is happening in the [devel/sensible-browser](https://github.com/neomutt/neomutt/tree/devel/sensible-browser) branch.

**Comment by P-EB** [comment]
I worked on it. See commit 199b308 for the current state of the patch.

**Comment by P-EB** [comment]
Previous comment updated, I have a working patch.

Reviewing of the code would be appreciated.

**Comment by P-EB** [comment]
The patch seems to be merge-ready. I'll let it to @flatcap.

**Comment by flatcap** [comment]
OK, the browser's looking good.
Now there are two extensions that are commonly asked for:

- Sort ".." first regardless of sort type and direction.
  This means tweaking the `browser_compare_*` functions
- Disable the sensible-browser if the sort method isn't (reverse-)alphabetic,
  e.g. sort by reverse-new-count.

Starting with some folders:

```
apple      0
banana     3
cherry     7
damson     2
elderberry 1
```

Sorted by reverse-new-count:

```
cherry     7    <= CURSOR
banana     3
damson     2
elderberry 1
apple      0
```

If I open "cherry" and read all the new emails, then when I go to the browser,
I'd expect to see:

```
banana     3    <= CURSOR
damson     2
elderberry 1
apple      0
cherry     0
```

**Comment by P-EB** [comment]
In my opinion that'd be counter-intuitive. I'd expect to see highlighted the folder I was in, whatever the sorting is.

I guess it's a policy choice, I can comply with it, but I'd feel unsatisfied by it.

**Comment by P-EB** [comment]
I made a patch for the first demand. See 7f562fd.

If you wish to merge some commits, please keep this one aside of the others as it is not the same feature.

**Comment by P-EB** [comment]
Merged in neomutt.
