### ISSUE TITLE
Recipient's S/MIME certificate disappears after sending an encrypted email

### ISSUE THREAD

**Issue by mimaoffice** [neomutt/neomutt#1006]
(Tested with NeoMutt 20171208 on macOS - installed with MacPort - and also with mutt-1.9.1 on Fedora 26)

I already reported this bug [here](https://dev.mutt.org/trac/ticket/3982) and it has already been [fixed](https://gitlab.com/muttmua/mutt/commit/9eedfd4e1b62d1749f7e93d85fb0930e7d2cdf8f) in mutt-1.9.2. Can you please also fix it in neomutt?

How to reproduce:

- start neomutt (with default smime.rc)
- enter IMAP password
- compose a new email
- enter a text and exit the editor (vi)
- set the security to "e" (encrypt)
- send

At this point, as an `strace` shows, the certificate of the recipient has been deleted:

```
[pid  7621] lstat("/u/mmarcio/.smime/certificates/0cf3fc1c.0", {st_mode=S_IFREG|0600, st_size=2291, ...}) = 0
[pid  7621] open("/u/mmarcio/.smime/certificates/0cf3fc1c.0", O_RDWR|O_NOFOLLOW) = 8
[pid  7621] fstat(8, {st_mode=S_IFREG|0600, st_size=2291, ...}) = 0
[pid  7621] fcntl(8, F_GETFL)           = 0x28002 (flags O_RDWR|O_LARGEFILE|O_NOFOLLOW)
[pid  7621] unlink("/u/mmarcio/.smime/certificates/0cf3fc1c.0") = 0
```
Bests, Michele

**Comment by flatcap** [comment]
Thanks for the bug report, @mimaoffice.
All of Mutt's fixes get folded into NeoMutt, but it just missed out on the latest NeoMutt release.

As there's a workaround, the fix will have to wait until the next release (in a few weeks).
I'll leave this issue open until the fix is committed.

**Workaround**

- enable `smime_self_encrypt`
- set a value for `smime_self_encrypt_as`

This will cause the certificate list to have more than one cert, causing the unlink to fail.

**Comment by mimaoffice** [comment]
Should the workaround not be the default?
