### ISSUE TITLE
Add sane and minimal gpg defaults

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#101]
Currently, I am throwing my brain against making Mutt work with newer versions of GnuPG.  While there's a myriad of howtos, nothing really leads to success. Having a minimal, current, working snippets for common use cases would help with finding out what needs doing.

**Comment by flatcap** [comment]
I recently put my crypto.rc online which uses gpg2 : [crypto.rc](https://gist.github.com/flatcap/c0d567ea97ef1b68ecf3df698210f9a5)
That may help you, but you're right, we need more helpful config examples.

There are some limits to the defaults we can set in NeoMutt and the config files that get installed depend on the distro, but we can do better.

**Comment by pickfire** [comment]
@flatcap I found the newest version of gpg 2.1.4 working nice with mutt. Is there anything that is off?

**Comment by RichiH** [comment]
@flatcap What you're describing is the problem of legacy configs, be they system or user; my own config is more than a decade in the making.

This might descend into an endless rabbit hole of handholding, but it might be an option to warn about known-bad/stale settings while parsing the config.

**Comment by aradici** [comment]
RichiH my suggestion is to use "set crypt_use_gpgme=yes" and have gpg2 installed, that should be enough and you won't need to configure any pgp command as it was in the past.

In Debian we are shipping this configuration starting with 1.7.0-2 (which corresponds to NeoMutt 20160827).

As neomutt is providing the source I'm not sure what we can provide by default because even if we set it to true in neomutt, the user has to build it with the right options at configure time :(

**Comment by RichiH** [comment]
Interesting, I will have to try this when I have access to my normal keys again next week.

If people mess with build options, they tend to understand that sample configs might not be for them so I don't see that as too much of a problem.
