### ISSUE TITLE
Mail appended to $record even of sending fails

### ISSUE THREAD

**Issue by darnir** [neomutt/neomutt#1012]
I use NeoMutt with msmtp for sending my emails.

Due to a connection issue, msmtp failed to send the email I sent and returned an error code. Mutt correctly identified the error and showed the message that msmtp threw.

However, multiple copies of my email were added to the $record directory for my account, one for each time I tried before giving up. The email should be appended to $record only on a successful sending of the email, not otherwise

**Comment by flatcap** [comment]
This also happens with the built-in SMTP (and upstream mutt).
I remember some conversation on the mutt-devel mailing list -- something about saving emails on errors.

**Comment by Knusper** [comment]
I just ran into this issue and found this bugreport.  How can I prevent that emails are saved to sent, even if there was an error when sending.  (I use set record=~/Mail/sent).  In my case the smtp server sometimes refuses to log me in, and I get a "SASL (authentication failed)" error, but the mail is still copied to sent...

**Comment by gahr** [comment]
Do you have `fcc_before_send` set perhaps?

**Comment by Knusper** [comment]
No, I use `set record=` - note that I am not running on the latest development branch but the last release.

**Comment by Knusper** [comment]
I found the the thread in the mutt-dev mailinglist - it seems that the mutt dev consider it a feature, rather than a bug: https://marc.info/?t=146942943600002&r=1&w=2

:( - given that there is also `fcc_before_send` it is beyond my understanding why this behaviour is as it is...

**Comment by sjbronner** [comment]
I just read through the thread in the mutt-dev mailing list. I agree with Olaf Hering, Oswald Buddenhagen, Vincent Lefevre, Derek Martin, and web626 that the `$record` directory should contain only messages that were actually sent. The desire not to lose messages in the event of an unrelated and immediately subsequent unrecoverable failure, as voiced by Michael Tatge, Ian Collier, and Simon Ruderich, can still be achieved by using the following sequence:

1. Store the message that is to be sent in `$postponed`. (There it is in the right place in case of an unrelated and immediately subsequent unrecoverable failure.)
2. Send the message.
3. Move the message from `$postponed` to `$record`.

It seems that Michael Tatge agreed with this early on in the thread (https://marc.info/?l=mutt-dev&m=146945120924606):

```
> > > For each iteration another copy of the message to be sent is stored in
> > > record
> > 
> > in general that's a good think(tm).
> > you don't loose the mail you where just trying to send, because there is
> > a local copy.
> >
> assuming that's even necessary, the _sensible_ thing to do in this
> scenario would be postponing the message instead.

right
```

I'm not sure why that didn't gain any traction, though.

Anyway, is there a position on this for `neomutt` @flatcap ? Or did you close this issue due to inactivity?

**Comment by flatcap** [comment]
@sjbronner 

> Anyway, is there a position on this for `neomutt`?

Generally, we'll follow upstream Mutt's lead.
I read their discussion about saving.  Ultimately, it's just an email.

Upstream Mutt added a new config option and I've merged it into NeoMutt (it's in [2019-10-25](https://github.com/neomutt/neomutt/releases/tag/2019-10-25))

> Or did you close this issue due to inactivity?

mea culpa.
Yeah, I have been known to close discussions I didn't want to have :-)

**Comment by Knusper** [comment]
Thanks for the new release and the hard work! Which option is the one
you are referring to?

**Comment by sjbronner** [comment]
Besides enabling the behavior desired in this issue, this option even defaults to it. This is really nice. I tested it and it works wonderfully. This resolves the issue for me.
