### ISSUE TITLE
The recommended pgp_decrypt_command takes a long time to decrypt and fails eventually

### ISSUE THREAD

**Issue by doronbehar** [neomutt/neomutt#1014]
### Expected behavior
When trying to open a decrypted message, I want to be prompted for entering the passphrase for my private key and to view the message.
### Actual behavior
I'm prompted to enter a passphrase to unlock my secret key but it is stuck in a loop that fails every iteration after a long time it tries to process something and eventually I get the red error message `Can't decrypt PGP message`. Plus, the text from the terminal asking me to enter the passphrase is printed weird:
```
Invoking PGP...Please enter the passphrase to unlock the OpenPGP secret key:
                                                                            "my name <me@example.com>"
                                                                                                      ####-bit RSA key, ID FFFFFFFFFFFFFFFF,
                                                                                                                                            created 2017-07-10 (main key ID FFFFFFFFFFFFFFFF).
                                                                                                                                                                                              Passphrase:

```
### Steps to reproduce
Just open a decrypted message with this setting in your `rc`:
```muttrc
set pgp_decrypt_command="gpg --status-fd=2 %?p?--passphrase-fd 0? --no-verbose --quiet --batch --output - %f"
```

### Used program versions

```
$ neomutt --version
NeoMutt 20171013
Copyright (C) 1996-2016 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type `neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type `neomutt -vv' for details.

System: Linux 4.14.4-1-ARCH (x86_64)
ncurses: ncurses 6.0.20170902 (compiled with 6.0)
libidn: 1.33 (compiled with 1.33)
hcache backends: gdbm

Compiler:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.2.0 (GCC) 

Configure options: '--prefix=/usr' '--sysconfdir=/etc' '--enable-debug' '--enable-gpgme' '--enable-lua' '--enable-notmuch' '--with-gss=/usr' '--with-ssl=/usr' '--with-sasl' '--with-curses=/usr' '--with-idn' '--with-gdbm' 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' 'LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' 'CPPFLAGS=-D_FORTIFY_SOURCE=2'

Compilation CFLAGS: -Wall -pedantic -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fno-delete-null-pointer-checks

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  +bkgdset +color +curs_set +debug +fcntl -flock -fmemopen +futimens 
  +getaddrinfo -gnutls +gpgme +gss +hcache -homespool +idn -locales_hack +lua 
  +meta -mixmaster +nls +notmuch +openssl +pgp +resizeterm +sasl +smime 
  +start_color +sun_attachment +typeahead 
MAILPATH="/var/mail"
PKGDATADIR="/usr/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/etc"

To learn more about NeoMutt, visit: http://www.neomutt.org/
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

```
$ gpg --version
gpg (GnuPG) 2.2.3
libgcrypt 1.8.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/doron/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

### Operating System and its version

```
$ uname -isrvo
Linux 4.14.4-1-ARCH #1 SMP PREEMPT Tue Dec 5 19:10:06 UTC 2017 unknown GNU/Linux
```

**Comment by Hasimir** [comment]
Try recompiling Neomutt but change the configure flag for GPGME from `--enable-gpgme` to `--with-gpgme=/usr/local` (assuming GPGME is actually installed in `/usr/local`, if not then change the path as appropriate for your system.  Then enable GPGME in your .muttrc if it's not already and try again.

**Comment by doronbehar** [comment]
Tell me if I'm wrong but I have a few questions
1. Isn't `gpgme` a dependency of `neomutt`? I have it installed in `/usr`
2. isn't my version of `neomutt` is compiled with gpgme enabled according to `neomutt -v | grep gpgme`?

I have `set crypto_use_gpgme = yes` in `rc` and I get the same results even when I don't have it defined.

**Comment by Hasimir** [comment]
It's an optional dependency in both Mutt and Neomutt.  If it's not compiled in then `set crypt_use_gpgme=yes` won't do anything and GPG would need to be called directly and bound to various Mutt hooks in the config file(s).

The out put of your Neomutt configuration clearly shows that the flaf used with the configure script was incorrect.  Yours has `--enable-gpgme` which won't do anything because the configure script doesn't know where to find GPGME.  To see exactly what you need to use in place of that flag, run this:

```bash
echo "--with-gpgme=`gpgme-config --prefix`"
```

On my system that tells me the flag is `--with-gpgme=/usr/local`, but the path will depend on where and how you installed GPGME in the first place.

**Comment by doronbehar** [comment]
First of all, this is the way it is compiled in Arch Linux:
```sh
./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --libexecdir=/usr/lib \
        --gpgme \
        --enable-lua \
        --notmuch \
        --gss \
        --ssl \
        --sasl \
        --with-ui=ncurses \
        --with-idn=/usr \
        --gdbm
```
source: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/neomutt

Running `gpgme-config --prefix` gives me `/usr`. Isn't it the default location for `./configure` chooses when compiling with `--gpgme` or `--enable-gpgme`?

**Comment by libBletchley** [comment]
It's really bizarre that you would get the same results whether you have `set crypto_use_gpgme = yes` or `unset crypto_use_gpgme`.  Make sure you don't have any funny business in your sitewide configs.

GPGME is new and experimental.  It's not ready for prime-time (even though the Debian project sadly enables gpgme in the sitewide config, thus forcing users to override it).  I suggest putting `unset crypto_use_gpgme` in your local configs to make sure it's not used, and to ensure that the  `pgp_decrypt_command` variable is actually used, at least for diagnostic purposes.

OTOH, I don't know of any GPGME issues with decryption.  GPGME is just broken when it comes to encrypting.  (hence this feature req: https://github.com/neomutt/neomutt/issues/913)

When it comes to decryption, for me it works with gpg 2.1.18 regardless of whether I use GPGME or the stock `pgp_decrypt_command`.  Maybe your newer gpg version introduced an issue?

**Comment by gahr** [comment]
> GPGME is new and experimental. It's not ready for prime-time

For the sake of completeness, I just would like to point out that this is totally your opinion, not GPGMe's developers', who instead state that "Especially authors of MUAs should consider to use GPGME.".

From your earlier comments, I get that your opinion comes from the fact that GPGMe doesn't support inline signatures. I also get that you would like to stick with inline signatures because some 3rd party agent/shop doesn't handle pgp/mime signatures correctly. Well, those are lagging behind, and time would be best invested in upgrading those solutions to handle recent standards.

I wish we could just drop pgp support via process calls entirely and just use GPGMe....

**Comment by doronbehar** [comment]
I get the same behaviour whether I `set crypto_use_gpgme = yes` or whether I `unset crypto_use_gpgme`.

**Comment by libBletchley** [comment]
@doronbehar 
I believe your problem is due to missing `--pinentry-mode loopback`.  Use this line: `set pgp_sign_command="/usr/bin/gpg %?p?--pinentry-mode loopback --passphrase-fd 0? --no-verbose --batch --quiet --output - --armor --textmode %?a?--local-user %a? --detach-sign %f"`

The need for `--pinentry-mode loopback` emerged in a recent GPG version with a huge number of significant changes.

@gahr 
GPGME is missing basic functionality.  This is why I say it's not ready for prime-time.

If the recipient is limited to the older (inline) standard, you cannot contact them.  That's not minor.  Being unable to communicate securely with someone is a serious and unacceptable show-stopper, particularly in a post-Snowden time period.  Specifically, it breaks:

 * sending a file attachment to a protonmail user (protonmail has widespread popularity ATM)
 * sending any secure message to a user of any webmail service running the hushmail backend (file attachment or not)
 * sending any secure message to anyone using a classic non-PGP/MIME MUA
 * receiving a msg from any of the above users probably requires extra manual work to open
 * ability to verify S/MIME sigs, strangely enough (https://github.com/neomutt/neomutt/issues/940)

Keeping `crypto_use_gpgme` _unset_ is the only way to ensure that a user can do everything mutt was designed for (and to be able to contact anyone).  AFAIK, GPGME has zero functionality benefits.  Or what am I missing?  The only advantage to GPGME is reduced configuration.  It would be quite unreasonable to trade the ability to communicate with some people for having a shorter config file.

Who should GPGME be recommended to?  An advanced user who knows they will never correspond with any above-mentioned recipient, and who will not receive signed S/MIME msgs.  And even then, they'll forget, try to send a file to a protonmail user, and go through a very inconvenient diagnosis to realize what the issue is.

It was a very sensible move for neomutt to have GPGME disabled by default.

**Comment by doronbehar** [comment]
O.K @libBletchley, I have finally managed to isolate the problem thanks to your suggestion.

My `~/.gnupg/gpg.conf` is empty and my `~/.gnupg/gpg-agent.conf` has:
```gpg
pinentry-program /home/doron/.bin/pinentry
allow-loopback-pinentry
```
I experience this problem because of my `pinentry-program` and the fact that I have `set pgp_use_gpg_agent = yes`. My `pinentry-program` is a simple bash script that uses the environmental variable `$PINENTRY_USER_DATA` as explained in the man page `gpg(1)`. Here is my [`~/.bin/pinentry`](https://github.com/doronbehar/dotfiles/blob/master/.bin/pinentry):
```sh
#!/bin/sh
# TAKEN FROM https://unix.stackexchange.com/a/236747/135796
# choose pinentry depending on PINENTRY_USER_DATA
# requires pinentry-curses and pinentry-gtk2
# this *only works* with gpg 2
# see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802020

case $PINENTRY_USER_DATA in
	curses)
		exec /usr/bin/pinentry-curses "$@"
		;;
	emacs)
		exec /usr/bin/pinentry-emacs "$@"
		;;
	gnome3)
		exec /usr/bin/pinentry-gnome3 "$@"
		;;
	gtk)
		exec /usr/bin/pinentry-gtk-2 "$@"
		;;
	qt)
		exec /usr/bin/pinentry-qt "$@"
		;;
	tty)
		exec /usr/bin/pinentry-tty "$@"
		;;
	*)
		exec /usr/bin/pinentry "$@"
		;;
esac
```

Usually my `$PINENTRY_USER_DATA` equals `tty` - that's why I see the characters printed out wierd underneith `neomutt`'s shell. But, If I run mutt with `env PINENTRY_USER_DATA=`, I do see a normal gtk/qt pinentry prompt **only if I'm in an X session**. On the other hand, if I run `env PINENTRY_USER_DATA= neomutt` on a bare tty terminal, I get the same behavior as I reported initially where the `pinentry-tty` program is trying to print a message and trying to get the passphrase from it's shell which resides inside`neomutt`'s shell.

**Luckily, as a workaround for users who use only tty, the `pinentry-ncurses` works just fine in a this scenario.**

I think we need to address this issue at least in the documentation - we need to recommend users to use the proper `pinentry-program` in their `gpg-agent.conf` based on their environment and explain that it is not recommended at the moment and it may cause a denial of service to use `pinentry-tty` together with `pgp_use_gpg_agent = yes` when one opens an encrypted message.

My problem was solved by adding `setenv PINENTRY_USER_DATA curses` to my `neomuttrc`.
