### ISSUE TITLE
Feature request: Different `From:` header depending on recipient list

### ISSUE THREAD

**Issue by RichiH** [neomutt/neomutt#110]
I have two email addresses at work: Shortform for internal, longform for external mail recipients.

If sending to an outside address, I am required/heavily encouraged to use `richard.hartmann@`, if sending internal mail, it's customary to use `rih@`.

A way to change detect any mail not going to `@space.net` and switching to longform would be nice. Obviously, this could only trigger on `To:` and `CC:`; not `BCC:`.

**Comment by flatcap** [comment]
Hmm... this sounds like the sort of thing Mutt does well.
[Looking through the docs](http://www.neomutt.org/manual/configuration.html#reply-hook) :-)
I find: 

- reply-hook [!]pattern command
- send-hook [!]pattern command
- send2-hook [!]pattern command

They sound like what you need.

If you've tried them and they're inadequate, let me know.

**Comment by RichiH** [comment]
I tried ALL(?) the things in the past and got nowhere.

I shall try again, though :)

**Comment by P-EB** [comment]
I currently use something like:

`send-hook '~C .*@internal.example.com' 'my_hdr From: MyName <rih@internal.example.com>'`

The issue is the my_hdr is permanent. So, in my hook file, before this send-hook, I have

`send-hook !'~C .*@internal.example.com' 'unmy_hdr From'`

so my classic email address is used for the other domains.

Keep in mind you might require send2-hook. And place the "unmy_hdr" before, as the hooks are executed in order.
