### ISSUE TITLE
set mime_forward = ask-no     not respected

### ISSUE THREAD

**Issue by Konfekt** [neomutt/neomutt#1127]
## bug reports

The option `set mime_forward = ask-no`  is not respected.

* Expected behavior
It asks for mime forwarding and defaults to no.
* Actual behavior
It always mime forwards.

* Steps to reproduce
Add `set mime_forward = ask-no` to `~/.muttrc`
* Used program versions
NeoMutt 20170421 (1.8.2)
* Operating System and its version
OpenSUSE 42.3

**Comment by flatcap** [comment]
Hi @Konfekt 
Things seem to be working as expected for me.
I've tested all six combinations of `mime_forward`:
- `no` - get inline email
- `yes` - get attached email
- `ask-no` <kbd>\<enter\></kbd> (or <kbd>n</kbd>) - get inline email
- `ask-no` <kbd>y</kbd> - get attached email
- `ask-yes` <kbd>\<enter\></kbd> (or <kbd>y</kbd>) - get attached email
- `ask-yes` <kbd>n</kbd> - get inline email

I've tested the latest version and 20170421.
They were tested with `neomutt -n -F /dev/null` (just the built-in config).

**Comment by Konfekt** [comment]
Ok, it was the command
```
send-hook   .          'push "!mbsync --quiet --push work:Sent >/dev/null 2>&1 &\n"'
```
Do you have a clue why this caused it?

**Comment by flatcap** [comment]
Ooh, that's a good one :-)
I can confirm that I see the same:
```
set mime_forward = ask-no
send-hook . 'push "!echo<enter>"'
```

Here's what's happening:
- Start in the index (or pager)
- <kbd>f</kdb> to foward an email
- 'f' is caught by the index (or pager)
- Question "To:"
- Question "Subject: "
- send-hook is fired, putting "!echo<enter>" into the keyboard buffer
- Question "Forward as attachment? ([no]/yes):"

Now you don't get to answer that because there's already text in the buffer.
- <kbd>!</kbd> (ignored)
- <kbd>e</kbd> (ignored)
- <kbd>c</kbd> (ignored)
- <kbd>h</kbd> (ignored)
- <kbd>o</kbd> (ignored)
- <kbd>\<enter\></kbd> - **answers the question**

An alternative, might be to use the `timeout-hook`:
```
timeout-hook 'push "!mbsync --quiet --push work:Sent >/dev/null 2>&1 &\n"'
```

**Comment by Konfekt** [comment]
Thanks for spelling it out!

Well, the idea of the hook is to sync the sent folder when it was changed by sending an email. Reading the man page, I am unsure it does. Perhaps `fcc-hook` is more appropriate?
