### ISSUE TITLE
Logging: Review all logging messages and their log level

### ISSUE THREAD

**Issue by reisradomil** [neomutt/neomutt#1133]
(This is more a code clean-up thing than really an issue)

I noticed that `mutt_warrning()` isn't used by any code. On the other hand some log messages are flagged as errors (e.g. `key not bound` or `Top of message is shown`) which -- I would say -- are more warnings (or even informational messages) than errors.

It would be an improvement to make this consistent and develop (and document!) some guidelines what type of messages are debug5/.../debug1/messages/warning/errors.

(Note: there is also a perror level which I think are errors from C library functions)

**Comment by flatcap** [comment]
> make this consistent ... (and document!) some guidelines
  
That is a **BIG** job, but one that we can do piecemeal.

Here are the current uses:
- 201 `mutt_perror()`
- 565 `mutt_error()`
- 216 `mutt_message()`
-   0 `mutt_warning()`
- 322 `mutt_debug(1)`
- 243 `mutt_debug(2)`
-  73 `mutt_debug(3)`
-  15 `mutt_debug(4)`
-  49 `mutt_debug(5)`

> I noticed that mutt_warning() isn't used by any code

Yes, that's a new level that I introduced when I updated the logging system.

> there is also a perror level which I think are errors from C library functions

Yes, many of the standard library functions return `-1` on failure and set a global variable `errno`.
`perror(3)` turns that into a localised string.

We need a separate level for this in the code, but the user shouldn't be aware of it.

> guidelines what type of messages are debug5/.../debug1/messages/warning/errors.

Hmm... tricky.

There are a couple of things we can do to improve the logging.
Filter out:
- Progress bar messages
  Having a separate level for these, means they could be displayed, but not saved
- UI messages, such as 'You're on the last message'
  These 'errors' probably need downgrading, too

What are your thoughts?

**Comment by flatcap** [comment]
@reisradomil 
Are you ready for another coding challenge?

**Comment by reisradomil** [comment]
> > make this consistent ... (and document!) some guidelines
>
> That is a **BIG** job, but one that we can do piecemeal.

I'm aware of that. This issue was more intended to point this out and to have a place to discuss it and to keep track of this issue.

> > I noticed that mutt_warning() isn't used by any code
>
> Yes, that's a new level that I introduced when I updated the logging system.

I thought something like that.

> >  guidelines what type of messages are debug5/.../debug1/messages/warning/errors.
>
> Hmm... tricky.

Indeed it is! It's not the first time I think about a good categorisation for log levels but so far nothing satisfying has come up. I once read an article about Java errors vs exceptions (do not confuse this with the Java classes Error or Exception, respectively):

* An *error* is some condition in which the program cannot recover from, e.g. out of memory, some vital data files not found, not run as root, ... and thus has to abort. (A good name for these *errors* would be *panic*)

* An *exception* is a situation where the program can continue to run in a more or less sane way, e.g. a text editor which is asked to open a non-existing file.

Sadly, this does not help in our case as we want to classify the exception case into error/warning/...

> There are a couple of things we can do to improve the logging.
> Filter out:
>
> *   Progress bar messages
>     Having a separate level for these, means they could be displayed, but not saved

In principle a good idea. However, this might also be a opportunity to shoot yourself in the foot. For example if you want to debug your application which crashes at some point during such a progress operation. Then it might be a good idea to look up the latest progress message to have a clue at what point the crash happens and what might be the culprit. So enabling debug messages should also save these messages.

On the other hand, I would sustain to make the distinctions to fine-grained to gave some leeway and to avoid making it to rigid and complex. In my opinion already five debug levels are way to much (but that's not up for debate here).

> What are your thoughts?

As said earlier this is tricky. Following things pop into my mind:

1. a *warning* or *error* is a situation where NeoMutt cannot do the thing it was told to do (either directly or indirectly) by the user.
2. the distinction between *error* and *warning* is that in the former case NeoMutt cannot continue in a sane/expectable way, whereas in the latter case there is a sane/commonly accepted default/workaround.
3. The distinction between *debug* and *message* is often clear but there are cases which are debatable: "Is this still information for the user or is that bit already to much internal"
4. *debug* levels (i.e. *debug1* to *debug5*) are completely up to the developer/code writer.

From these points only the first is a hard criteria. All others are again soft criteria (what is "sane"? what is "unexpected" ...)

Some examples:
* ``key not bound`` would by 1 (user said do something but NeoMutt does not know what it should do) be either an *error* or *warning*. By 2. I can argue that "doing nothing" is a sane thing to do instead. So it should be a warning.
* ``Sorting mailbox``. By 1 clearly not an *error* or *warning*. By 3. I could say its not a *debug* information so be a *message*.
* ``SASL authentication failed`` by 1 either *error* or *warning*. By 2 I would go with *error* in this case as I cannot see a sensible way of continuing.
* ``unknown command`` (when parsing a config file). By 1 clearly an *error* or *warning*. Whether it is a *warning* or an *error* is in my opinion debatable:
  - If it is a typo then ignoring that line and continuing with parsing is a sane thing to do --> *warning*
  - It also be a part of a `if` statement or variable definition, so continue parsing would lead to either even more errors or totally unexpected behaviour (for the user).  --> *error*

**Comment by flatcap** [comment]
Hmm... all good points.

> error is a situation where NeoMutt cannot do the thing it was told to do

It's likely that most of NeoMutt's errors are errors.
By the time something has gone wrong it's too late.
Perhaps there are some situations where we can do better validation (and warn the user) instead.

> warning: sane/commonly accepted default/workaround

A quick grep of the 'error' messages shows quite a few that should be warnings:
- "Threading is not enabled." -- Help the user fix the situation
- "No subject specified." -- Decrease the perceived severity of the situation
- "Search interrupted." -- Feedback for a user-initiated action

---

> > Progress - separate level for these, means they could be displayed, but not saved

> this might also be a opportunity to shoot yourself in the foot
> if you want to debug your application which crashes at some point during such a progress operation

Fair point.
Progress wants to be a _user level_ for display, but a _debug level_ for saving to a file.

> debug levels are completely up to the developer/code writer.
> five debug levels are way too much

How about we define levels 4 and 5:
- Level 4: Progress info: "45% complete", "Entering function X()"
- Level 5: Data: read, written, transferred...
  Only this level may contain private information

We could review the existing levels 4 and 5 and adjust them as necessary.
Levels 1 - 3 would still be at the discretion of the programmer.

---

From my reading on UI design, an error message should tell the user:
1. What the problem is
2. Why it happened
3. What can be done to recover / prevent the error happening again

Cramming that into one line of text is going to be hard.

How do you feel about error codes (like vim)?
`"filename" E212: Cannot open file for writing`

The error code links to either:
- a fuller description of the error
- help on how to perform the action

**Comment by reisradomil** [comment]
> >   error is a situation where NeoMutt cannot do the thing it was told to do
>
> It's likely that most of NeoMutt's errors are errors.
> By the time something has gone wrong it's too late.
> Perhaps there are some situations where we can do better validation (and warn the user) instead.

Good point.

> > debug levels are completely up to the developer/code writer.
> > five debug levels are way too much
> >
> How about we define levels 4 and 5:
>
> *    Level 4: Progress info: "45% complete", "Entering function X()"
> *    Level 5: Data: read, written, transferred...
>      Only this level may contain private information
>
> We could review the existing levels 4 and 5 and adjust them as necessary.
> Levels 1 - 3 would still be at the discretion of the programmer.

That's a sound suggestion.

---

> From my reading on UI design, an error message should tell the user:
>
> 1.    What the problem is
> 2.    Why it happened
> 3.    What can be done to recover / prevent the error happening again
>
> Cramming that into one line of text is going to be hard.

It would be an amazing world if every program would do that (at least partially). Sadly, as of today these programs are more like an exotic blossom than an ordinary flower. Nevertheless, we should try make NeoMutt such a beautiful blossom.

> How do you feel about error codes (like vim)?
> "filename" E212: Cannot open file for writing
>
> The error code links to either:
>
>     a fuller description of the error
>     help on how to perform the action

Actually, I never thought about that. Here's what pops into my mind:

* Unique identifier for the error. Makes it more googleable.
* Numbers are arbitrary and convey no information.
* We can try as hard as we want to keep some consistency in the numbering (e.g. 1xx are IO errors, 2xx are mailbox errors, ...) but in the end I think will be more or less random.
* To make them usable NeoMutt should have some kind of documentation/help system. Either build in or installed on the local hard drive. (I don't like it when I have to look up the manual online.) vim's help system is here again a very good example.

I don't have any special opinion about them. In the end these error codes are nothing else then a linking id between the error and its documentation. We could use the error message itself for that if it is unique (`cannot open file` might depend on the context and thus might not be unique). Spinning this further we could also use some random words for this linking id, e.g.

`E Tiger: cannot open file for writing`
`E Obélix: File too large`
`E Gandalf: Access denied`

These might actually be more memorable for humans than plain numbers.

---

Some absurd idea crept up on me while writing the above:
We can utilize NeoMutt's ability as a mail client for an built-in help as follows: There is a special "mailbox URL" (similar to notmuch, e.g. help://) which opens a (read-only) mailbox. In this mailbox there are messages each belonging to a help topic (titles correspond to subjects, threads can be exploited as subsections, ...). Searching, sorting and the like is already available by NeoMutt's capabilities for mailboxes. The actual mailbox itself is a maildir/mbox mailbox somewhere in /usr/share/doc/neomutt/ or so.

**Comment by flatcap** [comment]
> > Level 4: Progress info: "45% complete", "Entering function X()"
> > Level 5: Data: read, written, transferred...

> That's a sound suggestion.

OK

> Nevertheless, we should try make NeoMutt such a beautiful blossom.

Definitely.  Not long back, I was fixing something and there were two possible methods:
- The Mutt Way : Quick and dirty
- The NeoMutt Way : Thinking about the future

> > "filename" E212: Cannot open file for writing

> * Unique identifier for the error. Makes it more googleable.
> * Numbers are arbitrary and convey no information.

Yes, exactly like Vim.

> (e.g. 1xx are IO errors, 2xx are mailbox errors, ...)
> but in the end I think will be more or less random.

Yes, that'd be a nightmare to plan.

> To make them usable NeoMutt should have some kind of documentation/help system

Yes, I've already been thinking about exactly that.

> `E Obélix: File too large`
> These might actually be more memorable for humans than plain numbers.

hehe.  That's certainly a interesting idea.
There are over 700 errors -- good luck picking that many random words (that aren't offensive in any language :-)

> Some absurd idea crept up on me while writing the above:

They do that, don't they!  Make sure you write down every idea you have.

I keep a list.  It's not for the general public.  https://github.com/neomutt/flatcap-brain-dump
It's unfiltered, unsorted, chaotic.
Once in a while, I read through it and try to connect the dots.

> We can utilize NeoMutt's ability as a mail client for an built-in help

Yep!  I'm already there!  /cc @floand

I was thinking:

1. Convert the guide into markdown
2. Add YML headers, so that
   - The website can display it directly
   - We can add metadata: keywords, error codes, etc
3. Sections are subdirectories / subfolders
4. Install these files in /usr/share/doc/neomutt
4. Create a new mailbox (code) that reads these files
   (as it's readonly, it should be fairly simple)

Extra ideas:
- The "help" mailbox can search by title, metadata, body text
  It would create an index menu of matches
- It would appear in the sidebar like any other mailbox
- Bookmarking a page would be like subscribing to a folder

We'd need some system for links.  As NeoMutt doesn't have a "cursor" like lynx
does, we could number[1] the[2] links[3] instead.

> There is a special "mailbox URL" (similar to notmuch, e.g. help://)

Ooh, I hadn't thought of that.
I think "help" is too generic, it would need to be neomutt://
I wonder how we register that with the desktop?

---

The plan.  Please can you:

Review and adjust:
- 15 `mutt_debug(4)`
- 49 `mutt_debug(5)`

level 3: debugging stuff
level 4: progress
level 5: data or anything private

Alter the progress bar to log at the correct level.

Thanks
