### ISSUE TITLE
Convert Pattern to use STAILQ

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1224]
## Description

Many NeoMutt structures implement their own linked-list type.
The Patterns are simply stored as a long linked list.

`STAILQ` is a singly-linked list with pointers to both the head and the tail.
It's defined in [mutt/queue.h](https://github.com/neomutt/neomutt/blob/master/mutt/queue.h),

**Note**: This isn't too hard, but there are lots of uses of Pattern.

### Part 2: Change all users to match

There are plenty of examples in NeoMutt's code of how to iterate through a list.
For example: [tags.c](https://github.com/neomutt/neomutt/blob/master/tags.c), [tags.h](https://github.com/neomutt/neomutt/blob/master/tags.h)

**Note**: When deleting items, use `STAILQ_FOREACH_SAFE()`

**Comment by yuzibo** [comment]
Hello,
Do we hope move it into "mutt/*" dir at last?

**Comment by flatcap** [comment]
Sort of.
The `mutt` library dir contains **only** functions that are:
- Independent of NeoMutt code
- Tidy and Doxygen documented

There are some dependencies between library files, [as seen in the docs](https://neomutt.org/code/mutt.html), but the library can be compiled and tested separately.

The `test` dir in the source has a growing set of "[acutest](https://github.com/mity/acutest)" test cases.

Each file that we add to the libary makes it easier to understand (and improve) the core of NeoMutt.

**Comment by nnathan** [comment]
I've done a rudimentary implementation. I chose to use the SLIST macros instead of STAILQ since:

1. The features of STAILQ are unnecessary. The linked list is built by appending to the tail (->next) in the original code. There is no need for list concatenat
2. Doesn't justify the slowdown.

I'm frankly unimpressed with switching to SLIST. All the changes made were simple renaming of `pat->next` with `SLIST_NEXT(pat, entries)`. It is difficult to use the SLIST macros properly with SLIST_HEAD(), SLIST_FOREACH, etc. since most of the code passes around `struct Pattern *` as the head of the list instead of an SLIST_HEAD() object. Changing the code to use SLIST_HEAD() would require considerable amounts of refactoring (which I'm open to).

What are your thoughts?

As an aside:
I used this issue as an opportunity to familiarise myself with the BSD queue.h macros. In case anyone ends up finding this issue and wondering how they work I put up a rudimentary example: https://gist.github.com/nnathan/ce79b21797513fc41b9e71a350a1ae0b .
