### ISSUE TITLE
Request: consistent release contents

### ISSUE THREAD

**Issue by jdswinbank** [neomutt/neomutt#127]
What do releases consist of?

Looking at https://github.com/neomutt/neomutt/releases, there seems to be a variety of tarballs produced for each release. Sometimes we just have `neomutt-YYYYMMDD.tar.gz`; sometimes `neomutt-contrib-`, `neomutt-distrib-`, `neomutt-patches-`. To the neophyte, it's not obvious what these are supposed to contain (one can download them and poke about inside, but I can't find it documented anywhere).

So far as I can see, the most practically useful & reliably available download of all is the "source code (tar.gz)". Unfortunately, it never seems to be accompanied by a signed checksum.

Please would it be possible to push out a simple, signed tarball containing everything needed to get up and running with each release? Thank you!

**Comment by flatcap** [comment]
Hi @jdswinbank 

You're right, it's confusing.  Sorry.  I shall try to explain.

### Explanation

In the beginning, there were few features.  Each feature was a separate patch against Mutt and there was a mega-patch combining them all.  This was the "please-everybody" phase of the project.  It was all very thorough and pleasing.  It also took up a fair amount of my time.

Next came the distros -- all the downstream users of NeoMutt.  They all have their own patches.  It made sense for NeoMutt to manage them -- we know the code better.  More patches, more merging, **lots** more time.

I've tried to explain my grand plan to the new developers, but nobody understood -- despite all my diagrams.  So starting with 1.7.0 all the feature branches got dropped (all permanently merged).  No more patches.  Releases no longer take days to prepare.

Now, your choices for trying NeoMutt are all or nothing.  No more pick'n'mix of patches.

The release process for NeoMutt has been fairly uneven -- it should be clear I'm making it up as I go :-)
It should be simpler in future, because there will be fewer options.
Any part of the release cycle that we can automate, we will.

###  Who should be using what?

All normal, non-technical, users of NeoMutt should allow their distro to provide for them.  There are about 9 or 10 distros packaging NeoMutt, most of whom provide updates very soon after we release.

Techies, tinkerers, etc should use git: https://github.com/neomutt/neomutt

### Downloads

> I can't find it documented anywhere

Unfortunately we're a small project, so we haven't documented everything.  We're trying hard, though.

| Filename | Description | Status |
|:--- |:--- |:--- |
| neomutt-YYYYMMDD.tar.gz | The complete NeoMutt source | Maintained |
| neomutt-YYYYMMDD.diff | NeoMutt patch for Mutt-1.7.0 | Maintained (might be compressed in future) |
| neomutt-contrib | Copy of user contributions | Merged, obsolete |
| neomutt-distro | Stacked patches for downstream distros |  Abandoned |
| neomutt-patches | Separate feature patches (against Mutt) | Abandoned |
| source code (tar/zip) | Copy of the source | Automatically generated by GitHub (missing version info) |

> the most ... reliably available download of all is the "source code (tar.gz)". 
> Unfortunately, it never seems to be accompanied by a signed checksum.

It's an automatically generated package of the git repo.
It's missing some version files which we generate at build time.

I **have** signed them in the past, but I've stopped.  They're automatically generated **when** I make a GitHub release.  This means, I have to announce, download, checksum, upload -- which is just a pain.

> Please would it be possible to push out a simple, signed tarball containing everything needed to get up and running with each release?

That will be the "neomutt-YYYYMMDD.tar.gz"
It will always be signed.

However, using git will always be a better solution.

> Thank you!

Thanks for your suggestions.
I'm sure you now have more questions, so ask away :-)

**Comment by jdswinbank** [comment]
Wow — thank you for the swift & comprehensive answer. That answers all my questions for now.

Of course I realise that documentation takes effort, and I didn't mean to complain. Your answer above already goes a long way to addressing the issue.
