### ISSUE TITLE
sidebar mail stats no longer get updated when pager is idle

### ISSUE THREAD

**Issue by sassmann** [neomutt/neomutt#1279]
## Expected Behaviour

sidebar mail stats get updated when new mail arrives and neomutt is idle and pager is open.

## Actual Behaviour

sidebar mail stats only get updated when an action is performed. No new mail notification is triggered when pager is idle.

## NeoMutt Version
NeoMutt 20180622 broken
NeoMutt 20180512 still worked

## settings
set mbox_type=Maildir
set header_cache_backend=tokyocabinet
set mail_check=15

**Comment by flatcap** [comment]
Thanks for the bug report, @sassmann.
I'm not sure what we've done to cause this.  Most of the latest release was translation!

If you have a chance to bisect the problem, it'd be much appreciated.

Thanks.

**Comment by sassmann** [comment]
Bisect points to
184244053 doxy: document buffy.c
This seems weird at first, as this should only be a clean-up. Then I realized a subtle change you probably didn't consider.

```
+bool mutt_buffy_notify(void)
 {
-  if (mutt_buffy_check(false) && BuffyNotify)
+  if (BuffyNotify && (mutt_buffy_check(false) != 0))
   {
-    return (mutt_buffy_list());
+    return mutt_buffy_list();
   }
```
By reversing the check mutt_buffy_check() and BuffNotify in the if statement mutt_buffy_check() never executes when BuffyNotify is zero. However, it is essential to run mutt_buffy_check() before checking BuffyNotify, as mutt_buffy_check() updates BuffyNotify.

Here's the fix:
https://paste.fedoraproject.org/paste/Y4tJycRWt-5jVKTkWpkt-g/raw

Sidenote, why did you at the != 0 check in the first place? It seems superfluous to me.

**Comment by flatcap** [comment]
Argh!  Thanks, merged.

> why did you add the "!= 0" check in the first place?
> It seems superfluous to me.

This is a style thing.
I'm trying to reinforce the types of things.  (that sounds vague :-)

I'd like to only use `!` to test bools and pointers.
Many functions return 0 on success and I'd like the code to be clearer.

My pet peeve is this form:
```c
if (strcmp(var, "string"))
{
  /* Do something */
}
```

You have to know the return type of the function to understand that the 'do something' happens when `strcmp()` fails.
A naive coder reads: "if strcmp is true (succeeds), then do something".

Changing the code to test against 0, reads better (to me).
The `!= 0` now implies that the 'do something' is a failure condition.
```c
if (strcmp(var, "string") != 0)
{
  /* Do something */
}
```

`strcmp()`s an easy one.  We **know** how it works, but there are hundreds of mutt functions that aren't obvious.
