### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [neomutt/neomutt#1329]
The function “[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[mutt_sig_exit_handler](https://github.com/neomutt/neomutt/blob/ea0ce7a60642c943efbd0034b060f08b0997430a/mutt/signal.c#L61 "Update candidate")”.

**Comment by flatcap** [comment]
I've fixed quite a lot of ugly code in Mutt (to create NeoMutt).
But... I haven't got around to looking at the signal handling.

As that function is there to just stop the program, I doubt that `exit(0)` will cause trouble.

I'll make a note (for the distant time when this will matter :-)
Thanks.

**Comment by elfring** [comment]
Can it make sense to leave this issue open until it will be really fixed?

-----

Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/)

**Comment by flatcap** [comment]
> Can it make sense to leave this issue open until it will be really fixed?

If someone's willing to work on it now, then OK, otherwise it could be years.

There are very few active developers, so issues can stagnate and it becomes depressing.
I keep notes of all the proposed ideas, but I like to keep the number of issues low to try to focus development.

> Would you like to consider other software design options?

Consider?  Yes.  But not yet.

The NeoMutt code is still a disaster area...
- hundreds of global variables
- no struct locking / ref-counting
- single-threaded

If you're keen to fix the signal handling, then I'll happily help you (by answering questions).

**Comment by elfring** [comment]
:crystal_ball: The solution possibilities will depend also on your software design preferences, won't they?

**Comment by flatcap** [comment]
hehe, indeed.
I'd be happy with any improvement, but I don't have the time to investigate.

There isn't any design in NeoMutt, atm.
Mutt was 20 years of bolting things on and making it work.
There's a terrible overlap between data and UI.

I'm trying to sort out the object hierarchy so that we can get an MVC model.
But, almost nobody understands the code, so it's slow progress.

**Comment by elfring** [comment]
The reuse of the MVC design pattern would be nice. I am curious if there were previous attempts to use it in [the original software](http://mutt.org/ "Mutt e-mail client").

**Comment by flatcap** [comment]
I haven't seen any evidence of design :-)

There's a global `Context` which represents the current mailbox, but it's used deep within a lot of code.  And it drags UI dependencies with it.

I'm aiming for [this](https://github.com/neomutt/neomutt/issues/1326#issuecomment-416914778)
First I need to insert an object above the mailboxes for all the shared account info.
Then I can start creating 'view' objects.

**Comment by elfring** [comment]
Some software designs were applied already. I guess that the software structure can still be improved at involved places.
