### ISSUE TITLE
Add OAuth2 support for gmail!

### ISSUE THREAD

**Issue by changbindu** [neomutt/neomutt#1362]
Google has moved to blocking apps that are using IMAP/SMTP PLAIN authentication by default. Now google prevents logging in from mutt.

Sine Google strongly recommends IMAP/SMTP protocol users switch to OAuth 2.0, so it is great if OAuth is supported by neomutt.

Some linkes:
http://googledevelopers.blogspot.co.uk/2015/02/reminder-clientlogin-shutdown-scheduled.html
https://productforums.google.com/forum/#!topic/gmail/z4UcNRW5jks
https://unix.stackexchange.com/questions/172666/gmail-blocking-mutt

**Comment by flatcap** [comment]
Actually, it's already there in `master` (the development version).
Upstream added it, but I haven't tried it myself.

There's not much documentation.
I think you need to download [oauth2.py](https://github.com/google/gmail-oauth2-tools/blob/master/python/oauth2.py) from Google.
Then set `$imap_oauth_refresh_command` to the script in NeoMutt.
See also `$pop_oauth_refresh_command` and `$smtp_oauth_refresh_command`

Feedback is welcomed.

The next release of NeoMutt will contain this feature, but...
I'm working on some large changes so that might not be any time soon.

> Google has moved to blocking apps that are using IMAP/SMTP PLAIN authentication by default. Now google prevents logging in from mutt.

Does Google still have the "Allow Insecure Apps" option?

**Comment by changbindu** [comment]
Yes,  the "Less secure app accesss" option is still there but not working now.

Thanks for your information. For oauth2, I think mutt should require client ID and client secret first. I will read the code to find out how to use it.

**Comment by flatcap** [comment]
The patch and discussion happened on the Mutt Dev mailing list ([archive](https://marc.info/?t=153893576200027&r=1&w=2))

**Comment by gahr** [comment]
App passwords still work fine: https://support.google.com/accounts/answer/185833?hl=en

**Comment by changbindu** [comment]
yes, app paasword does work. And if you're having trouble using an App Password, just goto https://accounts.google.com/DisplayUnlockCaptcha to reslove it. App password is the easiest method to login with neomutt.

**Comment by weskerfoot** [comment]
Yeah, in my case I cannot change that setting since I do not have access. I would love the ability to use neomutt for all of my email accounts instead of the crappy web interface ;)

**Comment by mdecaffmeyer** [comment]
For G Suite users, you can actually disable smtp authentication and specify instead which server IPs may send emails. This is what I did and it works. And so I do not have to allow less secure apps.

**Comment by JonnyMako** [comment]
It would be nice to revisit this. Google's oauth2 python script isn't being maintained and hasn't been working with python 3 for a while. But a recent update to openssl broke it. OpenSSL guys relented and reverted the change for this version, but come version 3 of OpenSSL, google's oauth2.py will finally die for good. This is a good time to start thinking about baking oauth2 into mutt. FWIW all other workarounds mentioned in this issue have been efficiently plugged by google, so no good way to access gmail other than using oauth.

Relevant issues:
https://github.com/openssl/openssl/issues/11381
https://github.com/google/gmail-oauth2-tools/issues/21

**Comment by knatsakis** [comment]
> Google's oauth2 python script isn't being maintained and hasn't been working with python 3 for a while.

I was able to replace

```
set imap_oauth_refresh_command = "/opt/gmail-oauth2-tools/python/oauth2.py --quiet --user=$imap_user --client_id=$my_client_id --client_secret=$my_client_secret --refresh_token=$my_refresh_token"
```

with:

```
set imap_oauth_refresh_command = "curl --silent --request POST --data 'client_id=$my_client_id' --data 'client_secret=$my_client_secret' --data 'refresh_token=$my_refresh_token' --data 'grant_type=refresh_token' https://accounts.google.com/o/oauth2/token | jq --raw-output '.access_token'"
```

for accessing Gmail.

I found the instructions here: https://stackoverflow.com/questions/58285683/get-access-token-from-refresh-token-using-curl-google-api

Ref: https://neomutt.org/guide/optionalfeatures.html#6-%C2%A0oauthbearer-support

**Comment by googlebleh** [comment]
Another working config. Posting here since I found this issue while looking for documentation. [Website docs](https://neomutt.org/guide/optionalfeatures.html#6-%C2%A0oauthbearer-support) are still out of date, and the list of supported `smtp_authenticators` in `man 5 neomuttrc` doesn't list [`oauthbearer`](https://github.com/neomutt/neomutt/blob/master/send/smtp.c#L701).

This one is taken from the [mbsync Arch Wiki](https://wiki.archlinux.org/index.php/Isync#Using_XOAUTH2):
```
set smtp_authenticators = "oauthbearer"
set smtp_oauth_refresh_command = "oauth2get com.gmail.2gbleh 2gbleh@gmail.com"
```

**Comment by googlebleh** [comment]
Another working config. Posting here since I found this issue while looking for documentation. [Website docs](https://neomutt.org/guide/optionalfeatures.html#6-%C2%A0oauthbearer-support) are still out of date, and the list of supported `smtp_authenticators` in `man 5 neomuttrc` doesn't list [`oauthbearer`](https://github.com/neomutt/neomutt/blob/master/send/smtp.c#L701).

This one is taken from the [mbsync Arch Wiki](https://wiki.archlinux.org/index.php/Isync#Using_XOAUTH2):
```bash
# values from config below
$ oauth2create '$oauth2_provider' '$from'
```
```csh
set from = "me@gmail.com"
set oauth2_provider = "com.gmail.me"
set smtp_authenticators = "oauthbearer"
set smtp_oauth_refresh_command = "oauth2get '$oauth2_provider' '$from'"
```

**Comment by flatcap** [comment]
@gerazov  That's great!
Would you be willing to create a PR to bundle your script in NeoMutt?
(https://github.com/neomutt/neomutt/tree/main/contrib/oauth2)
Thanks!

**Comment by gerazov** [comment]
With pleasure :slightly_smiling_face: But there is already a Python3 `mutt-oauth2.py` there. I'm not sure what do I need to do?

**Comment by flatcap** [comment]
> I'm not sure what do I need to do?

hehe, I was hoping **you'd** know :wink:

[According to the docs](https://neomutt.org/guide/optionalfeatures.html#oauth), [mutt-oauth2.py](https://github.com/neomutt/neomutt/blob/main/contrib/oauth2/mutt_oauth2.py) is used for Office365, so I think we need both.

Would you mind writing a quick readme for your script?
(feel free to cut'n'paste anything useful from the [other readme](https://github.com/neomutt/neomutt/blob/main/contrib/oauth2/mutt_oauth2.py.README))
Thanks

**Comment by rprimus** [comment]
Sun 12 Jun 2022 05:18:11 BST

`mutt_oauth2.py` *also* handles Office365.

**Comment by flatcap** [comment]
> `mutt_oauth2.py` _also_ handles Office365.

Oh!  Thanks.

@gerazov In that case we don't need your updated script.  Thanks anyway.

**Comment by gerazov** [comment]
Glad to be of service :slightly_smiling_face: but the website needs to be updated not to point to the Google repo - rather to your script.
