### ISSUE TITLE
Startup hangs when machine name not in /etc/hosts

### ISSUE THREAD

**Issue by Knusper** [neomutt/neomutt#141]
I compiled neomutt NeoMutt 2016-09-10 (1.7.0) today (after accounting for #140 by hand) on openSUSE 42.

I used the following './configure' settings, where the compiler flags where set to match the flags used by openSUSEs included mutt (1.5.24) - but removing them alltogether also made no difference:
`--enable-debug --prefix=${HOME}/local/ --enable-sidebar  --enable-hcache --enable-smtp --with-curses=/usr --with-ssl=/usr --with-gnutls=/usr --with-sasl=/usr --with-sasl=/usr --enable-debug  CFLAGS='-Wall -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -I. -D_GNU_SOURCE -fno-strict-aliasing -fPIE -g3 -pipe' 'LDFLAGS=-Wl,--as-needed -Wl,-O2 -Wl,--hash-size=8599 -pie'`

Starting mutt took about 45 seconds.  Here are the first lines from the `.muttdebug0` when running mutt with  `-d 5`:

    [2016-09-11 22:36:17] NeoMutt/20160910 (1.7.0) debugging at level 5
    [2016-09-11 22:36:53] In mutt_reflow_windows

Apparently nothing happened in the  46 seconds between the start and the function call to `mutt_reflow_windows`.

The output from `strace` looks a bit more interesting, although I understand little of it: http://pastebin.com/L3NVMfjU

Nevertheless, with the help of  @flatcap in the IRC, I could fix the 'hang on startup behaviour' by adding `127.0.0.1 machine-name` to my /etc/hosts file.  openSUSE does only add `127.0.0.1 localhost` and some IPv6 related stuff.

I'm not sure if this is a neomutt bug, or an openSUSE issue, or maybe I have to alter something in the way I'm compiling mutt.  But I open an issue, since I did not run into this problem with mutt 1.5.24, so that the neomutt-devs can respond and that other openSUSE users trying to compile neomutt do find the above workaround / fix.

**Comment by flatcap** [comment]
The code is getting stuck when it calls **getaddrinfo()** to get the machine's **canonical name**.
This call has been in Mutt since 2013 and hence all versions of NeoMutt.

The function triggers a lookup in `/etc/nsswitch.conf`, mine looks like this:
```
hosts:      files mdns4_minimal [NOTFOUND=return] dns myhostname
```

The part that's taking the time is `dns` but you clearly can't remove that.
The reason the "fix", I suggested, works is that the `files` entry (/etc/hosts) comes before `dns`.

Something in your OS has changed.
When I had the same problem, I think it was because Fedora introduced a local DNSSEC-aware resolver.
(though I couldn't repeat the problem with a fresh install).

Sorry, there's nothing I can do.

If openSUSE can come up with a better solution please let us know.

**Comment by Knusper** [comment]
Well, OK.  So **gettadrinfo()** is calle

If I use the mutt 1.5.24 that comes shipped with the distro, this hang does not occur. Here is how they built it
https://build.opensuse.org/package/show?project=openSUSE%3ALeap%3A42.1&package=mutt

So far I  can see nothing in their way of building their binary package that would alter the behaviour in order for this not to happen.  I'll investigate.

**Comment by Knusper** [comment]
OK - for me 20170428 still hangs on 
`getdnsdomainname timeout` when trying to start.  I'm willing to help with debugging.

**Comment by l2dy** [comment]
@Knusper It stuck here: https://github.com/neomutt/neomutt/blob/neomutt-20170428/init.c#L3876.

If you want to avoid the timeout, use `./configure --with-domain=DOMAIN` when building neomutt or add your machine name to `/etc/host`.
