### ISSUE TITLE
IMAP: 'neomutt -f =foo/bar' opens the foo mailbox

### ISSUE THREAD

**Issue by EdwardBetts** [neomutt/neomutt#1438]
I expect that running `neomutt -f =foo/bar` will open the 'foo/bar' mailbox, instead neomutt opens the 'foo' mailbox, or complains if 'foo' isn't a mailbox.

This problem is only being triggered for me when using IMAP. Reading local Maildir mailboxes with neomutt works fine.

I ran git bisect and it says d6e6635 is when this change happened.

Here's some example settings from muttrc
```
set folder=imap://edward@localhost/
mailboxes =foo/bar
```

**Comment by gahr** [comment]
Is this still an issue? Are you sure the IMAP delimiter on the server is `/` and not `.`?

**Comment by gahr** [comment]
Got that. I can reproduce it.

**Comment by gahr** [comment]
This is due to `imap_fix_path` assuming a delimiter of `\0`, because `adata->delim` is `\0` here

https://github.com/neomutt/neomutt/blob/13512592274a96e08ac5532ed7d11318027b2bdd/imap/util.c#L793

With a default `ImapDelimChars` of `/.`, each one of those characters is substituted with a `\0`, effectively terminating the string at the first delimiter.

I'm working on a fix, which I think might be to not fix the path at all if the delimiter is `\0`.
