### ISSUE TITLE
Dovecot Docker for testing NeoMutt

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#1439]
We need some better ways to test NeoMutt.  Docker could really help here.

We'd like a Docker instance of Dovecot.
That would allow the developers to perform the same tests (as each other) and share sample data.  Then we could get Travis to perform automated tests of NeoMutt.

The Dovecot install doesn't need to be complicated, it just needs a few accounts and a way to create new mail and examine existing mail.

Ideally, the mail store would be outside of the Docker, so that our test scripts could perform actions on the mail.

**Comment by tecepe** [comment]
I've talked to @flatcap about this sometime ago, and I started to work on a docker solution. I'm in the middle of the way: I found a suitable docker image with Dovecot out of the box and I was able to use my own configuration files and so on. The problem is that my configuration files are not working well.  I believe that I'll be able to work around it soon. If someone else is interested on this, please let me know. =)

**Comment by flatcap** [comment]
Implemented in [test-docker](https://github.com/neomutt/test-docker.git).
