### ISSUE TITLE
Translation input

### ISSUE THREAD

**Issue by P-EB** [neomutt/neomutt#158]
The code moved a lot, the translation files did not that much.

We should take care of it, in a specific branch.

Help welcome!

Basically, we can regenerate .po files using make in the po/ directory, then, we have to fill missing translations. It should be enough.

**Comment by flatcap** [comment]
OK, let's get things started.
**To do**:
- [X] Create a branch
- [X] Update po files -- `make -C po update-po`
- [X] Add British English translation :-)
- [ ] Find and fix all unmarked strings
  - All strings presented to the user should be surrounded by a gettext function `_()` or `N_()`
- [ ] Merge vvv's [Russian translation](http://mutt.org.ua/download/current/patch-1.7.0.vvv.nntp_ru.gz)
- [ ] Fix warning in the po files
  - Missing/empty headers

Once we've got these bits done, we can start asking for help on the actual translations.
**Ask for help**:
- User mailing list (get them involved/engaged)
- Web news post
- IRC - pester people :-)

**Jobs**:
- Check the "fuzzy" translations
  - A translation is marked "fuzzy" when the compiler has seen lots of changes since the last update.  It cannot be certain that this is the correct translation string.  Most times, it will be.
- Fill in the empty "msgstr" message strings
  - There are plenty of tools to help automate this task, e.g. `poedit`

Among the NeoMutt regulars, we speak:
- [ ] English
- [ ] French
- [ ] German
- [ ] Dutch
- [ ] Estonian

After these languages are complete, I suggest creating a page with a table of translations and their %age completion.

**Comment by pickfire** [comment]
@flatcap Nice, I speak Chinese here.
