### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by magnetophon** [neomutt/neomutt#1691]
There have been 1739 commits to master since the last release.
Packagers would rejoice!

**Comment by mschilli87** [comment]
@magnetophon: Have a look at https://github.com/neomutt/neomutt/issues/1326. There have been some major changes in architecture and others things (testing, etc) that inflate the number of commits since the last release. At the same time, refactoring is also more likely to cause regressions than adding new features. I hope this explains the delay of the next release.

Note that this was also announced on the same page I guess you got the 1739 commits count from: https://github.com/neomutt/neomutt/issues/1326

**Comment by magnetophon** [comment]
Ah, yes, it was indeed announced there.
Sorry for the noise!
