### ISSUE TITLE
How to delete mails in virtual mailbox

### ISSUE THREAD

**Issue by weilbith** [neomutt/neomutt#1736]
The question is quite simple: How do I delete a message within a `virtual-mailbox`.

I'm at the index and mark mails to delete via the defaul `d` (`delete-message`) key. They get visually marked. If I use `$` to manually `sync-mailbox` nothing happens. Probably make sense, cause it is a virtual mailbox. If I switch the virtual mailbox, I get the status message that all messages are kept and `0` deleted.
So how can I make these marked mails to become actually deleted?

**Comment by weilbith** [comment]
Any hint? :/

**Comment by jindraj** [comment]
I'm not deleting messages at all. I just add tag:trash and remove tag:inbox. Maybe some with more experience with virtual mailboxes would know. But I have a macro idea.

pipe message, get message-id, and then execute shell `rm $(notmuch search --output=files  id:5d1c9266.1c69fb81.df331.54daSMTPIN_ADDED_BROKEN@mx.google.com)`

**Comment by Austin-Ray** [comment]
`notmuch` does not provide a way to delete an email since it operates on the principle of not modifying your mail[0]. So you can't really delete your email, but you can hide it in `virtual-mailboxes` by tags.

`neomutt`'s `notmuch` backend has the `nm_exclude_tags`[1] variable which lets you set tags to ignore in all `virtual-mailboxes` statements (you can directly query exclude tags with `vfolder-from-query`.) 

We can combine `nm_exclude_tags` with two small macros to achieve "deletion" in `virtual-mailboxes`.

```rc
set nm_exclude_tags=deleted

macro index d "<delete-message><modify-tags-then-hide>+deleted<enter>"
macro index u "<undelete-messsage><modify-tags-then-hide>-deleted<enter>"
```

This configuration sets exclusion of the `deleted` tag then overrides the default behavior of `d` and `u` to add/remove the excluded tag. It should work on both regular and virtual mailboxes.

If you want to delete the physical file, @jindraj has provided a good starting point. The Arch Linux wiki has a small section for physically deleting notmuch files[2] for additional reference.

[0] https://notmuchmail.org/excluding/
[1] https://neomutt.org/feature/notmuch#4-%C2%A0variables
[2] https://wiki.archlinux.org/index.php/Notmuch#Permanently_delete_emails

**Comment by weilbith** [comment]
I would rather go for actual deleting. I haven't tried @jindraj his suggestion, but it looks promising to me. :+1: 
@Austin-Ray thanks for the exhaustive explanation and links!

**Comment by jindraj** [comment]
Maybe the better idea is to implement your own trash with automatic deletion like GMail has.
Just tag messages you want to delete with some tag. Lets say `bin`.

Then there is multiple options:
- periodic cron job
- post sync hook in offlineimap or other tool you use (runs too often)
- pre-new notmuch hook (runs too often)
- neomutt macro with shell script

```sh
notmuch search --output=files --format=text0 tag:bin date:..$(date -d '1 months ago' '+%Y-%m-%d') | xargs -0 rm
```
For bsd date use: `date -v-1m '+%Y-%m-%d'`
You can also add `notmuch new` at the end of the script If you want notmuch to remove messages from its database right away.

It does the search for all messages taggeed `bin` older than 1 month. So even if you tag some messages by mistake, you should be able to fix it.
