### ISSUE TITLE
Subject lines containing emojis dont truncate properly

### ISSUE THREAD

**Issue by Fybe** [neomutt/neomutt#1741]
Emojis (double width characters) seem to be treated as single width characters. If the subject line is longer than than the index width, the last character overflows to the next line. If it doesnt overflow, the last character remains on screen if a mail is opened.

![1560083973](https://user-images.githubusercontent.com/11479663/59159358-cc77b400-8ac8-11e9-92a1-067fd2558029.png)

My locales:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I checked with `neomutt-20180716` as well as `master`.

**Comment by flatcap** [comment]
Sorry, I can't repeat this.
I've tried a few different emojis and a couple of different terminals (gnome-terminal and konsole).

Gnome-Terminal has a profile setting: 'Ambiguous-width characters' -- mine's set to 'Narrow'.
If that's set to 'Wide' messes up my display when the sidebar's visible.

Does the problem still occur if the sidebar is disabled?
How about if you `set sidebar_divider_char='|'`  (pipe char - shift-\ )

Try saving one email locally, then running NeoMutt with just the default settings.
```
s~/test.mbox<enter>
```

```
./neomutt -n -F /dev/null -f test.mbox
```

**Comment by sjhoran** [comment]
I also occasionally see this issue.

I did some testing with different settings and discovered that this bug only occurs when running neomutt within GNU screen. I don't see this behaviour when running neomutt within tmux or on a standard login terminal outside of a terminal multiplexer.

I tested with PuTTY on Windows 10 ssh'ing into a FreeBSD 11 machine. I also tested with the terminal that comes with CYGWIN. Both exhibited the same quirk.

I don't know if this issue is within neomutt or screen, but hopefully this will help you in reproducing it if you want to investigate further.

**Comment by sjhoran** [comment]
A little further information...

neomutt in the FreeBSD ports collection defaults to using ncurses, and that's what all the above mentioned testing was done with.

Compiling using slang instead of ncurses made the problem go away entirely for me.

Testing done with neomutt-20200501
