### ISSUE TITLE
setting Content-type in multipart/alternative messages

### ISSUE THREAD

**Issue by noahrama** [neomutt/neomutt#1792]
Setting Content-type using the code below produces this bash bash error:

```
Error in command line: boundary=8ec29bd4d64fb9d9e0485582dd6fef5f536c14538b8dc4f0: unknown command
```
Attempts to escape the semi-colon have failed:

```
"my_hdr ${content_type/;/\\;}"      --failed
```

Attempts to "set content_type" have also failed:

```
echo "$body" | neomutt -e "set content_type='$content_type'" -s "$subject" "$recipient" 
```
The mail will send, but the headers are screwed up. Can anybody spot what i am missing? 

```
#!/bin/sh
# using mutt, send a mixed multipart text and html message:

usage() {
    echo "error: $1"
    echo "usage: $(basename $0) -s subject -r recipient -h htmlfile"
    exit 1
}

htmlfile=""
subject=""
recipient=""

while getopts "s:r:h:" opt; do
    case $opt in
        s) subject="$OPTARG" ;;
        r) recipient="$OPTARG" ;;
        h) htmlfile="$OPTARG" ;;
        ?) usage "invalid option: -$OPTARG" ;;
    esac
done
shift $((OPTIND-1))

[ -z "$recipient" ] && usage "no recipient specified"
[ -z "$htmlfile" ] && usage "no htmlfile specified"
[ ! -f "$htmlfile" ] && usage "no such file: $htmlfile"

boundary=$(openssl rand -hex 24)
textfile=$(elinks --dump "$htmlfile")
content_type="Content-type: multipart/alternative; boundary=$boundary"

##
body=$(cat - << END

--$boundary
Content-Type: text/plain; charset=ISO-8859-1

$(cat <<< "$textfile")

--$boundary
Content-Type: text/html; charset=ISO-8859-1

$(cat "$htmlfile")

--$boundary
END
)
##

echo "$content_type"
echo "$body" | neomutt -e "my_hdr $content_type" -s "$subject" "$recipient"
```

**Comment by gahr** [comment]
You'll need to escape the semicolon

```sh
content_type="Content-type: multipart/alternative\; boundary=$boundary"
```

but that won't be enough, because the order of operations when constructing the email to send is:

1. Add MIME-related headers, [sendlib.c:2362](https://github.com/neomutt/neomutt/blob/master/sendlib.c#L2362)
2. Add custom headers, [sendlib.c:2384](https://github.com/neomutt/neomutt/blob/master/sendlib.c#L2384)

This results in a file with duplicated content-type:

```
Date: Thu, 22 Aug 2019 11:20:03 +0000
From: Pietro Cerutti <gahr@gahr.ch>
To: gahr@gahr.ch
Subject: Test
Message-ID: <20190822111918.w4mxppiqg4xsgdxr@ptrcrt.ch>
Reply-To: Pietro Cerutti <gahr@gahr.ch>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Disposition: inline
Content-type: multipart/alternative;
 boundary=76aa9a3ef600b76f4ac159a888734017a0013b416324c940

Test
```

which my system understands as spam, because of MULTIPLE_UNIQUE_HEADERS.

Potentially, we could change the order of insertion, keep track of user-headers, and avoid emitting a certain subset of headers (we would need to know which ones are supposed to be unique) if they are overridden by user a user header. It sounds convoluted and I'm not certain I understand all consequences, though.

**Comment by gahr** [comment]
Oh, and by the way, the last boundary will need to be terminated:

```
----$boundary
```

**Comment by gahr** [comment]
@noahrama with NeoMutt master and the suggested fixes, your script works fine now.
