### ISSUE TITLE
Create a new variable $net_folder_format

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#181]
`$folder_format` is used for both local file/dirs and network mailboxes, such as
IMAP.  If you have multiple mailboxes, some local, some remote, then 

I'd like you to introduce a new variable `$net_folder_format`
If the mailbox is remote and this variable is set, then use it to format the
folder information.  If the variable isn't set, then default to `$folder_format`

Local mailboxes use `$folder_format` as normal.

---

**Easy tasks would be perfect for someone new to NeoMutt.**
You won't need to write lots of code, and you won't need any previous knowledge
of the NeoMutt code.  Obviously, you will need to be able to write C code :-)

**Easy tasks also come with a mentor** -- a NeoMutt project member -- who will help
you learn what you need to complete the work.

If you're interested in having a go, leave a comment or speak to us in our
IRC channel: #neomutt on irc.freenode.net

Thank you :heart:

**Comment by toogley** [comment]
@flatcap Should the new variable also use a global variable like `folder_format`'s [FolderFormat](https://github.com/neomutt/neomutt/blob/master/globals.h#L55) ?

**Comment by flatcap** [comment]
Yes.  This is the simple fix.

The bigger (better) solution would be to refactor the browser to move a lot of the code into the mailboxes.
For each mailbox type, (e.g. maildir, imap, notmuch) work out what they'd want to display, then create a browser that knows nothing about its data.

**Comment by toogley** [comment]
(I'm woring in [devel/net-folder-format](https://github.com/neomutt/neomutt/tree/devel/net-folder-format) on it, but am not finished yet.)

**Comment by toogley** [comment]
On IRC, @flatcap and I discussed about `browser.c` and in particular the `folder_format_str()` method. I was proposing an extra method `net_folder_format_str()` and for handling the shared fields (field for Message of unread messages, etc.) in one method per field. The result would be an enormous list of small functions, so this post tries to collect the amount of those small functions. I think, small functions are more readable and this way we can also cut the very big method folder_format_str() a bit down.


**Note However**: This can only be an estimation. As i've made this list, i've seen multiple fields which seem similar (for instance: %n of pgp_entry_format and %C of e.g. folder_format), but i don't know if the implementation can actually be made shared. Furthermore, i'll try to extend this list in the future.

### multiple format definitions (two or more)

*(by "entry", i mean sth like a mailbox, a newsgroup or similar)*

* entry number  %C  (shared by NNTP, IMAP, local)
* amount of new messages %n (shared by NNTP, IMAP, local)
* has new messages %N (shared by NNTP, IMAP, local)
* absolute amount of messages %m (shared by NNTP, IMAP, local)
* %>X (shared by NNTP, IMAP, local)
* %|X (shared by NNTP, IMAP, local)
* %*x (shared by NNTP, IMAP, local)
* size of entry %s (shared by NNTP, IMAP, local)
* date using date_format %D (shared by NNTP, IMAP, local)
* entry name %f (shared by NNTP, IMAP, local)
* is tagged %t (shared by NNTP, IMAP, local)

### folder_format

* %d  (shared by NNTP, IMAP, local)



------------------------------


As an alternative, @flatcap was proposing a  `shared_format_str()` method which should return bool : true == I handled it, false == I didn't. The caller would check *its* format letters first allowing it to override the shared ones. 

If the notmuch or nntp versions did something different with %X (made up), they could do so. even if %X was share by other format strings. if there are more than two callers of the shared function, then it can be both shared and overridden, therefore.

**Comment by toogley** [comment]
@neomutt/reviewers do you have an opinion about the above design decision? (`shared_format_str()` vs lots of method for each shared field)

**Comment by charles2910** [comment]
Hi, I've seen some work here before. Is this issue still open to newcomers? I'd like to contribute to neomutt (my everyday mail reader)

**Comment by flatcap** [comment]
Welcome to NeoMutt, @charles2910!

> Is this issue still open to newcomers?

Yes and we'd appreciate your help :-)

The code has changed quite a lot since this issue was opened, but the task is the same.
I'd like to add another step to move the config, to match the other libraries.

## Move the browser config

NeoMutt's divided up into separate libraries.
Some of these define their own config, e.g. [Sidebar's config](https://github.com/neomutt/neomutt/blob/main/sidebar/config.c#L54=)

These config variables are only used by the browser:
- `browser_abbreviate_mailboxes`
- `folder_format`
- `group_index_format`
- `show_only_unread`
- `sort_browser`
- `mask`

Move them into a new file `browser/config.c`
This commit 1f517034f did the same thing for the menu library.

## Create a new config variable

Create `net_folder_format` in `browser/config.c` and add some docs to `docs/config.c`
Much of that can be copied from the `folder_format` entries.
Pick a default value that's appropriate for a Mailbox.

## Enable the new config variable

The browser is started by `mutt_buffer_select_file()` in `browser/browser.c`
It's managed by [`struct Menu`](https://github.com/neomutt/neomutt/blob/main/menu/lib.h#L68=).

The browser defines a function to format each line of the display:
https://github.com/neomutt/neomutt/blob/main/browser/browser.c#L1309

That function calls a formatting routine.
(this is probably where you want to make a change)
https://github.com/neomutt/neomutt/blob/7df877bf67f8eb8e33473fad380846436943b143/browser/browser.c#L830-L853

(and this huge function does the work of turning `%m` into the number of messages, etc)
https://github.com/neomutt/neomutt/blob/7df877bf67f8eb8e33473fad380846436943b143/browser/browser.c#L231-L234

---

It's a lot to take in, so have a look through the code and ask lots of questions (either here or on IRC)
IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))

There's a load of useful [development info on our website](https://neomutt.org/dev).

**Comment by charles2910** [comment]
I'm having trouble to connect to irc today, not sure what's happening. Anyway, I did the first task - moving the configs to libbrowser  ([commit 019107b](https://github.com/charles2910/neomutt/commit/019a07b9c0c3ddfd3ae39465644953b050996981)).

I think it'd be better discuss this in irc, but I still can't connect so here it goes.

My initial idea would be to add another if statement in `folder_make_entry()` to check if it's an imap mailbox (`folder->ff->imap` right?) and if $`net_folder_format` is defined. Since it would need to see the `imap` variable that is only defined with `USE_IMAP`, I think this if statement would need to be inside an `#ifdef USE_IMAP` too.

Ok, this is my initial idea, do you think I'm in the right direction or is there something I need to change?

**Comment by flatcap** [comment]
> I did the first task

Great.  It's nearly perfect (it doesn't compile :-) -- I've left a couple of comments.

> add another if statement in `folder_make_entry()`

Sounds good

> check if it's an imap mailbox (folder->ff->imap)

Hmm... that'll do to start, but we probably want to check using the `Mailbox`.
If we have that, or its type, e.g. `MUTT_IMAP`, then we could use `mx_get_ops()` and `bool MxOps.is_local`

See if you can spot an easy way to get the info
(I haven't looked yet, so don't worry if it's not obvious)

**Comment by charles2910** [comment]
> > I did the first task
> 
> Great. It's nearly perfect (it doesn't compile :-) -- I've left a couple of comments.

Fixed that and tested the compilation. Seems to be working now.

> > check if it's an imap mailbox (folder->ff->imap)
> 
> Hmm... that'll do to start, but we probably want to check using the `Mailbox`. If we have that, or its type, e.g. `MUTT_IMAP`, then we could use `mx_get_ops()` and `bool MxOps.is_local`
> 
> See if you can spot an easy way to get the info (I haven't looked yet, so don't worry if it's not obvious)

I think that `get_current_mailbox()` should give us the mailbox. As far as I can tell, it can be called from anywhere and should return a mailbox (although I'm testing with gdb and, during neomutt initialization, it doesn't).

**Comment by flatcap** [comment]
> Fixed that and tested the compilation

Thanks.  Merged: b461f11bc

Meanwhile, I've had a bit of a crisis!
The more I look at the browser, the less I'm sure about `$net_folder_format`.
What if the user has a **mix** of local and remote mailboxes.

I'm starting to think that `$mailbox_folder_format` would make more sense.
When you attach a file, or navigate a maildir mailbox, then you'd use `$folder_format` (like the output of `ls -l`)
When in "mailbox" view, we'd use `$mailbox_folder_format` (names, descriptions, type).

The first thing we need to do is pass more info to `folder_make_entry()`.
The `Menu` is set up here:
https://github.com/neomutt/neomutt/blob/b461f11bcf84c7c5d116429e67a1ec04cdfb5749/browser/browser.c#L1309
and here:
https://github.com/neomutt/neomutt/blob/b461f11bcf84c7c5d116429e67a1ec04cdfb5749/browser/browser.c#L1341

Currently, we pass a pointer to the `entry` array:
https://github.com/neomutt/neomutt/blob/b461f11bcf84c7c5d116429e67a1ec04cdfb5749/browser/lib.h#L102-L110

I think we should pass the entire `struct`.
Then `BrowserState.is_mailbox_list` wouble be available to `folder_make_entry()`.

---

While you're playing with the browser, have a think about how else we might improve it.

A simple addition, might be colour.  What should we add colour to?
Have a look at how the Index and Sidebar are coloured for ideas.

**Comment by flatcap** [comment]
@charles2910 Busy?  or need a hint?

**Comment by charles2910** [comment]
> @charles2910 Busy? or need a hint?

Yeah, I started to take a look at it on Saturday, but I'm traveling since sunday morning and it has been quite difficult to manage everything. Though for the next days I think I'll be able to spend a couple hours per night on this (and I'll be on ther irc - I'm on gmt timezone).

So, following what you are proposing, we would use `$mailbox_folder_format` for all mailbox that `MxOps.is_local` is false, right? (That would be imap, nntp - though it uses `group_index_format` -, notmuch and pop)

I'm not very good in color choosing and I don't use the browser as much (I don't have a very unusual setup, only IMAP for now). So I think we could ask other user (and developers) for their opinion on this matter.

**Comment by charles2910** [comment]
Hi, it's been a while. Sorry about that, life got a little messy.

I took a close look in your comment and agree that `mailbox_folder_format` makes more sense.

You provided enough information, I just had to do a little digging and testing to understand when the browser was called and all.

So, I've followed your advice and passed the entire struct to `folder_make_entry()` so `is_mailbox_list` is accessible from the function and we can use it in an if statement - the commit is 51fb91d00ed2a638d3c27ec0dce6c30189cc8d49. I've set `mailbox_folder_format` to the following `"%2C %t %N %6n %6m %i"` which looks like this:

![Screenshot from 2022-05-24 23-34-34](https://user-images.githubusercontent.com/34252251/170329632-ea3f66c0-9577-4af3-a798-f5f15e0548b2.png)

This is a default value that works for me (imap use only), so I'd like to know if you have any other suggestions - that may be more sane for most use cases.

A small question: the documentation says that `%m` and `%n` need `mail_check_stats` set. What happens when it's not set? Will it mess up the browser?
