### ISSUE TITLE
Problem: resize xterm closes imap folder

### ISSUE THREAD

**Issue by jsmr1** [neomutt/neomutt#1869]
Since some weeks i found that if I resize the xterm the open imap folder is mostly closed.  I can change to the same folder or an other again, so the imap session may remain intact.  

I use LMDE and NeoMutt 20170113 (1.7.2).
System: Linux 4.9.0-11-amd64 (x86_64)
libidn: 1.33 (compiled with 1.33)
hcache backends: tokyocabinet

**Comment by flatcap** [comment]
Sorry to hear that @jsmr1 (and sorry for the slow reply).

I haven't heard of this problem before.
Resizing the terminal sends a signal to NeoMutt, whereupon it repaints.

We have heard of some strange interactions with screen/tmux, though.

> Since some weeks

What happened back then?
Did you upgrade your NeoMutt?  Terminal?  Did your email server change?

Does the same thing happen with other terminals?
How about a different window manager?

I'm interested to know the answers, but unfortunately my advice is going to be the same:
If possible please upgrade NeoMutt to the latest version: 2018-07-16.
(a lot of fixes happened since your version)

**Comment by jsmr1** [comment]
> We have heard of some strange interactions with screen/tmux, though.
> 
> > Since some weeks
> 
> What happened back then?
> Did you upgrade your NeoMutt? Terminal? Did your email server change?

Do the usal upgrades. I think xterm would not have changed, maybe Neomutt I use LMDE Cindy.
On the IMAP Server is LMDE Betsy unchanged the last half year.  

> Does the same thing happen with other terminals?

Now I use mate_terminal, this is more stable, the disconnects are more rare.  I also tried gnome_terminal, seams also better.  

> How about a different window manager?

Never changed since the change from fvwm1 to fvwm2 :-)

> If possible please upgrade NeoMutt to the latest version: 2018-07-16.
I heard that a new lmde is coming. For compiling from sources I have not enougt time.

**Comment by roccoblues** [comment]
Hi, I'm trying to cleanup some older issues here. Can you still reproduce this behavior with the latest version? Thanks!

**Comment by jsmr1** [comment]
Please close it. I can't reproduce it now.

Thanks for the work.

Am 21. Dezember 2023 09:10:01 schrieb Dennis Schön ***@***.***>:
