### ISSUE TITLE
Unexpected behavior when using virtual_spoofile.

### ISSUE THREAD

**Issue by hurricanehrndz** [neomutt/neomutt#197]
If using the option `set virtual_spoolfile=yes` which enables virtual folders, macros that employ `<toggle-mailboxes>` produces unexpected results, rather than having the folder browser appear.

**Comment by flatcap** [comment]
The problem happens in the browser, in combination with virtual folders (notmuch).
This macro triggers the bug:
```
macro index C "<copy-message>?<toggle-mailboxes>" "copy a message to a mailbox"
```
`<copy-message>` gives you a browser prompt, but `?` fails, then the rest of the macro is interpreted as keystrokes.

git bisect tells me that the bug was introduced in e0cb84c -- sensible browser patch
