### ISSUE TITLE
Backspace while editing any header field wraps around

### ISSUE THREAD

**Issue by eku** [neomutt/neomutt#2002]
## Expected Behaviour

While editing any header field I'm using backspace to delete a character.

## Actual Behaviour

When all characters are deleted the contents of the line is restored and cursor is again at the end.

## Steps to Reproduce

Finish editing an email. Edit Subject: or To: line. Delete all characters with backspace and press backspace again.

## How often does this happen?

- Always

## When did it start to happen?

- When I upgraded

 I'm not sure, but AFAIR with 2019 version. 2018 was good.

## NeoMutt Version

neomutt-20191111-1.fc30

## Extra Info

* Operating System and its version
Fedora 30
* Were you using multiple copies of NeoMutt at once?
No
* Were you using 'screen' or 'tmux'?
Yes, screen
* Is your email local (maildir) or remote (IMAP)?
mbox

**Comment by flatcap** [comment]
> wraps around

Sorry, I'm not sure I understand.

When I hit <kbd>Backspace</kbd> on an empty field, it cancels the prompt.
This **is** a new feature.  It gives the user a simple way to escape from a question.

Before, your choices were:
- <kbd>Ctrl-G</kbd> -- poorly documented and not easily discovered
- <kbd>Ctrl-C</kbd> -- which asks if you want to exit NeoMutt

Now, deleting everything + one more <kbd>Backspace</kbd> allows you to change your mind
(but, it still allows you to enter an empty string, if you wish).

**Comment by mschilli87** [comment]
@flatcap: I guess I'd try <kbd>Esc</kbd> in that case first rather than <kbd>Backspace</kbd>.

**Comment by flatcap** [comment]
> I guess I'd try <kbd>Esc</kbd> in that case

Yes.  Someone [suggested that](https://github.com/neomutt/neomutt/issues/1510) a while back.
Unfortunately, it's not as simple as it sounds.
Many function keys, etc, generate a sequence of characters containing escape.  To distinguish them isn't trivial.

**Comment by eku** [comment]
Well, I mean that menu before sending the email. It shows From: , To:, Subject: and other lines. If you press S to edit the subject the cursor is at the end. If you then keep pressing backspace to delete the characters left from the cursors. If the last chararacter has been deleted and you press backspace again it fills the field with the original text and the cursors is at the end again. This is IMO pretty anoying when you use autorepeat from the keyboard. It does not stop at the beginning.

**Comment by flatcap** [comment]
Weird.  I've never seen anything like that.
Can you try running without any config to see if it still happens: `neomutt -n -F /dev/null`

> If you press S to edit the subject the cursor is at the end.

OK, you should now get the prompt on the bottom line of the screen.
With the cursor at the end.

`Subject: this is the very long subject`

> If you then keep pressing backspace to delete the characters left from the cursors.

OK, so the last few things you see should be:

`Subject: thi`
`Subject: th`
`Subject: t`

then nothing

> If the last chararacter has been deleted and you press backspace again
> it fills the field with the original text and the cursors is at the end again.

That really confuses me.
I can't think how I might have caused that.

As a workaround for clearing the prompt, you can use <kbd>Ctrl-U</kbd>

**Comment by flatcap** [comment]
Have you tried running without any config to see if it still happens: `neomutt -n -F /dev/null`

**Comment by eku** [comment]
@flatcap Without a configuration the behavior is different, but still different than in the 2018 version. After deleting the last character and pressing backspace again the edit mode of the header is left instead of stopping at the beginning and waiting for input.

**Comment by flatcap** [comment]
> After deleting the last character and pressing backspace again
> the edit mode of the header is left

OK, that's the behaviour I was expecting.

Please can you try to work out which of your config is causing the strange behaviour.
Thanks

**Comment by akorn** [comment]
I get slightly different and even more annoying behaviour, even with `mutt -F /dev/null`:

When neomutt prompts for something (e.g. To: address, Subject etc.) it previously was possible to just keep pressing backspace until whatever default text was there disappeared.

As of this version, it's possible to keep erasing back beyond the first character of the string; for example, when composing mail, backspacing beyond the beginning of the offered Subject brings up the editor with the message being composed; saving and exiting shows that the Subject is in fact not empty but the default (e.g. "Re: original subject").

Backspacing beyond the beginning of the To: prompt likewise confirms the default To: address and goes to the Subject prompt.

This behaviour is completely counter-intuitive and hopefully not intentional.

In https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=945442, someone else also said: "when saving a bunch of tagged messages, and backspacing too far when attempting to change the destination folder, the messages will be saved to the default (save-hook) folder for the first tagged message. If the user is unaware of this bug, the user may not know what has happened or where the messages have gone."
