### ISSUE TITLE
Tag messages from sender of the current mail

### ISSUE THREAD

**Issue by Sweenu** [neomutt/neomutt#2050]
Hello !
I'd like a way to tag all messages from the same sender as the sender of the mail currently selected in my index.
There's the `<display-address>` function but it only displays the address. How could I store the address to use it in a macro?

I tried several things and carefully read the whole documentation but couldn't find anything to help me do that.

**Comment by jindraj** [comment]
Similar functionality was discussed here: https://github.com/neomutt/neomutt/issues/1636

In the config file setup a macro with <pipe-message> getting the sender from the message similar as in [this comment](https://github.com/neomutt/neomutt/issues/1636#issuecomment-480235751). Only instead of limiting the messages you would do tagging.

I just tested this and it works:
```
macro index,pager <f3> \
"<enter-command>set my_auto_tag=$auto_tag<enter>\
<enter-command>set auto_tag=no<enter>\
<pipe-message>formail -X from:|awk -F'[<>]' '{print $2}'>/tmp/sender<enter>\
<enter-command>source ~/.neomuttrc.tmp2<enter>\
<enter-command>set auto_tag=$my_auto_tag<enter>"
```
separate config file:
```
set my_sender=`cat /tmp/sender`
push "T~f \"$my_sender\"\n"
unset my_sender
```
what's happening step by step:

- It doesn't play nice with auto_tag - so in the beginning current auto_tag settings is saved to my_auto_tag
- auto_tag is turned off
- message piped to formail for from header extraction and saved to file /tmp/sender
- source separate config file (this is crucial!) - you need to do it in a config and not in the same macro. 
  - set variable my_sender
  - tag messages matching the sender
  - unset varialbe my_sender
- auto_tag is reverted back to it's original value

**Comment by Sweenu** [comment]
Thank you! Wouldn't have thought of doing something like that.

It'd be practical to have functions to get information about the current mail and store them in a variable. But at least this works, thanks :)
