### ISSUE TITLE
index menu resorts headers unnecessarily

### ISSUE THREAD

**Issue by sassmann** [neomutt/neomutt#2092]
On OP_DISPLAY_MESSAGE and OP_DISPLAY_HEADERS update_index() is called with flag  MUTT_NEW_MAIL.
https://github.com/neomutt/neomutt/blob/3406e2d77ce6bc8cb8671dd208718199784198f0/index.c#L2502-L2504
https://github.com/neomutt/neomutt/blob/3406e2d77ce6bc8cb8671dd208718199784198f0/index.c#L2550-L2551
In the threaded mail case this calls update_index_threaded()
https://github.com/neomutt/neomutt/blob/3406e2d77ce6bc8cb8671dd208718199784198f0/index.c#L626-L627
which unconditionally resorts headers.
https://github.com/neomutt/neomutt/blob/3406e2d77ce6bc8cb8671dd208718199784198f0/index.c#L499-L503
If the mailbox is unchanged and mails are just being navigated resorting should not be necessary. There seems to be no adequate MxCheckReturns flag for this case. I wonder, should we introduce a new flag here or just skip resorting in the MUTT_NEW_MAIL case?

**Comment by flatcap** [comment]
Yes, I agree, but I'm reluctant to make any changes.
There are a lot of interdependencies here and I'm not sure I understand them all.

The unnecessary sorting is a symptom of Mutt's bad design.
I'm working towards fix, slowly, and from a different angle.

Currently there's a struggle between the backend and the GUI.
The backend code often needs to sort the emails to sync with filesystem/server, then the GUI needs to sort them back before the user notices.
Also the GUI tries to keep track of which email is 'current' (see the `index_hint` parameters all over the place).
This repeated sorting has led to lots of issues where the cursor moves unexpected after new mail arrives.

My solution is to keep two arrays of pointers and use notifications to update them (there's still only one array of actual email objects).
The backend keeps an array in the order that's most appropriate for it.
The GUI keeps an array in the user's sort order.

When new mail arrives, the backend knows which emails are new.
It adds them to its array, then sends out a notification containing the list of new emails.

The GUI can now decide how to act.
It doesn't necessarily have to re-sort its array, it might be able to just insert the new emails in the right places.
Importantly, the GUI won't get confused about the 'current' email, because only **it** is making changes to the array.

It's going to take me some time to get there, though.

**Comment by sassmann** [comment]
Understood, I've had good results with https://github.com/sassmann/neomutt/commit/54dfc532fb52089e0fba5c96a4f7f6ebbd88b5af. Just mentioning that as a reference.

**Comment by roccoblues** [comment]
Hi, I'm currently cleaning up some older issues here. Is this still relevant? Thanks!
