### ISSUE TITLE
How to set trash directory of a virtual mailbox?

### ISSUE THREAD

**Issue by therealmaxmoon** [neomutt/neomutt#2127]
I have a virtual mailbox, which shows me all unread messages of several mailboxes: 
`virtual-mailboxes "Unread" "notmuch://?query=tag:unread"`
If I delete a message from the virtual mailbox Unread, it will purged forever and not been moved to the Trash directory of the mailbox itself. Is it deleted forever or is it just somewhere hidden?

How can I set the right Trash directory (or even Archive,  Junk, etc.) of the right mailbox in virtual-mailboxes?

**Comment by jindraj** [comment]
It's better to use a different approach of trash with notmuch.

tag messages with `trash` or some other tag. Define a macro for deletion e.g.:
```
macro index,pager ,d      "<modify-tags-then-hide>-unread -inbox +trash\n<sync-mailbox><check-stats>" "Delete message"
```

```
virtual-mailboxes "Unread" "notmuch://?query=tag:unread AND NOT tag:trash"
virtual-mailboxes "Trash" "notmuch://?query=tag:trash"
```

And either delete messages within neomutt trash mailbox later. Or create cron:
`notmuch search --format=text0  --output=files tag:trash and not date:2weeks.. | xargs -0 --no-run-if-empty rm`
This will delete all messages tagged trash and older than 2 weeks. Beware that if you tag a message older than 2 weeks that it will be deleted by cron on it's first upcoming run. It's message date, not since it was tagged. Better test it before.

**Comment by therealmaxmoon** [comment]
I've followed the advice and switched completely to virtual mailboxes, because mixed mailboxes caused a lot of issues (like #2123)

If someone needs it: Here is how to mark a message for deletion or undelete it, including a refresh of the index and the navigation (counted messages):
```
bind index,pager d noop
bind index,pager u noop
macro index,pager d "<modify-tags-then-hide>+deleted -inbox -unread<return><sync-mailbox><check-stats>" "Delete message"
macro index,pager u "<modify-tags-then-hide>-deleted +inbox +unread<return><sync-mailbox><check-stats>" "Undelete message"
```

But what I still don't understand is the date command for notmuch. Because `not date:2weeks..` reads like "get messages which are NOT older than 2 weeks (and older)".

So I tried to count messages with and without **not** or **..**
```
$ notmuch count date:2weeks  
24
$ notmuch count date:2weeks..
54
$ notmuch count not date:2weeks   
1170
$ notmuch count not date:2weeks..
1140
```
Can someone explain it to me, please, because I'm just confused about the output.

**EDIT:** Ok, I think I got it.

- The first one counts messages which are exactly 2 weeks old.
- The second one counts the messages which are 2 weeks old and younger.
- The third one excludes all messages, which are not exactly 2 weeks old. So those can be older or younger than 2 weeks.
- The forth one counts all messages, which are older than 2 weeks (excluding messages which are exactly 2 weeks old or younger)

Thanks a lot

**Comment by jindraj** [comment]
This is more notmuch query: see https://notmuchmail.org/manpages/notmuch-search-terms-7/
`date:2weeks` will match messages from (i mean old) two weeks ago. Like `date:today` or `date:yesterday` will give you messages from today and the other from yesterday.
`date:2weeks..` is range query - since 2weeks until now. When you omit one of the boundary it means since ever or until now
