### ISSUE TITLE
configurable screen clearing on exit

### ISSUE THREAD

**Issue by archenemies** [neomutt/neomutt#2146]
## What would you like to be able to do?

On my Arch system, Neomutt clears the screen on exit, while Mutt does not.

Apparently I am not the only one who finds it annoying to have the screen cleared, see <https://mutt-users.mutt.narkive.com/ugfB4p7e/exit-mutt-with-clear-screen>.

Less has a way to configure this, with the `-X` option.

Alternatively, for example I have compiled rxvt-unicode with `--disable-swapscreen`, perhaps this should be sufficient, if Neomutt sends the proper escapes, to prevent clearing.

## What needs to change in NeoMutt?

Probably just go back to the old Mutt way of doing it, would be the easiest solution. As mentioned in the above thread, users who want to clear the screen can make a shell alias, or use Ctrl-L after Q. That's only one additional keystroke.

## Have you tried any alternative methods?

No.

## Additional Info

Thank you

**Comment by flatcap** [comment]
> On my Arch system, Neomutt clears the screen on exit, while Mutt does not.

Really?  That's surprising.  They work the same for me.

Both NeoMutt and Mutt use ncurses (or slang which works the same).
Curses does all the drawing for us and curses does the swap-to-alternate-screen too.

A typical scene would be:
```c
attrset(colour);
mvaddstr(y, x, string);
attrset(another_colour);
mvaddstr(y+1, x, string);
refresh();
```

Here, curses is handling the colour, cursor position and text that are being written to screen.
Nothing will appear on screen until the `refresh()` call -- this allows curses to optimise the drawing.

Once curses has been initialised, every call to `refresh()` will change to the alternate screen.

> Less has a way to configure this, with the `-X` option.

`less` doesn't use curses.  It handles the screen drawing itself.

> go back to the old Mutt way of doing it

NeoMutt hasn't change anything in this respect.

> As mentioned in the above thread

I don't know how mutt worked 15 years ago, with a 15-year-old version of ncurses,
but, I'm fairly confident that the _normal_ behaviour for such programs was to use the alternate screen.

**Comment by archenemies** [comment]
> Really? That's surprising. They work the same for me.

In that case I'm probably doing something wrong, but I don't know what it is.

I researched it a bit and narrowed down the cause.

In xterm, with standard terminfo, I only get differences in behavior when I configure

    XTerm*titeInhibit: true

in xrdb. This disables the alternate screen.

When I use `script` to capture the output, I get this:

    mutt:

    Quit Mutt? ([yes]/no): ^MyesESC[K^MESC[JESC[39;49mESC[KESC[32;1HESC[?1049lESC[23;0;0t^MESC[?1lESC>

    neomutt:

    Quit NeoMutt? ([yes]/no): ^MyesESC[K^MMailbox is unchangedESC[39;49mESC[37mESC[40mESC[HESC[2JESC[39;49mESC[32dESC[KESC[32;1HESC[?1049lESC[23;0;0t^MESC[?1lESC>

These are copied from less's output. You can see that NeoMutt has ESC[HESC[2J which is the sequence defined in my .terminfo for clear: "clear=\E[H\E[2J". Mutt does not send such a sequence.

I'm attaching the outputs of mutt -v and neomutt -v.

[mutt.txt](https://github.com/neomutt/neomutt/files/4219317/mutt.txt)
[neomutt.txt](https://github.com/neomutt/neomutt/files/4219318/neomutt.txt)

Also it may be relevant that in the Arch PKGBUILD, mutt has:

    ./configure \
             --prefix=/usr \
             --sysconfdir=/etc \
             --enable-debug \
             --enable-gpgme \
             --enable-pop \
             --enable-imap \
             --enable-smtp \
             --enable-hcache \
             --enable-sidebar \
             --enable-autocrypt \
             --with-curses=/usr \
             --with-gss=/usr \
             --with-ssl=/usr \
             --with-sqlite3 \
             --with-sasl \
             --with-idn2 \

while neomutt has:

    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --libexecdir=/usr/lib \
        --gpgme \
        --sqlite \
        --autocrypt \
        --lua \
        --notmuch \
        --gss \
        --gnutls \
        --sasl \
        --with-ui=ncurses \
        --with-idn2=/usr \
        --disable-idn \
        --idn2 \
        --lmdb \
        --kyotocabinet \
        --gdbm

These look slightly different but I can see that the same curses library is being linked:

    $ /lib/ld-2.30.so --list /usr/bin/mutt | grep curs
            libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fdc0aea7000)
    $ /lib/ld-2.30.so --list /usr/bin/neomutt | grep curs
            libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fc4181a0000)

Thank you for your attention to this oddity.

**Comment by flatcap** [comment]
> `XTerm*titeInhibit: true`

Ah, I see.  That disables the `ti` and `te` sequences that switch to/from the alternate screen.

> When I use `script` to capture the output, I get this:

Nice.
I've tracked down a commit bccbef607c90eb3c3fb24ce7ed9e10d393099fc2 that I made a year ago.
That's what's causing the difference.  I wanted to make certain that the alternate screen was cleared before exit.
Leaving visible (findable) info could be a security problem.

Try reverting that: `git revert bccbef607c90eb3c3fb24ce7ed9e10d393099fc2`


> Thank you for your attention to this oddity.

No problem.

**Comment by archenemies** [comment]
It think there is little doubt that this commit is causing the behavior I objected to.

However, I don't think it's worthwhile to me to compile a separate version of Neomutt.

Are you interested in reverting the commit? It seems over-cautious to me, and I'm having a hard time imagining a situation where it would really improve security.

Thanks for tracking it down.

**Comment by flatcap** [comment]
> Are you interested in reverting the commit?

Maybe, I just need to think it over a little more.

> It seems over-cautious to me

yeah, probably :-)

> where it would really improve security

I'd consider leaving personal info on screen bad behaviour.

**Comment by archenemies** [comment]
> I'd consider leaving personal info on screen bad behaviour.

Well, any program, even `cat` can result in personal information being left on the terminal. That's why we have Ctrl-L, or better yet close the terminal, use a screen locker, and so on. As for clearing the alternate screen, it seems the issue was not that the info is being left visible on the terminal, but that it is still accessible to a user who has access to the terminal, like the scrollback buffer. But it is hard to imagine a case where I would give someone I don't trust access to my terminal. And I think someone malicious would simply use the shell history to find my mail program and run it again.

**Comment by mschilli87** [comment]
Sounds like two valid opinions to me. Usually in cases like this a config option turns out to be a good compromise. Looks like it would be as simple as adding an `if` around the code introduced in https://github.com/neomutt/neomutt/commit/bccbef607c90eb3c3fb24ce7ed9e10d393099fc2.
If that's the case, naming, documenting (incl. the security concerns) and CI testing would be the 'hard' part.
So maybe @archenemies could provide a PR adding this option (keeping the default as-is now, *i.e.* 'more cautious', 'less convenient'), which @flatcap could agree to merge (and practically take over the maintainence burden, but gaining a potentially recurring contributor)? :wink:

**Comment by archenemies** [comment]
@mschilli87 thank you for inviting me to join the Neomutt family, but I'd rather not be the one to add this extra complexity to Neomutt. In my view, people who want the screen cleared can `alias neomutt="neomutt; clear"` as suggested by the Mutt list 15 years ago.

**Comment by gahr** [comment]
Hi @archenemies, in the thread you mentioned I see nobody complaining about mutt clearing the screen, rather the OP is asking for this feature. Apart from the different behaviour between mutt and neomutt, what problem exactly is the term clearing causing to you / what does it prevent you from doing?

**Comment by navarum** [comment]
@gahr:

Conrad Lloyd-Knight

> The less program does the same thing (annoyingly... I turned it off when I compiled less, in fact)

Matthew D. Fuller

> More specifically, there's a pair of termcap/terminfo properties that I can't recall offhand that control whether this happens or not.
> Personally, I can't stand it :)

The reason to want to not have information disappear from the terminal is the same reason to want it to be there in the first place, presumably it had some value to the user. If the user could remember it all, then making it go away would be no loss. Can you remember a whole screen full of data?

What is the problem you're trying to solve with automatic clearing? User remembers to quit Neomutt but forgets to close the terminal or press Ctrl-L? User runs another curses program which rewrites half the secondary screen before segfaulting, leaving message subjects on the terminal, which user then leaves open for his roommate to find because he got suddenly distracted by something else?

Maybe Neomutt should quit after a set period of time, just so people don't leave it open by accident, and then when it quits it should locate the terminal PID and kill it, then erase itself from the shell history in case of malicious adversary getting shell access...

**Comment by gahr** [comment]
Me, I just thing that interactive apps should be responsible for drawing whatever they need and cleaning up after they're done. I oppose this pure text-only apps that are supposed to be arranged in pipelines, which of course need not cook/uncook the screen. That's why I think it's a good idea that `cat` doesn't clean up and `less` does.
Nowadays, I think there are better solutions (tmux comes to mind) for "remembering" what was displayed by NeoMutt than leaving the screen cluttered on exit.

Having said that, I don't particularly care one way or the other, as I rarely quit NeoMutt, if not for starting it again after a rebuild. I was just curious about the use case.

**Comment by navarum** [comment]
I also rarely quit neomutt, and I run it inside of screen. So this is mostly just a matter of principle, true. I think the proper way for users to configure screen clearing after a curses app is via their terminal options, e.g. `XTerm*titeInhibit`. I don't like to see applications breaking that.

**Comment by flatcap** [comment]
@archenemies 
Did you try [reverting the commit](https://github.com/neomutt/neomutt/issues/2146#issuecomment-587482957)?
Does it do what you want?

**Comment by archenemies** [comment]
@flatcap Yes, I have just checked that with the commit reverted, it does not clear the screen on exit. Apologies for my delay.

**Comment by archenemies** [comment]
Thank you indeed @flatcap
