### ISSUE TITLE
Automatically purge messages

### ISSUE THREAD

**Issue by daniel-sousa-me** [neomutt/neomutt#217]
Currently when we delete a message or save it to another folder, the message stays there until we sync or change the current folder.

Would it be possible to add a feature to automatically purge the messages after these actions?

**Comment by guyzmo** [comment]
I'm not sure this is a good idea… Because to remove a message, then mutt would have to reindex every message of the mailbox (at least starting from the removed message), acting the same as a macro doing a sync just after a delete.

Another reason is that when you delete a message, the delete is definitive, so it's always good to make it happen in at least two steps, having the message marked for deletion with the `D` marker.

I guess, there might be a way to "hide" a message from sight when you delete it, doing nothing on the real data up until you sync, but at least making it disappear from your sight. But you can already do that if you setup a filter (the `l` key) to `!~D` which will hide all mark for deleted messages from your sight.

**Comment by daniel-sousa-me** [comment]
In my case these actions only move the mail to a different folder, so I don't really want that extra step.

Is there any way to automatically apply that filter when I enter in a folder?

**Comment by guyzmo** [comment]
I guess you could use `folder-hook`s.

**Comment by gahr** [comment]
My solution to this is
`
set trash= /path/to/my/trash/folder
macro index d '<delete-message><sync-mailbox>y'
`
