### ISSUE TITLE
[Question / Feature Request] collapse/expand folders in sidebar

### ISSUE THREAD

**Issue by ngortheone** [neomutt/neomutt#2221]
This thread describes the desired feature:

https://www.mail-archive.com/mutt-users@mutt.org/msg50921.html

Is this possible with neomutt? If not then please consider this a feature request.

Thanks

**Comment by jindraj** [comment]
It's possible using specific configuration.

## folder-hooks approach
See my answer to a stackexchange quiestion: [mutt sidebar: expand/collapse folders
](https://unix.stackexchange.com/a/566611/85046)

- ✅ easier to setup, no need to do any sourcing file magic
- ❌ You need to enter the main account mailbox to collapse others and expand underlaying mailboxes

## macros approach
I think You can do similar thing with macros for switching accounts. Please note I didn't tested it. But I believe it should work.

- ✅no need to open the main account mailbox to expand underlaying mailboxes and collapse others
- ❌fragmented configuration over more files

*exmaple **config***
- just defines macros for switching between accounts
```
macro index,pager <F1> '<enter-command>source configfiles/account1<enter>'
macro index,pager <F2> '<enter-command>source configfiles/account2<enter>'
…
macro index,pager <FN> '<enter-command>source configfiles/accountN<enter>'
```

*example **configfiles/accountN***
- sources shared pre account config - see **configfiles/account_shared** below for more details
- sets mailboxes for current account
- sets all other settings You need for this account, changing $from etc.

```
source configfiles/account_shared
mailboxes accountN/INBOX accountN/sent accountN/drafts
… Your other account settings like
```

*example **configfiles/account_shared***
- clean all mailboxes
- add main accounts mailboxes
```
unmailboxes *
mailboxes account1 account2 … accountN
```

## notes
Both examples above counts with maildirs. If You want to do that with i.e. multiple IMAP accounts, You need to fake other's accounts existence in **account_shared** config because You can have only one $folder. 
```
named-mailboxes "account1" "/dev/null"
…
named-mailboxes "accountN" "/dev/null"
```
