### ISSUE TITLE
Can't login gmail

### ISSUE THREAD

**Issue by GasparVardanyan** [neomutt/neomutt#2256]
After trying to log in gmail accaunt I got this message:
No authenticators available or wrong credentials

In ~/.config/mutt/muttrc I have:
set folder = "imaps://gaspar.vardanyan.mailbox@gmail.com@imap.gmail.com:993"
set spoolfile = "+INBOX"

What is the problem?

P.S. I've enabled IMAP access in gmail settings.

**Comment by jindraj** [comment]
Are you using password `imap_pass` or oauth `imap_oauth_refresh_command`?
What is your imap_authenticators settings if any?

**Comment by GasparVardanyan** [comment]
I just have this config:
[gaspar ~]$ cat .config/mutt/muttrc
set folder = "imaps://gaspar.vardanyan.mailbox@gmail.com@imap.gmail.com:993"
set spoolfile = "+INBOX"
[gaspar ~]$

I type my password in neomutt's prompt

**Comment by jindraj** [comment]
Are you using application specific password with less secure apps enabled? https://support.google.com/accounts/answer/6010255?hl=en

Or are you just filling in your main Google password?

**Comment by GasparVardanyan** [comment]
I use my main Google password.

**Comment by jindraj** [comment]
That seems to be not possible.

Either use [oauth2](https://neomutt.org/guide/optionalfeatures#6-%C2%A0oauthbearer-support) or enable less secure apps and create application specific password.

Please prefer the oauth2 because GMail is sunsetting less secure apps. And to make it work now with less secure apps will only make you move to oauth2 sooner or later. Choosing oauth2 now will save You time.

See [GSuit updates blog](https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html) and non-Gsuite accounts will be followed.

**Comment by GasparVardanyan** [comment]
Solved. Thank you.
