### ISSUE TITLE
Better support for <group-alternatives> after attaching other files

### ISSUE THREAD

**Issue by dcpurton** [neomutt/neomutt#2387]
I've been experimenting with `<group-alternatives>` to send multipart/alternative mail.

I'd like to be able to construct the email as I normally would and then create the multipart/alternative version and send it in one keystroke.

I can do this with a macro like this:

```
macro compose y "<first-entry><enter-command>set wait_key=no<enter>| msg2html.sh<enter><attach-file>/tmp/neomutt-alternative.html<enter><tag-entry><first-entry><tag-entry><group-alternatives><enter-command>set wait_key=yes<enter><send-message>" "Send multipart/alternative message"
```

(`msg2html.sh` is a script that calls `pandoc`).

This works well, except if I attach other files before running the macro above. In this case the multipart/alternative message ends up being the last part in the list of mime parts. It seems not possible to make it the first part again. Neomutt returns the error: 'The fundamental part can't be moved'. Other how-tos I've seen suggest creating the multipart/alternative email, then adding other attachments, then sending. But, it would be nice to be able to do things in a more streamlined way.

The email still seems readable by the clients I tested, but not having the actual message as the first part seems untidy. (Neo)Mutt, of course, then places the attached files at the top, rather than the bottom of the email when reading it.

I don't know the technical reasons why 'The fundamental part can't be moved', but perhaps a command like `<make-fundamental>` could be added. Then this could be added to my macro just after `<group-alternatives>` to make the multipart/alternative mime part the first mime part in the email.

**Comment by dcpurton** [comment]
I had a go at a preliminary implementation of a `<make-fundamental>` feature. See https://github.com/dcpurton/neomutt/tree/make-fundamental.

It seems to work OK for me in my tests for what I want.

My macro to send a `multipart/alternative` email is now:

```
macro compose y "<first-entry><enter-command>set wait_key=no<enter>| msg2html.sh<enter><attach-file>/tmp/neomutt-alternative.html<enter><toggle-unlink><tag-entry><first-entry><tag-entry><group-alternatives><toggle-unlink><edit-description>\Ca\Ck<enter><make-fundamental><enter-command>set wait_key=yes<enter><send-message>" "Send multipart/alternative message"
```

Most changes are in `compose.c`. However, I'm not very familiar with the `mutt` code (and only have basic C skills). In particular I was uncertain about the relationship between attachments pointed to by `e->content` and the the `actx->idx` array. These two lists seem to normally be the same, but after grouping attachments (either alternatives or multilingual) they are out of sync. I added code to `<group-alternatives>` and `<group-multilingual>` (since it was analogous) to reconcile the two attachment lists. With this done I was able to make an attachment the fundamental part of the email.

I'm also not very familiar with how localisation works. There's a removed string and an added string, but I'd need some pointers to know what needs to be set up for translations.

If there's interest in having this feature merged upstream, I'd be happy to make any necessary alterations and additions to my code and open a pull request.

(There's still problems with the `<group-alternatives>` code though. Apart from issue https://github.com/neomutt/neomutt/issues/2364, stray empty files are left lying around in `/tmp/`. I think I've introduced the latter, but I'm still hunting for why it happens.)

**Comment by flatcap** [comment]
Hi @dcpurton 
Sorry it's taken a while to get back to you.

A long time ago, a few developers got excited about manipulating the attachments.
They created the grouping / multilingual code.  Since then, it's not been touched.  Or understood.

When #2364 was raised, I did a bit of investigation, but that was all I had time for.

We're not missing much, from having a really useful setup.
Almost all the code's already there.

Given a list of attachments, we want to be able to:
- Move up/down list
- Group/ungroup
- Promote/demote (to/from) an existing group

One important thing that's missing is the tree-drawing.
(it's there and working when we receive an email)
Without that feedback, it's hard to see what you're doing.

> I had a go at a preliminary implementation of a `<make-fundamental>` feature.

It works as expected.
Does it do anything special, that `<move-up>` doesn't?

>  only have basic C skills

The code looks fine (and follows the style of the other code :-)

> I was uncertain about the relationship between attachments pointed to by `e->content` and the the `actx->idx` array.
> These two lists seem to normally be the same,
> but after grouping attachments (either alternatives or multilingual) they are out of sync.

- `e->content` is a tree of `struct Body`
- `actx->idx` is a flat list of all those body parts
- `actx->v2r` (virtual to real) is a lookup table
  It lists the attachments in the order they are on screen

Here are some diagrams: [email](https://flatcap.org/mutt/group/compose-email.svg), [actx](https://flatcap.org/mutt/group/compose-actx.svg)

If you have graphviz installed, you can generate these diagrams from the code:
- `./configure --debug-graphviz`
- `dump_graphviz_email(e);`
- `dump_graphviz_attach_ctx(actx);`

> I added code to `<group-alternatives>` and `<group-multilingual>` to reconcile the two attachment lists.

I think that's right

> With this done I was able to make an attachment the fundamental part of the email.

Well done :-)

> I'm also not very familiar with how localisation works.

The translations are handled by `gettext()`, which has two handy macros:
- `_()` for normal runtime strings
- `N_()` for static strings

To update the translations files (`po/*.po`), run `make update-po`
But, that's something I do only periodically, because it creates a lot of noise in the diffs.

> If there's interest ... open a pull request

Yes, please!

**Comment by dcpurton** [comment]
Thanks, I'll have a look at using graphviz.

The current `<move-up>` command doesn't let you move an attachment from the second position into the first position at all (although that could be fixed of course).

For my use case, the main advantage of `<make-fundamental>` is that since the grouped attachment gets added to the end of the list of attachments, I can move it to the top in one command in a macro, rather than an unknown number of `<move-up>` commands. It may be that `<make-fundamental>` isn't really a good name. Using `<move-first>` might be better. I only used `<make-fundamental>` because that was the error returned by `<move-up>` when I tried to move an attachment from position two to position one in the list of attachments.

From your comments, I take it that I needn't worry about translations at the moment?

Also, what needs to be done as far as documentation goes?

And as an aside, I can confirm that your recent commit does fix the problem of empty temporary files being left around.

**Comment by Hugo-Heagren** [comment]
@dcpurton I'm not sure of your exact use case, but I've been developing a programme for this sort of thing recently (and could do with some motivated support and some test-users!). [multi-mark-maker](https://github.com/Hugo-Heagren/multi-mark-maker).

There's no documenatation at the moment, but I'll put up a basic usage guide in the README today for people who might want to have a go. I use the current version everyday at the moment to send multipart emails written in asciidoc, often with numerous attachments, and it works pretty well.

**Comment by dcpurton** [comment]
@Hugo-Heagren, I'm pretty happy with my setup at the moment.

I'm still using my fork of neomutt as haven't had a chance to get it in to a state that I can contribute back what I'm doinging.

The conversion from Markdown to html is achieved using a simple script with a bit of `sed`, `pandoc`, and `premailer` to put all the CSS inline.

Your project looks interesting, but unless I'm mistaken your code will not work with PGP signed and/or encrypted emails as it operates on the final fully formed email. The advantage of creating the HTML part in neomutt and making the multipart email there is then the whole email can still be signed/encrypted.
