### ISSUE TITLE
Doesn't compile with gpgme enabled

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#257]
../../crypt-gpgme.c:4962:6: error: conflicting types for 'gpgme_set_sender'
 void gpgme_set_sender (const char *sender)
      ^~~~~~~~~~~~~~~~
In file included from ../../crypt-gpgme.c:47:0:
/usr/include/gpgme.h:1171:15: note: previous declaration of 'gpgme_set_sender' was here
 gpgme_error_t gpgme_set_sender (gpgme_ctx_t ctx, const char *address);

This is with libpgme11 1.8.0-2

**Comment by riesebie** [comment]
Works now. Thanks ;-)

**Comment by larsks** [comment]
Hey @flatcap, any idea what happened to this commit?  `crypt-gpgme.c` in `master` still has `gpgme_set_sender` instead of `mutt_gpgme_set_sender`, and it doesn't look like any branches contain this commit.

**Comment by larsks** [comment]
With `gpgme` 1.8.0, `neomutt` compiles successfully if I cherry-pick this commit.

**Comment by flatcap** [comment]
Hi @larsks, I'm confused...

The commit I mention: 7d69f2a renamed a function in three places:
- `crypt-gpgme.c`
- `crypt-gpgme.h`
- `crypt-mod-pgp-gpgme.c`

Those files have been moved in neomutt, to
https://github.com/neomutt/neomutt/blob/1e5ff6580a4acb09889b4dcbba1223da40aee7b6/ncrypt/crypt_gpgme.c#L5139
https://github.com/neomutt/neomutt/blob/1e5ff6580a4acb09889b4dcbba1223da40aee7b6/ncrypt/crypt_gpgme.h#L65
https://github.com/neomutt/neomutt/blob/1e5ff6580a4acb09889b4dcbba1223da40aee7b6/ncrypt/crypt_mod_pgp_gpgme.c#L113

The changes are definitely there every release since neomutt-20170526.

**Comment by larsks** [comment]
Oh, you know what, my local repository apparently has a bad tracking branch and didn't actually update when I ran a `git update`. Neeeeeeeever mind.
