### ISSUE TITLE
sidebar breaks reflow_text

### ISSUE THREAD

**Issue by tsuflux** [neomutt/neomutt#26]
With the sidebar open, `reflow_text` set and the pager's current width less than `reflow_wrap`, mutt will not correctly wrap format=flowed text. The calculations simply ignore the width of the sidebar and instead use the total width of the terminal while the pager's actual width should be used.

**Comment by flatcap** [comment]
Hi @tsuflux 
The way windows are drawn in Mutt, has just been rewritten.
Unfortunately that code isn't stable and isn't in NeoMutt, yet :-(

I'll see if I can fix the problem.

If you have the time, could you check if the [devel/win-sidebar] branch of NeoMutt solves your problem:
```
git clone -b devel/win-sidebar https://github.com/neomutt/neomutt.git
cd neomutt
./prepare --enable-sidebar
make
./mutt
```

**Comment by tsuflux** [comment]
I've just tried out the [devel/win-sidebar] branch and it fixes my problem. :smiley:

I am looking forward to seeing these changes in the main branch.  Thank you.

**Comment by tsuflux** [comment]
The fix introduced a new problem found by @tzok. 

Because the pager now substracts `sidebar_width` from `reflow_wrap` when calculating the width of the displayed text, `reflow_wrap` is not correctly honored anymore. This will result in very few characters per line to be displayed if `sidebar_width` is large. I have not noticed this before due to the very thin sidebar I am using.

See also the comment section of the AUR package [mutt-sidebar](https://aur.archlinux.org/packages/mutt-sidebar/#news) for some examples.

**Comment by flatcap** [comment]
Thanks for the report @tsuflux I shall investigate.
I'll be glad when I can introduce the new windows code -- it'll fix things properly.

**Comment by flatcap** [comment]
@tzok, @tsuflux
I think I've found your problem.  I think you need to set $reflow_wrap.
By default, `set reflow_wrap=78`, which means the text is wrapped, even if reflowed.
Setting `set reflow_wrap=0` will wrap at the screen's edge, which is what you want.

**Comment by tsuflux** [comment]
But what if we don't want to wrap at the screen edge if the pager's width is larger than 78? I prefer having breaks at around this value, as very long lines a hard to read.

**Comment by flatcap** [comment]
Ah, sorry, I understand now.
Let me go off and experiment...

**Comment by tzok** [comment]
@tsuflux, I do not fully get the original bug report. In my case (without your fix introduced in 94b107d) I have sidebar_width = 48 and reflow_wrap = 78. When I change size of my virtual terminal to width between 48 and 78, the text is wrapped as I expect it to be wrapped - at the edge of terminal. Why is that bad?

Here you can see my terminal with mutt having width 78, 68 or 58. It is becoming less and less readable due to my relatively big sidebar_width, but for me the wrapping works as expected: [http://imgur.com/a/HAnYa](url)

**Comment by flatcap** [comment]
@tzok, If you have `reflow_wrap = 0` then everything looks fine (but it's slightly wrong).
What @tsuflux spotted is that I subtract SidebarWidth after the wrap width is calculated.
`sidebar_width = 20` and `reflow_wrap = 40` would lead to only 20 columns of text.

**Comment by tzok** [comment]
@flatcap, I meant that **before** changes introduced 94b107d everything was already fine IMHO. That's why I mentioned @tsuflux, because he opened this bugreport. When I tried to reproduce the issue as described in the first comment (see gallery in imgur in my previous comment) I think mutt worked as expected. Without subtracting SidebarWidth from width.

**Comment by flatcap** [comment]
Before the change, the text **was** still wrapped, but not correctly. If you had quoted text, then every wrapped line should have "> " at the beginning.  That's where the mistake shows.

**Comment by flatcap** [comment]
OK, I think I've got it now.
I've tested all combinations of:
- Sidebar off, narrow, medium, super wide
- reflow_wrap = 20, 60, 200, -20, -40, 0

Please can you test [issue/26](https://github.com/neomutt/neomutt/tree/issue/26) and check that you're happy with the result.
```
git clone -b issue/26 https://github.com/neomutt/neomutt.git
cd neomutt
./prepare --enable-sidebar
make
```

**Comment by tsuflux** [comment]
@flatcap, I did some tests as well and I believe that everything now works as expected. :+1:

**Comment by flatcap** [comment]
Excellent.  Thanks for testing it.
