### ISSUE TITLE
"Create is only supported for IMAP mailboxes"

### ISSUE THREAD

**Issue by asakura42** [neomutt/neomutt#2777]
I use Luke Smith's build of Neomutt (https://github.com/LukeSmithxyz/mutt-wizard/) and it uses isync to download mail. And I like to create folders for every type of mail (hello OCD 😀). But when I try to create new folder inside NeoMutt (printing c?C for example) it fails and writes "Create is only supported for IMAP mailboxes". But this configuration didn't use POP3. I dunno what's wrong. So now I create new folder with `mkdir -p ~/.local/share/mail/mail@mail.mail/Folder/{cur,new,tmp}` and adding this folder to `.muttrc` file of my account which is BORING

How can I create folders inside NeoMutt?

**Comment by ngortheone** [comment]
Luke's setup uses local Maildir for neomutt, and a separate tool (`mbsync`) is used to download IMAP contents to your local disk.
Neomutt does not have direct connection to IMAP in this scenario.

I recommend doing 3 things.
1) A macro to auto-discover nested Maildirs in your mail directory. Something along the lines(:
```
mailboxes `for file in ~/.local/var/mail/main/*; do \
  box=$(basename "$file"); \
  if [ ! "$box" = '.' \
      -a ! "$box" = '..' \
      -a ! "$box" = ".notmuch" \
      -a ! "$box" = '.customflags' \
      -a ! "$box" = '.subscriptions' ]; then \
    echo -n "\"=$box\" "; \
  fi; \
done`
```
I use this snippet myself.

2) Have another macro to create local folders. Sorry, don't have one ready (share it if you end up writing it!)

3) make sure mbsync/isync is setup to support two-way sync, so that next time you sync mail your new folders are uploaded to IMAP server (you'd have to read mbsync manual in order to get the details straight)

**Comment by brunnre8** [comment]
that's https://github.com/neomutt/neomutt/issues/2701 and I should start moving my behind...

**Comment by asakura42** [comment]
> for file in ~/.local/var/mail/main/*; do \

You can do it easier:

`find ~/.local/share/mail/mail@mail.mail/* -maxdepth 0 -type d | sed 's!.*/!!;s/^/"=/;s/$/"/' | tr '\n' ' '`

**Comment by ngortheone** [comment]
@asakura42 yeah, I didn't spend much time thinking about that macro when I wrote it. It gets the job done for me. But thanks for improvement, I'll take it in.

**Comment by gahr** [comment]
I'll close this as the feature is being tracked in #2701 already. Thanks.
