### ISSUE TITLE
Mail spoofing question

### ISSUE THREAD

**Issue by asakura42** [neomutt/neomutt#2797]
I wrote new mail but accidentally pressed `<Esc>f` and changed my dick@shit.cringe to FBI@CIA.GOV. Giggling I pressed "Send" and mail was sent from this address! Looks like good joke from my side but can NeoMutt prevent receiving spoofed mail? I dunno maybe check headers or smth like this. When I realized that in 2021 this mail bug/feature still works I got a little scared.

**Comment by brunnre8** [comment]
that's a job for dmarc / spf and dkim and your spam filter (say spam assassin) on the server side.

There's a difference between the smtp envelop from and the rfc5322 from.

Email is like a letter... you write some address on the envelop and shove a letter into it.

You can write any name you wish in the salutation / greeting line of the letter, your postal office happily delivers it to the recipient written on the envelop even if that doesn't match with the greeting.

It's obvious on the receiving end, sadly none of the normal email clients show the missmatch.
Un neomutt you can show the return-path header in addition to the from and then you'll see the discrepancy.

**Comment by ngortheone** [comment]
Some SMTP servers can be configured to validate FROM to match the reverse DNS of the incoming connection. Spam filtering engines could also be configured to mark such incoming email as potential spam.

But @brunnre8 is right. Email was designed to be relay-able. You could send any email to any server and it would forward it accordingly. Needless to say that this feature was abused by spammers so open relay is a big no-no today. But receiving side can still decide to receive and email even if it was sent from a host that does not match the domain specified in FROM field.

Likewise nothing prevents you from sending an email with fake FROM field. It is by design. You just need to keep in mind that chances of delivering of such message are going down. It can go to SPAM or be rejected at all depending on the receiving side configuration.

**Comment by ngortheone** [comment]
Additionally 

> Looks like good joke from my side but can NeoMutt prevent receiving spoofed mail?

Neomutt is a MUA (Mail User Agent). It does not receive mail. Your SMTP server does. You absolutely can configure your SMTP server to reject such emails.

**Comment by asakura42** [comment]
@brunnre8 @ngortheone Oh I know that I can install some tools on server but I use public email server as majority of users. What can I do in my situation? Of course I can write to admin, but i think he won't response.

I'm closing issue because it's not the NeoMutt issue. But as I know, Neomutt is not just a mail reader, it's sort of system with bunch of addons. So maybe some of other applications can help?
