### ISSUE TITLE
neomuttrc.vim

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#280]
FMPOV it makes sense to merge all `doc/vimrc.*` to one` neomuttrc.vim`. This file can also be pull requested at [vim/vim](https://github.com/vim/vim) and or [neovim/neovim](https://github.com/neovim/neovim). What do you think?

**Comment by guyzmo** [comment]
that would really make sense once a new path (and eventually a new filename) has been decided for the `muttrc` in a new path. I guess that `~/.config/mutt/neomuttrc` as entry point would make sense, and thus we could have both `neomuttrc.vim` living along with original `muttrc.vim`.

Otherwise, it won't be possible to tell `muttrc` from `neomuttrc` and vim (or neovim) people won't merge something that will affect the upstream project syntax highlighting. And BTW, neovim people chose to do a separate configuration entry point from vim, it being `~/.config/vim/init.vim`.

So meanwhile, I'm suggesting to actually create a new project `neomutt/neomuttrc.vim` that will expose the merged files as a ftplugin that can be loaded as a Plug.

**Comment by flatcap** [comment]
Yes, combining them would be a lot tidier.  They were separate files since the days that all the features were separate patches.

The config file names are settled (hopefully).  NeoMutt searches, in various dirs, for:
1. neomuttrc-YYYYMMDD
2. neomuttrc
3. muttrc-1.7.2
4. muttrc

What should we offer to (neo)vim?
A `neomuttrc.vim` file with **just** our bits, that `source`s the `muttrc.vim`? 
Or, a standalone `neomuttrc.vim` that includes all of Mutt's config too?

> create a new project neomutt/neomuttrc.vim that will expose the merged files as a ftplugin that can be loaded as a Plug.

Sure, go for it.  You should be able to create a repo.

**Comment by guyzmo** [comment]
> What should we offer to (neo)vim?
> A neomuttrc.vim file with just our bits, that sources the muttrc.vim?
> Or, a standalone neomuttrc.vim that includes all of Mutt's config too?

Obviously, a `neomuttrc.vim` that sources and extends `muttrc.vim`. Except if at some point in the future we're planning on doing incompatible change.

**Comment by chrisbra** [comment]
if you plan to go this route, I suggest create a PR at the vim/vim repository and add a simple neomuttrc.vim syntax file there that sources muttrc.vim. Make sure to include your name, a license and possibly a repository where people can direct questions. Bram will then pick this up and merge it with the next runtime file update and neovim folks will later then merge runtime file changes.

**Comment by flatcap** [comment]
@chrisbra 
Thanks for the info.  That's exactly what we needed to know.

**Comment by toogley** [comment]
fixed by https://github.com/neomutt/neomutt/pull/497/commits/9501fe70d544772662a2ea331198a20266ae4c6e
