### ISSUE TITLE
neomutt-20170113 headercache slows down

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#297]
Compared to 20161123 reading the headercache takes more than five times. In my case it is LMDB. Deleting the database and create a new one doesn't help. Entering a mailbox it first scans (what?) and then it reads the headers. Scanning and reading takes both approximately the same time. All together 25 sec on a 70k mailbox. Before it was max. 4 sec. This is on a i386 P4. On a amd64 it is faster but not as fast as on 20161123. I am missing the fingersnip ;-)

**Comment by riesebie** [comment]
There is no difference running kyotocabinet. qdbm is a bit faster but doesn't rock :( I think it is worth to test the other d'bases. It seems not to be frontend specific.

**Comment by flatcap** [comment]
Argh!  I think I know where the problem is.
Please can you build/test version 9f5acdc (just before I tidied the main hcache function).

**Comment by riesebie** [comment]
running [9f5acde](https://github.com/neomutt/neomutt/commit/9f5acdc2a70b1a0a9b06fb3e8b82ae177a9eb3db) seems to be as slow as 2017013....

**Comment by flatcap** [comment]
I've just done some tests on a 100K-email mailbox, using 20161126 and 20170113, using LMDB and TokyoCabinet.  20 tests, the times are sorted (best to worst):

| L 1126 | L 0113 | T 1126 | T 0113 |
|--------|--------|--------|--------|
| 3.840  | 3.737  | 2.374  | 2.363  |
| 3.852  | 3.743  | 2.383  | 2.381  |
| 3.906  | 3.744  | 2.409  | 2.406  |
| 3.915  | 3.761  | 2.412  | 2.419  |
| 3.963  | 3.776  | 2.416  | 2.422  |
| 3.978  | 3.783  | 2.421  | 2.424  |
| 3.988  | 3.794  | 2.471  | 2.442  |
| 4.015  | 3.814  | 2.477  | 2.460  |
| 4.023  | 3.888  | 2.479  | 2.471  |
| 4.033  | 3.918  | 2.488  | 2.496  |
| 4.039  | 3.920  | 2.506  | 2.518  |
| 4.042  | 3.930  | 2.532  | 2.554  |
| 4.066  | 3.933  | 2.552  | 2.593  |
| 4.098  | 4.008  | 2.584  | 2.595  |
| 4.116  | 4.042  | 2.620  | 2.598  |
| 4.121  | 4.064  | 2.635  | 2.611  |
| 4.137  | 4.076  | 2.669  | 2.616  |
| 4.176  | 4.108  | 2.704  | 2.632  |
| 4.223  | 4.143  | 2.732  | 2.651  |
| 4.395  | 4.270  | 2.753  | 2.815  |

This informal test shows a slight improvement since the last release of NeoMutt.
(statistically not significant :-)

**Comment by riesebie** [comment]
* Richard Russon <notifications@github.com> [2017-01-14 05:54 -0800]:

> I've just done some tests on a 100K-email mailbox, using 20161126
> and 20170113, using LMDB and TokyoCabinet.  20 tests, the times
> are sorted (best to worst):
> 
> | L 1126 | L 0113 | T 1126 | T 0113 |
> |--------|--------|--------|--------|
> | 3.840  | 3.737  | 2.374  | 2.363  |
> | 3.852  | 3.743  | 2.383  | 2.381  |
> | 3.906  | 3.744  | 2.409  | 2.406  |
> | 3.915  | 3.761  | 2.412  | 2.419  |
> | 3.963  | 3.776  | 2.416  | 2.422  |
> | 3.978  | 3.783  | 2.421  | 2.424  |
> | 3.988  | 3.794  | 2.471  | 2.442  |
> | 4.015  | 3.814  | 2.477  | 2.460  |
> | 4.023  | 3.888  | 2.479  | 2.471  |
> | 4.033  | 3.918  | 2.488  | 2.496  |
> | 4.039  | 3.920  | 2.506  | 2.518  |
> | 4.042  | 3.930  | 2.532  | 2.554  |
> | 4.066  | 3.933  | 2.552  | 2.593  |
> | 4.098  | 4.008  | 2.584  | 2.595  |
> | 4.116  | 4.042  | 2.620  | 2.598  |
> | 4.121  | 4.064  | 2.635  | 2.611  |
> | 4.137  | 4.076  | 2.669  | 2.616  |
> | 4.176  | 4.108  | 2.704  | 2.632  |
> | 4.223  | 4.143  | 2.732  | 2.651  |

How did you took the time?

-- 
  On the keyboard of life you have always
  to keep a finger at the escape key;-)

**Comment by flatcap** [comment]
```
for i in {1..20}; do rm -fr ~/.cache/mutt; time ./mutt -e 'exec exit'; done
```

**Comment by riesebie** [comment]
My build options: 

[build.txt](https://github.com/neomutt/neomutt/files/706037/build.txt)
