### ISSUE TITLE
wrong documentation of notmuch variable nm_default_uri

### ISSUE THREAD

**Issue by karlsebal** [neomutt/neomutt#3025]
In the [docs](https://neomutt.org/feature/notmuch#4-%C2%A0variables) the variable for notmuch default url is given as `nm_default_url` which leads to `ERR01 unknown variable: nm_default_url` in NeoMutt 20191207.

It must be `nm_default_uri` to work.

**Comment by flatcap** [comment]
Ah.  Sorry about that.

If you have a look at the docs installed with NeoMutt, you'll see that they say `nm_default_uri`.
e.g. `/usr/share/doc/neomutt/manual.html#notmuch`

The online docs are correct for the latest version of NeoMutt, but we've renamed a few config variables, since 2019, for consistency.  The new versions of NeoMutt accept both `_url` and `_uri`, but will eventually deprecate `_uri`.

**Comment by karlsebal** [comment]
Oh thank you for the prompt answer! I am on an LTS version here with a way too old version of NeoMutt so… Never mind, close the report and I will consult the man page in future rather than the online docs.

Thanks for your effort!

Am 21. August 2021 19:24:11 MESZ schrieb Richard Russon ***@***.***>:
