### ISSUE TITLE
next-unread-mailbox only works every mail_check_stats_interval seconds

### ISSUE THREAD

**Issue by vuori** [neomutt/neomutt#3053]
## Expected Behaviour

`next-unread-mailbox` should go to next unread mailbox.

## Actual Behaviour

If called more often than `mail_check_stats_interval` seconds, function says that there are no unread mailboxes.

## Steps to Reproduce

1. Wait for mail to arrive in a mailbox which is not the current one.
2. Press key bount to `next-unread-mailbox`, note that it will usually work once.
3. Move to another mailbox (without reading the new mail), try it again.
4. "No new messages" will be printed.

## How often does this happen?

- Always

## When did it start to happen?

Switched to master from Ubuntu package (20191207+dfsg.1-1.1) (maybe, I'm not sure if I tried to use the function when using the packaged release).

## NeoMutt Version

```
NeoMutt 20210205-804-7958fd-dirty
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.10.60+ (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2.20200212)
libidn: 1.33 (compiled with 1.33)
GPGME: 1.13.1-unknown
OpenSSL: OpenSSL 1.1.1f  31 Mar 2020
libnotmuch: 5.4.0
PCRE2: 10.34 2019-11-21
storage: kyotocabinet
compression: lz4, zlib
```

Mail check settings:
```
set mail_check = 5
set mail_check_recent = yes
set mail_check_stats = yes
set mail_check_stats_interval = 60
```

## Extra Info

Using an all-Maildir configuration.

The problem is that `mutt_mailbox_check()` sets `MailboxCount` to 0 even in cases when it's not going to actually check stats on mailboxes due to `mail_check_stats_interval` not having expired, except on the first time it sees a given mailbox.

Diff below fixes the immediate problem, though it may lead to `MailboxCount` being wonky after a new mailbox is added. In practice `first_check_stats_done` being false after the first call to the function sounds rare, but I think a canonical fix would require always either checking stats on all mailboxes or checking none of them. Basically `first_check_stats_done` would need to be checked in a separate pass and `check_stats` set to `true` if at least one mailbox needed a check I guess.

```diff
diff --git a/mutt_mailbox.c b/mutt_mailbox.c
index ac40682af..7e32706b0 100644
--- a/mutt_mailbox.c
+++ b/mutt_mailbox.c
@@ -191,10 +191,10 @@ int mutt_mailbox_check(struct Mailbox *m_cur, int force)
   {
     check_stats = true;
     MailboxStatsTime = t;
+    MailboxCount = 0;
   }
 
   MailboxTime = t;
-  MailboxCount = 0;
   MailboxNotify = 0;
 
   /* check device ID and serial number instead of comparing paths */
```

Addendum: I didn't test it but this looks like a regression caused by 0bef239d6e04316ab151bc34ea0a10750b70cfc7. Maybe the check on `check_stats` should be around just the `mx_mbox_check_stats()` call, i.e. if `!check_stats` then just look at `m_check->has_new` when deciding whether to increment `MailboxCount`? The different paths tatken around here by the `mail_check_stats` setting make things pretty tricky.

**Comment by vuori** [comment]
So after digging a bit more, it seems to me that https://github.com/neomutt/neomutt/pull/3023/commits/46dcb33f21ce87529512841ecab352efff5bad5a should be reverted and the problem mentioned in the PR https://github.com/neomutt/neomutt/pull/3023 regarding Notmuch ignoring the `check_stats` flag should be fixed in the Notmuch backend instead?

While second-guessing the backend in `mailbox_check()` can be made to work, it seems like a recipe for trouble in the future, especially when there's already a mechanism for telling the backend not to calculate stats.

**Comment by Austin-Ray** [comment]
@flatcap : Should `next-unread-mailbox` be checking for mailboxes with new mail instead of unread mail?

The only documentation related to `next-unread-mailbox` states[0]:
> The (by default unbound) function `<next-unread-mailbox>` in the index can be used to immediately open the next folder with **unread** mail (if any).

I see three issues with the existing implementation:
 1. The function's implementation contradicts its name.
 2. The notmuch backend doesn't have a concept of new mail so `next-unread-mailbox` will never work for it.

[0] https://neomutt.org/guide/advancedusage#13-2-%C2%A0polling-for-new-mail

**Comment by flatcap** [comment]
> Should `next-unread-mailbox` be checking for mailboxes with new mail instead of unread mail?

Hmm...
I've just checked, and Mutt does the same -- **new** mail only

> open the next folder with **unread** mail

A quick delve into the history...
It seems that function was created ~14 years ago and barely touched since.
The original `<next-folder>` function: `"open next folder with new mail"`
It got renamed to `unread`, but the docs never changed.

I think that if we're going to change the behaviour, we should add a function for the **new** case.
- `<next-unread-mailbox>`
- `<next-new-mailbox>`

**Comment by vuori** [comment]
> A quick delve into the history...
> It seems that function was created ~14 years ago and barely touched since.
> The original `<next-folder>` function: `"open next folder with new mail"`
> It got renamed to `unread`, but the docs never changed.
> 
> I think that if we're going to change the behaviour, we should add a function for the **new** case.
> - `<next-unread-mailbox>`
> - `<next-new-mailbox>`

Note that as it stands, `next-unread-mailbox` goes to neither new nor
unread mailboxes with `master` for me due to cached MailboxCount
getting stuck at 0.

I much prefer unread meaning unread, but adding `next-new-mailbox` for
those who prefer unread=new would be nice I guess. The standard for
consistency is not very high though: `sidebar-next/prev-new` will
select non-new unread folders despite the name (they also are not
affected by `mail_check_recent` unlike `next-unread-mailbox`, at least
when `mark_old=no`).

**Comment by Austin-Ray** [comment]
> Mutt does the same -- new mail only

Does Mutt consider new mail to be new and unread? I remember having to fix an issue with the sidebar because NeoMutt changed its definition of new mail to exclude unread (might have been sidebar only, not sure.)

> cached MailboxCount getting stuck at 0.

I think we should drop the stat checking calls from `mutt_mailbox_next()` all together. It pre-empts the expected behavior of `mail_check` and isn't called out like `<check-stats>`. I don't see any reason why we need to update new/stats outside of the existing `mail_check` and `mail_check_stats` codepaths.

If we want to run a check during `next-new-mailbox`, we should be calling `mx_mbox_check()`, not using the existing codepath that uses `mx_mbox_check_stats()`. That way we're explicit in which data we're looking for.

What do you think, @flatcap?

**Comment by vuori** [comment]
Tested current master and the issue reported here seems to be fixed. Seeing at least some of the other wonkiness reported in https://github.com/neomutt/neomutt/issues/3072 with Maildir mailboxes, but anyway I'll close this since `next-unread-mailbox` now works.
