### ISSUE TITLE
NeoMutt with Notmuch 0.33.2 not returning results (due to difficult version detection?)

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#3182]
## Expected Behaviour

Execute a notmuch search in NeoMutt and get results.

## Actual Behaviour

The notmuch search always yields no results.

## Steps to Reproduce

I run `<vfolder-from-query>` with any query and it does not return anything.

## How often does this happen?

- Always

## When did it start to happen?

A bisect leads to 28786f79.

## NeoMutt Version

```
NeoMutt 20211029-153-ebbdb9
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.5-051505-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
libnotmuch: 5.4.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --asan --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR -fsanitize=address -O0 -fno-omit-frame-pointer -fno-common

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

Devel options:
  asan 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?
maildir

This is on Ubuntu 21.10. Version info for notmuch, installed from Ubuntu repositories, is here:

```
$ notmuch --version
notmuch 0.33.2
$ apt-cache policy notmuch
notmuch:
  Installed: 0.33.2-1ubuntu1
  Candidate: 0.33.2-1ubuntu1
  Version table:
 *** 0.33.2-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu impish/universe amd64 Packages
        100 /var/lib/dpkg/status
$ 
```

Here is my config.log, which I believe contains some important checks to figure out the Notmuch library capabilities: 
[config.log](https://github.com/neomutt/neomutt/files/7797849/config.log)

@Austin-Ray Thank you for dealing with this tricky Notmuch version issue. I appreciate your work!

**Comment by Austin-Ray** [comment]
This seems like it's going to be a tough one.

Do you know if this was present when you filed #3149? Both `neomutt -v` outputs include `libnotmuch 5.4.0` so if its that version check then it should have been affecting you then. In addition, I built neomutt 20211029-153-ebbdb9 against notmuch 0.33.2 and wasn't able to reproduce it which leads me to believe that it's not the version check.

Do the neomutt logs indicate if neomutt is clobbering the queries?

**Comment by Austin-Ray** [comment]
Thanks for grabbing logs on both sides bisected commit!

Ironically, commit 28786f7 was introduced to resolve similar failed appends for #3017.

Based on the logs, it looks like notmuch is returning paths rooted with `/home/scott/.mail` instead of the correct root of `/home/scott/.mail-ufl`. This leads me to suspect notmuch configuration. In your notmuch config, what's the value of `database.mail_root` (may be unset) and `database.path`?

**Comment by scottkosty** [comment]
> Based on the logs, it looks like notmuch is returning paths rooted with `/home/scott/.mail` instead of the correct root of `/home/scott/.mail-ufl`.

Good catch! I stared at the logs for a bit before I posted and did not catch that.

> This leads me to suspect notmuch configuration.

Which leads me to suspect user error :)

> In your notmuch config, what's the value of `database.mail_root` (may be unset) and `database.path`?

I have different not much configs for different email accounts (private and work). It seems that the wires are crossing. For my UFL account, my entire `~/.notmuch-config-ufl` (without commented out stuff) is:

```
[database]
path=/home/scott/.mail-ufl

[new]
ignore=cache
```

However, I also have a `~/.notmuch-config` file, which is for my personal email account, and has `path=/home/scott/.mail`, with the following contents:

```
[database]
path=/home/scott/.mail

[new]
ignore=cache
```

Thanks to your hint, if I copy the `database.path` from `~/.notmuch-config-ufl` and put it as the `database.path` for `~/.notmuch-config`, then everything works as expected. Thus, before it seems that only `~/.notmuch-config-ufl` was being relied on, but now, for some reason the search is done with `~/.notmuch-config-ufl` and then the files are read based on `~/.notmuch-config` ?

This makes me think that things were working just by luck before, and that my configuration is bad. But I can't figure out why. Actually, how does notmuch know to do the initial query using `~/.notmuch-config-ufl` ? I'm not sure where in my configs I tell notmuch to use that rc when I am using NeoMutt with my UFL account. So right now I'm more confused that the initial query is done with `~/.notmuch-config-ufl` than the subsequent query that uses `~/.notmuch-config`.

**Comment by Austin-Ray** [comment]
> Which leads me to suspect user error :)

After reading your message, not your error (nor notmuch's), but mine. There's some improvements I need to make to the notmuch integration and ASAP as I've broken your workflow. I'll aim to have a fix by the end of today.

The rest of this is a bit of a long technical answer so feel free to skip over it if you're not interested.

> Thus, before it seems that only ~/.notmuch-config-ufl was being relied on, but now, for some reason the search is done with ~/.notmuch-config-ufl and then the files are read based on ~/.notmuch-config?

Before commit 28786f7, we never loaded the config and, to my knowledge, libnotmuch was completely configuration-less before notmuch 0.32. Only the `notmuch` CLI used the configuration file. libnotmuch assumed the database and mail shared the same root, which is why it was possible to have multiple separate databases and just update `nm_default_url` to swap between them.

However, notmuch 0.32+ (libnotmuch 5.4.0+) allows separate database and mail directories but relies on libnotmuch loading a configuration so it can return correct file paths. Commit 28786f7 opens the database in a way that it will look for a configuration file so libnotmuch can do the correction. Unfortunately, in your case, this means notmuch loads the wrong configuration (`~/.notmuch-config`) and returns a  "corrected" paths that NeoMutt is unable to load. This results in the empty mail.

I wasn't as thorough as I thought in looking for different use cases. Apologies that my lack of thoroughness broke your setup.

> This makes me think that things were working just by luck before, and that my configuration is bad. But I can't figure out why. 

Fortunately, it isn't your configuration that's bad. It's my code.

> Actually, how does notmuch know to do the initial query using ~/.notmuch-config-ufl ?
> I'm not sure where in my configs I tell notmuch to use that rc when I am using NeoMutt with my UFL account. So right now I'm more confused that the initial query is done with ~/.notmuch-config-ufl than the subsequent query that uses ~/.notmuch-config.

Is this with the `notmuch` CLI or when using `neomutt`? I can't answer for the `notmuch` CLI, but for `neomutt`, based on the bad log, you start out in non-notmuch folder then execute the query. That explains having mail initially. If we're talking about mailbox stats, those are directly from the database without any file checking so they won't be affected by invalid paths.

**Comment by scottkosty** [comment]
> I'll aim to have a fix by the end of today.

Great, thank you! No worries if you can't get to it. I can easily work around this issue for a while.

> libnotmuch assumed the database and mail shared the same root

Ah, I think this indeed solves my confusion.

> The rest of this is a bit of a long technical answer so feel free to skip over it if you're not interested.

I enjoyed reading it. By the way, I appreciate your detailed commit messages. I don't know any of the technical details, and just read them out of curiosity, but it is fun to follow along.

> I wasn't as thorough as I thought in looking for different use cases. Apologies that my lack of thoroughness broke your setup.

You mean you didn't test the 5 billion possible combinations of NeoMutt configs interacted with every possible third-party version? :)

I am very thankful for your work, and I'm happy to test NeoMutt. I'm not always interested in testing development versions of software I rely on, but the NeoMutt team is so responsive, thorough with testing, and helpful that I almost get excited when I have a chance to do a bisect and report an issue.

**Comment by scottkosty** [comment]
In case anyone else comes across this issue, I think it may be a workaround to set the environment variable `NOTMUCH_CONFIG`. e.g.,:

    export NOTMUCH_CONFIG=~/.muttrc-config-ufl

**Comment by Austin-Ray** [comment]
Sorry it took so long to get back to this. I have a draft PR #3492 that adds the `nm_config_file` config option.

It can be set to a path (what you want), `auto` for auto-detecting a config (current behavior), or an empty string for no configuration at all.

Please let me know if it resolves your issue.

**Comment by scottkosty** [comment]
@Austin-Ray Thanks! I won't be able to test for a while as I'm on vacation.

**Comment by scottkosty** [comment]
@Austin-Ray  Sorry it took me so long to get back to you. I just tested master, which has the branch you referenced merged, and it seems to work well with respect to this issue. Thanks!
