### ISSUE TITLE
skip travis build automatically if non-code files were edited

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#319]
At the moment, we use travis to build our code. But travis runs at the moment on every commit - even when only documentation stuff was edited.

Of course we can use `[ci skip]` in the commit message to tell what to ignore - but some people (including me) keep forgetting that.

So, i think it would be useful, if we added some check to our [build file](https://github.com/neomutt/travis-build/blob/master/build) which skips the rest of the build if **only** certain files were edited.

I guess we could even go so far and ignore every commit in which no *.c or *.h file was edited?

**Comment by gahr** [comment]
-1 for me. The build also builds the docs, making sure the source xml files are correct. Any changes to autotools machinery should also go through the build process. The only files for which we could avoid the build are .mds and the READMEs...

**Comment by flatcap** [comment]
OK, @gahr let me see if I can convince you...

There are three things to be built: code, docs, translations.

The docs and translations depend on the code.
The contrib dir can't be checked, so can be ignored.

Travis tells us what's changed since the last build in `$TRAVIS_COMMIT_RANGE`.
This means we have enough information to work out which files have changed.
With a little light editing of the build script, we should be able to reduce the load on travis.

If changes occur in:
- **contrib**/ -- do nothing at all
- **doc**/ -- configure and build docs
- **po**/ -- configure and build translations

Otherwise build everything.

Currently, the [build script](https://github.com/neomutt/travis-build/blob/master/build), does two builds (controlled by the txt files in the [build repo](https://github.com/neomutt/travis-build).)
The build is configured with `--disable-doc --disable-po` for speed.

If travis is building the neomutt branch, it finishes by doing an extra build including the docs (with validation), "make dist" and "make distcheck".

**Comment by gahr** [comment]
This way, yes :)

**Comment by flatcap** [comment]
Things we can build/test:
* compile code (make) (build sets defined in [travis-build](https://github.com/neomutt/travis-build))
* test packaging (make dist, make distcheck)
* test install (make install, make uninstall)
* build/validate docs
* compile/validate translations
* validate scripts (shell, perl)

Riskier things we can do:
* Look for whitespace errors

**Comment by flatcap** [comment]
It's a good idea, but it's more likely that we will split up all the big repos and builds into smallers repos and build.
