### ISSUE TITLE
neomutt -e "push <search>imagine<enter>" no longer works

### ISSUE THREAD

**Issue by scottkosty** [neomutt/neomutt#3229]
## Expected Behaviour

I was executing the following command to find a particular message in my inbox:

    neomutt -e "push <search>imagine<enter>"

## Actual Behaviour

I get the following prompt:

    Create earch>imagine? ([yes]/no):

## How often does this happen?

- Always

## When did it start to happen?

Bisect leads to 89811bea.

## NeoMutt Version

```
NeoMutt 20211029-266-785837
Copyright (C) 1996-2020 Michael R. Elkins and others.
NeoMutt comes with ABSOLUTELY NO WARRANTY; for details type 'neomutt -vv'.
NeoMutt is free software, and you are welcome to redistribute it
under certain conditions; type 'neomutt -vv' for details.

System: Linux 5.15.5-051505-generic (x86_64)
ncurses: ncurses 6.2.20201114 (compiled with 6.2.20201114)
libidn: 1.33 (compiled with 1.33)
OpenSSL: OpenSSL 1.1.1l  24 Aug 2021
libnotmuch: 5.4.0
storage: tokyocabinet

Configure options: --ssl --sasl --enable-notmuch --enable-debug --tokyocabinet --prefix=/usr/local

Compilation CFLAGS: -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/local/include -DNCURSES_WIDECHAR

Default options:
  +attach_headers_color +compose_to_sender +compress +cond_date +debug 
  +encrypt_to_self +forgotten_attachments +forwref +ifdef +imap +index_color 
  +initials +limit_current_thread +multiple_fcc +nested_if +new_mail +nntp +pop 
  +progress +quasi_delete +regcomp +reply_with_xorig +sensible_browser +sidebar 
  +skip_quoted +smtp +status_color +timeout +tls_sni +trash 

Compile options:
  -autocrypt +fcntl -flock -fmemopen +futimens +getaddrinfo -gnutls -gpgme -gss 
  +hcache -homespool +idn +inotify -locales_hack -lua -mixmaster +nls +notmuch 
  +openssl +pgp +regex +sasl +smime -sqlite +sun_attachment 

MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/neomutt"
SENDMAIL="/usr/sbin/sendmail"
SYSCONFDIR="/usr/local/etc"

To learn more about NeoMutt, visit: https://neomutt.org
If you find a bug in NeoMutt, please raise an issue at:
    https://github.com/neomutt/neomutt/issues
or send an email to: <neomutt-devel@neomutt.org>
```

## Extra Info

* Is your email local (maildir) or remote (IMAP)?

maildir

**Comment by flatcap** [comment]
Argh!
I renamed some functions, internally, to make it clear _what_ they worked on.

`<search>` in the Index works as expected, but I forgot how the "generic" functions would work, e.g when you run commands.

I might have to revert that commit and rethink it.
Thanks

**Comment by scottkosty** [comment]
Thanks for the quick response! No hurry. Reverting would help me to keep daily-driving master, but on the other hand I understand there will be work-in-progress left in master so it's not a problem if you prefer to leave it and fix it when you can.

**Comment by dcpurton** [comment]
This also breaks my hack for creating a `multipart/related` email which uses a macro which reads in a rc file containing `push "<search>…"`.

**Comment by dcpurton** [comment]
As a work around, I notice that using the bound key works. I.e.,

```
push "/…"
```

**Comment by flatcap** [comment]
Well!  That's sent me down a deep key-handling rabbit hole!

> `push <search>imagine<enter>`

The `push` command puts data in the macro buffer, but it _interprets_ it first.
Or tries to.

Because this is happening as the result of `neomutt -e 'xxx'`, there isn't an Index, yet.
Despite that, `push` looks through **all** the menus for a match to `<search>`.

Index doesn't implement `<search>`, it relies on the 'generic' menu to provide it (as `OP_SEARCH`)
Pager **does** implement `<search>`, but I've redirected that to `OP_PAGER_SEARCH`.
The 'generic' menu implements `<search>`, but it's last in the list so it's not reached.

`push` discovers `OP_PAGER_SEARCH` and stacks it:
- OP_PAGER_SEARCH
- "imagine"
- `<enter>`

Now things get weird.

When the Index starts, it asks for a keypress.
NeoMutt looks to see if there's anything in the macro buffer, and finds something: `OP_PAGER_SEARCH`.
Hmm... but _that_'s not an Index function.
So it decides to reverse-engineer the OP.
It looks up the op in **all** the menus until it finds a match: `OP_PAGER_SEARCH` == `<search>`
OK, it thinks, _that_'s what the user must have wanted.

NeoMutt now pushes the characters `<`, `s`, `e`, ... into the "unget" buffer.

Finally, NeoMutt take the first character '<' and looks up _that_ and finds `<` == `OP_PREV_LINE`
Index performs `OP_PREV_LINE`

Next comes the `s`, which is `OP_SAVE`
Then NeoMutt helpfully fills the save prompt with `earch<imagine` and hits `<enter>` for us.

---

**Conclusion**: I need to back out the Pager function renames.

**Comment by scottkosty** [comment]
Thanks for that detailed information! When I first did the bisect I thought "hmmm I wonder if flatcap just missed one that needed renaming" and almost tried to figure out a superficial patch. I'm glad I didn't :)

**Comment by scottkosty** [comment]
@flatcap  Would it be a not-too-difficult task to write a test for this issue? I don't have much time these days, but when I do have time I want to learn more about writing tests since that seems to be another way to contribute to NeoMutt without knowing enough to provide bug fixes. If this would be a good candidate, I'll make a note to come back to this "someday".

**Comment by ebblake** [comment]
I just built with commit 0b9a85aa included (the revert of the pager search rename), but I'm still running into wonkiness with my:
```folder-hook . 'push <collapse-all><last-entry><half-up>'```
behaving as if I typed a literal '<' then 'c'.  I'm not sure if it was that hook, or an earlier one, where push got confused, but note that <half-up> was one of the commands changed in commit b26b0072, next door to the just-reverted 89811bea8; and that if I build before that point, the wonkiness goes away.

**Comment by flatcap** [comment]
Urgh, more pager functions.
OK, thanks.  I'll fix them too.

I was aware that I'd left some un-reverted, but I couldn't think of a use-case that'd need to run motion functions blindly :-)

**Comment by flatcap** [comment]
Please can you give branch [[devel/revert]](https://github.com/neomutt/neomutt/tree/devel/revert) a try.

Thanks

**Comment by ebblake** [comment]
yes, that branch gets me back to normal behavior
