### ISSUE TITLE
20220408: TAB on last new message not exiting message view

### ISSUE THREAD

**Issue by 0-wiz-0** [neomutt/neomutt#3359]
Before the last release, pressing `TAB` while viewing a message would show the next unread message, and if there was none, return to the index view, closing the message.

This was helpful because the highly visible status change clearly showed that there were no more new messages, compared to not having pressed `TAB` or the `TAB` not going out via the SSH connection yet.

Pressing `q` on the last message also returns to the message view, but if there's a laggy SSH connection to the host and two `q`s were pressed and sent, the second `q` will quit neomutt.

**Comment by flatcap** [comment]
Sorry about that.  It should be fixed in ccde81231 (already merged into `master`).
(There's a new release planned for tomorrow)

> second `q` will quit neomutt.

You got a couple of options:
- `set quit = ask-yes`
  Ask before leaving
- `bind index Q exit; bind index q noop; bind generic q noop`
  Disable <kbd>q</kbd> for the index and use <kbd>Q</kbd> instead.
  (binding the generic menu may cause side-effects)

Please can you give `master` a try.
Thanks

**Comment by 0-wiz-0** [comment]
I've just tried master and `TAB` seems to work fine again.
Thanks for the quick fix!
