### ISSUE TITLE
Duplicated functions: `<refresh>` vs `<redraw-screen>`

### ISSUE THREAD

**Issue by darrel-glud** [neomutt/neomutt#3415]
## Expected Behaviour

Consistent UI and/or proper documentation.

## Actual Behaviour

The generic menu has `<refresh>` (bound to `^L`) with the description "clear and redraw the screen", while in the pager menu has `<redraw-screen>` (bound also to `^L`) with the same description.
A quick test suggests that the pager does not have a `<refresh>` and index does not have `<redraw-screen>`.

Thus: What is the difference between the two?
If there is one, that should be documented.
If there is none, I consider this a bug and one of the two should be deprecated (I suggest deprecating `<refresh>` because of the less descriptive name) and eventually be removed. Until then I suggest introducing an alias for backwards compatibility.

**Comment by flatcap** [comment]
Good spot!
This is one of those legacy problems that are proving difficult to undo.

The first Mutt commit (24 years ago) contains this distinction.
https://github.com/neomutt/upstream-mutt/blob/1a5381e07e97fe482c2b3a7c75f99938f0b105d4/functions.h

The `generic` menu roughly matches `struct Menu` in the code -- it's behind all the lists, like the Index.
Because the Pager doesn't have a list, it doesn't use the `generic` menu.
But, it still needed a `<refresh>` function.
`$deity` knows why they chose a different name for it.

I'd like to get rid of the `generic` menu altogether, but it's tricky.
I recently moved one function out of `generic` into the separate menus that needed it.
That needed quite a few workarounds.

For now, I'll add a `<refresh>` alias for the Pager and kill any references to `<redraw-screen>`.

**Comment by darrel-glud** [comment]
Thanks @flatcap for the archaeological tour (quite a lot of empty lines there...).
I created PR #3418 which is a naive attempt of doing that.

**Comment by darrel-glud** [comment]
@flatcap wrote:
> I'd like to get rid of the generic menu altogether, but it's tricky.
> I recently moved one function out of generic into the separate menus that needed it.
> That needed quite a few workarounds.

Interesting thought.  While searching for the `<refresh>` stuff, I noticed that `<show-version>`, which is in Pager and Index but not in other menus and which I would have moved into the generic menu so it is accessible everywhere.
(I also noticed `<exit>` and `<quit>` all over the place but I better not touch those.)

**Comment by flatcap** [comment]
> I noticed that `<show-version>`, which is in Pager and Index but not in other menus

Yes.
It gets a bit tricky with key-bindings.
You can't bind a key to a function that's in `OpGeneric`, unless it's in the current Op as well, e.g. `OpIndex`, `OpPager`.

I've got a reasonable understanding of how things fit together,
but I haven't got a plan for improving them yet.

> I also noticed `<exit>` and `<quit>` all over the place

hehe, yeah.  I'm not brave enough to mess with them
