### ISSUE TITLE
A million question lol

### ISSUE THREAD

**Issue by SingularisArt** [neomutt/neomutt#3571]
I've got a couple of questions (actually, I've got a lot lol). I couldn't find the answers to any of them in the documentation. So, here I go.

1. I would like to sync my changes from my local mail to my Gmail server. For example, when I mark an email as read, I also want Gmail to mark that as read as well.
2. How can I search with notmuch for specific accounts? I've currently got 5 emails setup, where mbsync clones all of them. I then run `notmuch new`. How can I parse those tags based on what account I'm currently using? For example, if I'm viewing my `email-1@gmail.com` account, how can I search for the phrase, say, `read more`, and have notmuch display all the emails in the `email-1@gmail.com` account with the phrase `read more`?
3. Creating/renaming/removing folders and have that update on my Gmail server. I would like to be able to create, rename or remove folders on my local mail, and then have Gmail update. I looked into the documentation and it appears that I can only create a folder when I'm directly logging into neomutt, via Gmail, but I'm just syncing my emails.
4. Automatically display all folders. Each account of mine has dozens of folders and subfolders. Instead of manually typing `mailboxes "=folder1" "=folder1/subfolder1" ...`, how can I make neomutt load all those folders.
5. How can I create filters? For example, if an email is `something@gmail.com`, I would like to put that into the `something` folder.
6. Accept calendar invitations. How can I accept calendar invitations in neomutt? Is there a separate program that I should be using to accept/decline it and send the email to the owner?
7. When create the following keybind: `bind index,attach,pager,browser,query,alias,compose q exit` (the reason I'm doing this is because I remove all neomutt's default keybindings) and if I mark something as read/unread and quit, it doesn't take effect when I open neomutt again. For example, let's say I have the email `email-1` unread. When I open it up to view it, it changes from unread to read. But when I leave neomutt with `q` and open it up again, it goes back to unread. Why does this happen?

Finally, I just want to say thanks for making this program. It's really fun to tinker around and it's been of great use to me!

**Comment by gahr** [comment]
I'll give you pointers for the questions I can comment on

1. I understand you are using mbsync. NeoMutt has a `sync-mailbox` command to sync with the backend. Mbsync should then pick it up and propagate it, but that is best asked elsewhere I guess
2. I don't use notmuch, I don't know
3. there is an open PR in progress (#2853) to add support for creating folders for local maildirs
4. you can expand the result of a shell command into your mailboxes argument, e.g.,
    ```
    mailboxes `find /path/to/my/maildir -type d -name cur | xargs dirname | xargs`
    ```
5. NeoMutt doesn't filter incoming mail. This needs to be done earlier, perhaps in gmail itself in your case?
6. see if https://neomutt.org/contrib/useful-programs#calendar-tools gives you any useful pointers
7. probably because you're not syncing back your changes. On a default configuration, changes are written back to disk when you quit NeoMutt. Can you see if this works as expected if you use an empty config file / don't disable everything?

**Comment by gahr** [comment]
You need a pipe `|` at the end of the source argument, if you want NeoMutt to invoke the script and read its output. Not sure if it can read arguments, though. See https://neomutt.org/guide/configuration.html#source.

**Comment by gahr** [comment]
I am going to close this. Please, can you open one issue for one question, if you still have any?
