### ISSUE TITLE
Add (or ignore) missing 'new' and 'tmp' dirs when opening a maildir

### ISSUE THREAD

**Issue by acarrico** [neomutt/neomutt#3586]
I've used git to sync a maildir tree to another machine. The problem is that git doesn't add empty directories, so often you will get a directory with files like ```~/Mail/foo/cur/xxxxx.xxxx.xxx```, but no ```~/Mail/foo/new``` or ```~/Mail/foo/tmp```. Such dirs will provoke ```mx_path_probe() unable to stat =foo/: No such file or directory (errno 2)``` in the log, and the user interface status line will report ```(no mailbox)```. Once I realized the problem, I manually created those two directories, and the maildir does open correctly in NeoMutt.

Perhaps NeoMutt should create empty ```new``` and ```tmp``` directories when opening such a maildir. NeoMutt actually already does this in certain circumstances, for example, saving a message to such a maildir will "repair" it.

I decided to report this issue in case it will help others who happen to have the issue, but I understand that this may be out of scope for the project, so I labeled this issue as a feature request rather than a bug report. Feel free to close the suggestion.

**Comment by gahr** [comment]
Yes, we create `cur`, `tmp`, and `new` directories, if they're missing, when we're opening a maildir for writing. One of the reasons is that NeoMutt allows you to write into a non-existing maildir, so it needs to be able to create the full structure.

However, when we open a maildir for reading, we expect the structure to be there, at least to understand that it's a maildir. Specifically, we require the `new` and `cur` directories to be there, because that's where we read messages from.

We could consider relaxing the constraint and read from `cur` and `new` if they are there, and only fail if none of them are. It's not clear what the consequences would be, though. Should we create any missing directories in that case? What if we're opening a maildir in read-only mode? Does the rest of the code expect `cur` and `new` to be there?

**Comment by acarrico** [comment]
I can understand that you use the directories to identify a maildir, and that you might not want to touch a directory you are opening read-only.

Options:

* Is there any question of confusing a maildir missing its ```new```/```tmp``` with an mbox (or some other format)? If not, in read-mode, perhaps treat a missing ```new```/```tmp``` like an empty ```new```/```tmp```; maybe identifying a directory with some subset of ```cur```/```new```/```tmp``` as a maildir like.

* Keep everything the same, but improve the report to the user. This is probably the best and easiest solution. Currently neomutt reports "(no mailbox)", but it takes some user sophistication to jump from that to, "oh, there is a missing subdirectory in my maildir."

* One step up from that would be a user dialog, "Maildir =foo missing ```new``` subdirectory. Fix? Y/N"

* Or just close this issue as not-a-bug. After all, I could just write some script to fixup my maildirs after git! I'm mainly reporting this because it can be confusing if you happen to run into this problem and you aren't familiar with the format. Truthfully this is a git design flaw, as many have argued in the past.
