### ISSUE TITLE
Website says Fmemopen feature is disabled due to an unsolved bug - but no bug is listed.

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#361]
The description of the [fmemopen feature](https://www.neomutt.org/feature/fmemopen) says:

> fmemopen has been disabled until an awkward bug has been fixed

but the section `4. Known Bugs` says no bugs exist for this feature, which is contradictory. 

*(as far as i understood, everything in neomutt.org/feature is also generated from the docs folder, therefore i post this issue here)*

**Comment by flatcap** [comment]
Good call.

`fmemopen` was in widespread use until one person found one problem, intermittently, on one arch.
I couldn't find the problem at the time, but I thought it serious enough to disable for all users.
This is a shame, because it should improve performance (I haven't any data to back that up).

**Comment by flatcap** [comment]
It was a repeatable crash for someone using "torify" around mutt.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834408

**Comment by gahr** [comment]
Doc fix was merged.
