### ISSUE TITLE
Cannot set $sidebar_divider_char to ""

### ISSUE THREAD

**Issue by whitney-cumber** [neomutt/neomutt#3750]
## Expected Behaviour

Be free to $sidebar_divider_char to "", always regardless of background colour.
(Personally, I do not understand why the requirement to have a background colour set.)

## When did it start to happen?

on Feb 27, 2023, 1:59 PM UTC and 29 seconds to be precise.

**Comment by flatcap** [comment]
History, as always :-)

The user wasn't allowed to set an empty divider char, because of some magic going on behind the scenes.

In combination with the `$ascii_chars` variable, ncurses tries to gracefully degrade to an ASCII `|` (pipe char).

Because most users would want a Unicode `│` (vertical line), but may not have been able to type it, the code interpreted an empty string as that.
