### ISSUE TITLE
 undefined reference `init_extended_pair`

### ISSUE THREAD

**Issue by juppytt** [neomutt/neomutt#3837]
I get this error in Ubuntu 18.04 when building neomut with the default config.
```
libcolor.a(curses.o): In function `curses_color_init':
curses.c:(.text+0x229): undefined reference to `init_extended_pair'
```

libncurses6.1 may not support extended colors if it is not built with `with_ext_colors`. 

https://github.com/neomutt/neomutt/blob/fc0cb3b7491eedd129706fb1484ea56610256637/color/curses.c#L106-L108

Line 106 should check whether `NCURSES_EXT_COLORS` is defined.

**Comment by flatcap** [comment]
> in Ubuntu 18.04

Oh.  I'd consider upgrading if you're able -- a lot's changed since 2018 :-)
(Unless it's a work thing)

> libncurses6.1 may not support extended colors if it is not built with `with_ext_colors`.

Ah!  Our new feature depends on `init_extended_pair()`.

> Line 106 should check whether `NCURSES_EXT_COLORS` is defined.

I've pushed a fix to disable the entire feature if it's not defined.
 Please can you give branch [[devel/colour]](https://github.com/neomutt/neomutt/tree/devel/colour) a try.

Thanks

**Comment by juppytt** [comment]
It builds well. Thanks!

**Comment by flatcap** [comment]
Great!  Merged.
