### ISSUE TITLE
syntax highlighting inside mails

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#394]
I think this would be a really great feature, but I'm not sure how realistic it is to implement.

* [Pygments](http://pygments.org/faq/) can print out ANSI sequences (console output)
* [markdown lexer for pygments](https://pygments-markdown-lexer.readthedocs.io/en/latest/)

**Comment by guyzmo** [comment]
I think this is not directly a desirable feature.

The first question is *when* do you want to show highlighted syntax?

The only use case is when a given mail actually use some sort of parseable formatting. Those are html on one hand, and all the wiki syntaxes on the other.

So what you really want is to change the content type of a (e.g.) markdown content within a `text/plain` file, into a `text/markdown`, and have it associated with a `mailcap` entry that can parse the markdown and output the code parts with ANSI-like colourisation.

Then we might want to have mutt accept to show ANSI colours in the pager, if it's not already the case.

**Comment by d-k-c** [comment]
I'm not for this feature, but another possible situation is patches. Usually they are sent as plain text, and basic coloring helps a lot for readability (like `git diff --color`).

**Comment by guyzmo** [comment]
again, if the diff is a mime attachment, you can use some external program to colourise it properly. We just need to make sure mutt can handle ANSI colour (or 24bit colouring) within the pager, everything else is not mutt's problem.

**Comment by ElDeveloper** [comment]
>  another possible situation is patches

FWIW, I have had (on and off) a few highlighting rules specifically targeting git patches and github emails:

```
# http://karelzak.blogspot.com/2010/02/highlighted-patches-inside-mutt.html
# diffs coming from github, thanks to @adamrp, for making this work better
color body green color234 "^(\>\ )*diff \-.*"
color body green color234 "^(\>\ )*index [a-f0-9].*"
color body green color234 "^\(\>\ )*\-\-\- .*"
color body green color234 "^(\>\ )*[\+]{3} .*"
color body brightgreen color234 "^(\>\ ){1,}[\+].*"
color body brightred  color234 "^(\>\ ){1,}[\-].*"
color body cyan color234 "^(\>\ ){1,}@@ .*"
```

Though GitHub has ever-since changed the format of the diffs they send over email, so these rules won't work very well anymore.

---------

Recently, I also came across these rules, but I haven't tried them:

```
### the following list of expressions are taken from:
### https://raw.githubusercontent.com/jessfraz/dockerfiles/master/mutt/.mutt/mutt-patch-highlighting.muttrc
# Patch syntax highlighting
# #color   normal  white           default
# color   body    brightwhite     default         ^[[:space:]].*
# color   body    yellow          default         ^(diff).*
# #color   body    white           default         ^[\-\-\-].*
# #color   body    white           default         ^[\+\+\+].*
# #color   body    green           default         ^[\+].*
# #color   body    red             default         ^[\-].*
# #color   body    brightblue      default         [@@].*
# color   body    brightwhite     default         ^(\s).*
# color   body    cyan            default         ^(Signed-off-by).*
# color   body    cyan            default         ^(Docker-DCO-1.1-Signed-off-by).*
# color   body    brightwhite     default         ^(Cc)
# color   body    yellow          default         "^diff \-.*"
# color   body    brightwhite     default         "^index [a-f0-9].*"
# color   body    brightblue      default         "^---$"
# color   body    white           default         "^\-\-\- .*"
# color   body    white           default         "^[\+]{3} .*"
# color   body    green           default         "^[\+][^\+]+.*"
# color   body    red             default         "^\-[^\-]+.*"
# color   body    brightblue      default         "^@@ .*"
# color   body    green           default         "LGTM"
# color   body    brightmagenta   default         "-- Commit Summary --"
# color   body    brightmagenta   default         "-- File Changes --"
# color   body    brightmagenta   default         "-- Patch Links --"
# color   body    green           default         "^Merged #.*"
# color   body    red             default         "^Closed #.*"
# color   body    brightblue      default         "^Reply to this email.*"
```

**Comment by toogley** [comment]
@ElDeveloper Great idea.

**Comment by d-k-c** [comment]
I also use this kind of coloring, but it impacts all emails, so it can have some side effects (for instance, where list elements starts with a dash).

**Comment by guyzmo** [comment]
well, it could be used with a hook that will only format mails from places where you expect diffs from!

otherwise, it's pretty great, I've added that ☺

**Comment by ElDeveloper** [comment]
@d-k-c, that has indeed been a problem! What needs to happen is that someone needs to come up with some very github-specific regexes that will do the trick, but then again, once GitHub's emailing format changes, those will need to be updated so ` ¯\_(ツ)_/¯`.

**Comment by guyzmo** [comment]
another argument for a lua scripting integration, along with some way of distributing and updating plugins ☺

**Comment by xdgc** [comment]
One of the guiding principles in mutt has been to think of new features as specific cases of broader scenarios. Don't implement in code what you can do in external processes, but do everything possible to empower externals.

Consider implementing this as an external display filter rather than coding it into neomutt. Here's what I would encourage:

1. extend display_filter to accept a stack of filter programs, which are executed in series.
1a. Design and implement a protocol for these: e.g.
* exit status 0 -> filtering complete; terminate stack
* 1 -> filtering performed; continue stack
* 2 -> no filtering performed; continue stack
* 255 -> error; note stderr and continue stack
1b. Permit display_filters to give literal display codes to the paging engine (i.e. bypass normal ansi regex processing). Invent some signal that this is what you're doing. It could be a flag in the display_filter definition, or you could simply define a new display_filter variable with a different name.

2. Write a filter that detects highlightable content. Implement it however you like, and update it when git flips again.

3. Publish it and announce that you have a new, hyper-flexible framework for display filtering instead of saying you can colorize git patches and logging a bug when that breaks.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).
