### ISSUE TITLE
Use of gpg's group option

### ISSUE THREAD

**Issue by Polichronucci** [neomutt/neomutt#404]
GPG has an option to define groups in order to add an alias email as recipient in an email and encrypt it with multiple keys. This doesn't work with Mutt or NeoMutt because the %r variable passed to the gpg command in gpg.rc is a keyid/fingerprint and not an email address.

I have not thought this through how this can be managed. Thunderbird with the Enigmail plugin manages this through the menu entry "Edit Per-Recipient Rules".

**Comment by flatcap** [comment]
Is this a commonly-used feature of gpg?
Who would an email be addressed to? Multiple people or just the alias email?
What is the command line for gpg that you'd need?

If you can explain the steps, we can figure out what we'd need to change.

**Comment by flatcap** [comment]
It's a useful idea, but nobody seems to have any time to code it.

If someone volunteers to work on it we can re-open the issue.

This issue has been added to a list of [closed discussions and blue-sky ideas](https://www.neomutt.org/dev/discussions).

**Comment by libBletchley** [comment]
@Polichronucci 
That group config is ignored by the `gpg --list-keys` command, which I find unfortunate.  Here's a feature request to improve that in gpg: https://dev.gnupg.org/T3495

I think mutt could improve as well.  That is, when a msg is sent to someone for whom there is no `crypt-hook` set, mutt doesn't even try to get a shortlist of possible matches.  It just bluntly asks for the key ID (which no user is likely to enter by hand), and then shows the entire keyring if none is entered.  Since gpg's `--list-keys` command can accept a list of strings, which may be IDs, names, or addresses, it would be useful if mutt took advantage of that by adding two more substitution tokens:
```
%e <= email address of the recipient (parsed from the "name" <email@address.com> format if needed)
%n <= name of the recipient (parsed from the "name" <email@address.com> format)
```
Then someone could define `pgp_list_pubring_command` as: `gpg --no-verbose --batch --quiet --with-colons --with-fingerprint --with-fingerprint --list-keys %?e?%r %e %n?`.  The mutt could show a shortlist (based on the existence of an e-mail address), and if the user rejects shortlist, mutt could then act as if `%e` is empty and run the command again to give a long list.

That would add convenience to all cases where there is no `crypt-hook` set, and it would also cover your need, which is to have a gpg group included in the key selection (of course, the groups would only work if the gnupg project also implements https://dev.gnupg.org/T3495).

**Comment by varac** [comment]
I'm appreciate this feature too!

**Comment by Hasimir** [comment]
@lilBletchley I'd need to double check the list archives to be sure, but I believe this issue is raised periodically and IIRC the problem with doing what is suggested in that feature request is the high potential of creating a recursive loop of key lookups.

The issue is that group lines are set by associating a string with a number of keys identified by key ID or fingerprint.  Both of which are values which will return in a --list-keys.  Now depending on what precisely you set that group ID as, you could very easily create a group identifier which would invariably result in the GPG becoming trapped in a loop of lookups matching the group itself and then trying to resolve it.

It may be possible to implement as a new command and the group data is already accessible via an alternative command.  Specifically bt rubbing this:

    gpgconf --list-options gpg | grep ^group
	
This will output all the group entries on a single line in a form similar to the --with-colons output.  Except for the first group line, the rest are separated from each other with a `,"` and scripting that through additional filters ought to spit out output which could either be used to generate crypt-hooks dynamically or utilise the keys directly.

Obviously that's not as nice as a command like --list-keys is, but it is there and potentially useable.
