### ISSUE TITLE
What's the current state of Lua scripting support?

### ISSUE THREAD

**Issue by ahmedelgabri** [neomutt/neomutt#4132]
The document here https://neomutt.org/2017/04/29/lua is 7 years old and mentions that the Lua support is in "testing" mode, so I wonder if anything changed?

**Comment by flatcap** [comment]
Basic, but working...
Lua support hasn't been improved since then, but it hasn't fallen into disrepair, either.

You can get/set variables, run `:command`s, execute `<function>`s.

**We need help** to make it do more

---

@jindraj has created a couple of lua scripts (of differing usefulness ;-)

- [change_color_scheme.lua](https://github.com/jindraj/dotfiles/blob/master/.neomutt/lua/change_color_scheme.lua)
  Randomise the colour scheme
- [rotate_window_timebase.lua](https://github.com/jindraj/dotfiles/blob/master/.neomutt/lua/rotate_window_timebase.lua)
  Change the Notmuch time window

---

The big thing that's missing is some form of **introspection**...

We need functions to:
- Get the current Mailbox
- Get the current Email
- Get the subject of an Email
- etc

It wouldn't be _that_ hard to do, but I don't have the time and nobody's volunteered.
I'll always **make** time to help others help NeoMutt.

**Comment by ahmedelgabri** [comment]
Thanks for the answer @flatcap. I will close the issue then.
