### ISSUE TITLE
Lines suspicious of being a memory leak in smime.c

### ISSUE THREAD

**Issue by alejandro-colomar** [neomutt/neomutt#4169]
SMIME code, probably a couple of memory leaks:

<https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/smime.c#L666>

<https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/smime.c#L714>

Almost identic GPGME code:

<https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/crypt_gpgme.c#L3256>

<https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/crypt_gpgme.c#L3328>

I don't see any code in the implementation of `dlg_smime()` that suggests that it would require the caller to make a copy.  It is almost identic to `dlg_gpgme()`, which doesn't require it.

**Comment by flatcap** [comment]
> SMIME code, probably a couple of memory leaks:

Entirely possible, the code's seldom been looked at.

> I don't see ... that it would require the caller to make a copy

I _think_ we're OK.
The jobs of the dialogs is to select a key, but as you've spotted they return differently.

---

In `smime_get_key_by_addr()`, we get all the possible keys:
https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/smime.c#L616

and filter it down into `matches`, then have one of several paths:

https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/smime.c#L647-L670

In the Dialog path, the user selects a key -- this is one of the keys in `matches`:
https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/smime_functions.c#L53-L88

which is returned:
https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/dlg_smime.c#L262

All the paths in `smime_get_key_by_addr()` now call `return_key = smime_copy_key()` on the selection and then free `matches`:

https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/smime.c#L669

Finally, `smime_get_key_by_addr()` returns the single selected key:
https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/smime.c#L672

smime_get_key_by_str() follows the same pattern, but more simply.

---

> It is almost identical to `dlg_gpgme()`, which doesn't require it.

By contrast, in `dlg_gpgme()`, the user selection causes the key to be copied:
https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/gpgme_functions.c#L728-L785

then `crypt_getkeybyaddr()` keeps track of the copied key, frees `matches` and returns the selected key:

https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/crypt_gpgme.c#L3256-L3266

`crypt_getkeybystr()` works the same way.

---

Both methods work and I don't _think_ either leaks.
My preference of the two styles is for `dlg_smime()` -- the dialog **selects** a key from a list, but nothing else.

Looking through the code, there's room for improvement.
We could use `TAILQ` or `ARRAY`, rather than a homegrown `List` implementation,
but those upgrades might require a lot of changes.

**Comment by alejandro-colomar** [comment]
> > I don't see ... that it would require the caller to make a copy
> 
> I _think_ we're OK. The jobs of the dialogs is to select a key, but as you've spotted they return differently.


> By contrast, in `dlg_gpgme()`, the user selection causes the key to be copied:
> 
> https://github.com/neomutt/neomutt/blob/07e12e7742ded7200a2907fdd370b2c6f6af3d81/ncrypt/gpgme_functions.c#L728-L785

Ahh, this is what I was looking for but didn't find.

> Both methods work and I don't _think_ either leaks. My preference of the two styles is for `dlg_smime()` -- the dialog **selects** a key from a list, but nothing else.

Yup; me too.
