### ISSUE TITLE
merge bind and macro commands

### ISSUE THREAD

**Issue by toogley** [neomutt/neomutt#424]
At the moment, both `bind` and `macro` commands do IMHO very similar things - as far as i understand, `macro` just allows multiple function calls, bind only one.

That also means that we have two different parts of our code doing very similar things - therefore i think we can simplify our code.

## Additional Question:

* Does the usage of `bind` provide any advantage over `macro` ?
* as this will definitely break compatibility with upstream mutt, i'm not sure how we should proceed. What are your thoughts?

**Comment by guiniol** [comment]
I'm not sure I for that.
`macro` syntax is actually a bit different than `bind` because macro literally acts as if you typed whatever is in it's definition. In addition, you could break a lot of things in a `macro`, so understanding the difference with a simple `bind` is useful IMHO.

**Comment by guyzmo** [comment]
well, I believe that bind should get the ability to call a chain of commands. or, simply using Lua scripting you can leverage that (the binding call /one/ command, but that command is a lua function that does a bunch of stuff).

But there's a bigger task ahead on macros to make them more reliable (stop the macro upon failure of one command), and make it possible to record temporary macros (like vim's `q` command).

**Comment by guiniol** [comment]
If we have a specific syntax for `bind` to execute multiple commands in a row in a half intelligent manner instead of the "you typed a bunch of things very fast and I'm going to execute it through to the end whatever happens" that `macro`s have. We would at least need the equivalent of bash's `;` and `&&`. Ideally, we would need options for commands. What I mean is, look at the save entry command. You can write a macro to always save an attachment to the same folder. But what happens if a file already has the same name? You get a prompt to ask you if you want to overwrite it or not. Now imagine that prompt appears in the middle of your macro. How do you handle that in the macro? You *CAN'T*, because it only appears if some conditions are met, but your macro always process every single keystroke in the order you wrote them. Which is why I think the problem isn't that we have `bind` and `macro` but that it's way to easy to break stuff with the macros, and as such, I don't think we should merge them as is with bind.
