### ISSUE TITLE
Unit test suite using a minimal C Framework

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#428]
Here's my take at a minimal unit-testing framework in C.

The work is being carried out in the [feature/unit-test](https://github.com/neomutt/neomutt/tree/feature/unit-test) branch.

### Basics
1.  Unit-tests are based on the header-only [cutest](https://github.com/mity/cutest) framework. This provides a no-dependency, simple drop-in solution.
2. Unit-tests are compiled into the mutt executable when configured the `--with-unittest` flag and are executed with `mutt -T`.
3. Translation units implementing tests - ideally one for feature - are [included](https://github.com/neomutt/neomutt/blob/feature/unit-test/unit-test/driver.c#L9) in the `test/driver.c` main driver and [declared](https://github.com/neomutt/neomutt/blob/feature/unit-test/unit-test/Makefile.am#L5) in `test/Makefile.am`.
4. Single tests are [declared](https://github.com/neomutt/neomutt/blob/feature/unit-test/unit-test/driver.c#L13) in the `unit-test/driver.c` main driver.

### Example

```sh
$ ./mutt -T
Test list_create...             [   OK   ]
Test list_add...                [   OK   ]
Test list_find...               [   OK   ]

Summary:
  SUCCESS: All unit tests have passed.
```

### Discussion
The decisions I've taken - such as not building a separate `mutt-test` executable - are of course open to discussion. Feel free to comment and suggest improvements!

**Comment by gahr** [comment]
The first thing I would like to discuss is whether we want to unconditionally build and enable unit-tests, so removing the `--with-unittest` flag. I would be in favour of doing so.

**Comment by gahr** [comment]
Running unit tests has been integrated in Travis when building the `feature/unit-test` branch:

https://travis-ci.org/neomutt/neomutt/builds/204913282

**Comment by toogley** [comment]
As far as i understand, unit tests should not rely on dependencies (by that i mean typical things like databases, external servers, internet connection, filesystem, etc. pp.) (I have read this in a book called ["The art of unit testing"](https://www.manning.com/books/the-art-of-unit-testing-second-edition?a_bid=f6ea80f5&a_aid=iserializable)). 

How would you solve this issue with your minimal unit testing framework? That means, how would you mock external dependencies, such as imap server, notmuch database, maildir, etc. ?

**Comment by gahr** [comment]
> How would you solve this issue with your minimal unit testing framework? That means, how would you mock external dependencies, such as imap server, notmuch database, maildir, etc. ?

I would not tackle this problem just now/here. My intent is to have a functional unit-testing framework so we can assess the correctness of basic building blocks in isolation. Some simple mocks and stubs might be needed for certain parts, but I would defer testing, say, a complete connection and authentication to an IMAP server to a feature testing stage/space.

As a concrete example, speaking of IMAP, I would rather assess that `mutt_to_base64` works fine with a wide range of inputs and in the presence of particular corner cases rather than testing that a particular PLAIN authentication using a particular set of username/password against a particular IMAP server works fine *in that particular case*.

This is the basic difference between unit and functional or integration testing. Here and now, I am interested in the former only and I'm not advocating the usage of this framework for the latter.

**Comment by toogley** [comment]
Hm..

> The first thing I would like to discuss is whether we want to unconditionally build and enable unit-tests, so removing the --with-unittest flag. I would be in favour of doing so.

Why do we even have to compile the unit tests into the mutt binary? 

* Isn't that inconvenient, because if you change a small thing in the unit test or sth like that, you have to rebuild everything? or do i miss sth here?

* I'd like to have a time measurement for **every** test. Because when the one test takes the double/triple amount of time (compared to other tests), we probably won't notice that if we don't have a measurement set on. However, it might be a useful indicator that the unit test is not as good as we think it is. Maybe its not isolated enough, etc. pp. That means: How easily can we have that with your unit testing implementation?

> As a concrete example, speaking of IMAP, I would rather assess that mutt_to_base64 works fine with a wide range of inputs and in the presence of particular corner cases 

I agree with that. I think that's a very good starting point in testing the mutt source code.

**Comment by guyzmo** [comment]
* *[…] not building a separate mutt-test executable*: if you're running tests within the mutt executable, then you're not doing unit tests, you're doing functional tests. The difference being that you're running functions in the context of the application's runtime, and not within a controlled petri-dish environment. So this is a big no from me for doing it this way.
* a better way is to keep each test scenario self-contained, and ran as an independant executable, so that way we can more easily identify if there's an issue at compile time or a crash, or an implementation error, but still have the other test scenario work up to the end.
* using a BDD approach (cf #431 for a C version) is also a good idea, because it helps the developer writing the test focus on the behaviour (*usage drives implementation*), and helps whoever will read the test understand why it's there. It's also avoiding ending up with `test_1`, `test_2`, `test_3`… It's also homogeneous to the tests being writing with lua+busted, which is 👍.
* @toogley, *I'd like to have a time measurement for every test.*, we're not doing a benchmark (which can be another kind of tests), we're testing behaviour of functions. Testing for time spent doing a task is a different issue, and needs long running tests you only launch once in a while (because they take a lot of time).

-----------

(tl;dr: jump to bottom)

Then here comes my take on the discussion @gahr wants to have about unit tests.

We agree that functional testing is some sort of "blackbox" approach of testing the application using only the API directly accessible by the user within the application's runtime context, for which leveraging the embedded Lua interpreter's API is a nice way to go.

When you consider your application's full execution tree, what @gahr says is true when you only tests functions operating at the leaves, and for which you have little external context. Functions like `mutt_to_base64`, `mutt_*_list` etc. are perfect examples. They're purely algorithmical, and thus their tests are relatively easy to write.

But most of the time, functions of that category are the less likely to break, because once they've been proven to work as expected (because they're trivial, or they've been tested on paper, or using a non-included mockup…) and checked by many eyes, it's unlikely they will change, and they won't start breaking randomly. I mean, that function that translates base64 strings that has been around since 1999, is very unlikely to be broken, and it's unlikely to break any time soon.

But *textbooks* unit tests are there to test every single function that makes your application. From the low-profile low level ones, to the higher level ones. If your application is pure functional, then it'll be easy, and you won't need much overhead to test every bit of your app. But for an app like mutt, that's another story…

The real hard work is the stuff that goes in between of the public API (aka *User Interface*) and those "leaf" functions. There you'll have to mockup socket connections to an IMAP server, an NNTP server or a bunch of SMTP servers, writing or reading mockup mails from mockup mailboxes etc. All that using a mockup indexer and label system.

So, we need to think *why* we're adding tests. We don't really need *textbook* unit tests, where each and every function is tested for every possible input. Because we can't afford that: we neither have the manpower or the time to write that. Testing that the base64 convertion function that's been around since 1996 is indeed converting to base64 is adding very little value. I'm not saying we don't have a bunch of functions that handles complex algorithmics, but those come in a very limited number, and once you've proven they work, you don't need to test them every other morning.

Because we're refactoring code and changing things, what we *really* want is to protect ourselves from regressions, and prove new stuff we're adding actually work. And writing unit tests is the perfect thing for that.

So whatever solution we choose, it will be end up being complex and will need a lot of stuff to glue things together. And, thus, I believe C is not the best language for that, because it's not great at glueing things together, dynamic languages are far better at that, and that's how they're being used most of the time.

All in all, what can do the most can do the few. Testing those "leaf" functions can be done with a bigger workhorse, like the one I'm suggesting in the #415 PR. Going with a simpler framework won't cope with that. 

TBH, I'd rather go for using python as dynamic language, because it's self-explicit and it's a lot of helper libs to handle mockups, and do monkey patching of the environment the app will run in. But it comes with a weight and it's yet another language to add to mutt — as we've already got C, Muttrc, Lua, Shell, M4… So I thought going for Lua was a more sensible idea.

Then, @gahr, you've been worrying about having layers between your failing test and your code. Having a lot of code being executed between where you test and what you test does is not a real matter. Once the test works, if the tested code changes and the test stops not work, then it's not the intermediate layers that will be to blame, only the tested code.
And if it crashes, then *yes* you can throw a gdb at it, you can safely ignore the lua stack crap, and introspect your tested function. You'll see what really matters in the C side. The dynamic is just being sugar added on top of it, and dynamic languages come with ease of introspection.

-----

That being said, from this point on, I see three possibilities:

1. we go with a low profile C testing framework, and we run all the non-functional tests with it,
2. we go with a high profile dynamic language testing framework, and we run all the non-functional tests with it,
3. we go with both, the C testing framework to test what I called the "leaf" functions, those that are easy to test, and the high profile dynamic language framework to test all those intermediate level APIs.

I don't think that ① is a sensible option, ② has the advantage of offering a single place to look up all tests. ③ has the advantage to make @gahr happy for all the low profile unit testing, but still make it possible to cope with everything between functional testing and unit testing.

**Comment by toogley** [comment]
> @toogley, I'd like to have a time measurement for every test., we're not doing a benchmark (which can be another kind of tests), we're testing behaviour of functions. Testing for time spent doing a task is a different issue, and needs long running tests you only launch once in a while (because they take a lot of time).

Of course. But what i mean is: as far as i understand, unit tests should be really fast, that means a runtime of about <1 second (or so). When we have about 50 unit tests, we won't notice if one of them takes 10 seconds, but it may be hint that the unit test is not working really good - maybe its not isolated enough, or does things complicated, etc. pp.

**Comment by guyzmo** [comment]
@toogley a test might also be hanging because the load on the machine is running got very high which can happen because something in another container or another VM is momenteraly killing the performances of yours. For most checks, they're likely to take 1µs, and might get up to 10µs when something is slowing them down.

This is why in benchmark tests you run the same tested function like 1000000 times, so you can make a trend. If your test is taking 1s to run, you're reaching the target, if it's 1000010µs one iteration has been slowed down it's negligeable, if it's 10s, you've got a problem with your loop.

But you don't want to do that with all your tests, because you'd be slowing down all your tests. You'd want to do that only with meaningful tests, on algorithms you know are having a high time complexity, not the ones with a trivial complexity.

**Comment by toogley** [comment]
@guyzmo agreed.

**Comment by gahr** [comment]
No more relevant. I'm working on a slightly modified version of this.
