### ISSUE TITLE
Show message preview in compose view to verify attachment list matches message content

### ISSUE THREAD

**Issue by edi9999** [neomutt/neomutt#4415]
## Current Behavior

When composing a message in compose view, we can only see:
- Headers (To, From, Subject, etc)
- List of attachments 
- No preview of the actual message content

## Use Case

A very common email workflow is:
1. Write a message listing attachments, e.g.:
   "Please find attached:
   - Report Q1 2024
   - Financial summary
   - Team metrics"
2. Attach the files
3. Need to verify that all mentioned attachments are actually attached

Currently this requires:

- Press 'v' to check message content
- Switch back to compose view to see attachment list 
- Mentally compare the two lists
- Risk missing attachments because the lists are never visible simultaneously

This context switching:
- Makes it easy to miss attachments
- Increases cognitive load of comparing two separate views
- Slows down the composition process
- Could lead to embarrassing emails with missing attachments

## Desired Behavior
Show message preview below headers/attachments in compose view so users can:
- See their list of promised attachments
- Compare against actual attached files
- Verify everything matches before sending
- All in a single view without switching contexts

## Implementation Notes
This could be implemented as:
1. A new config option like `compose_show_preview` (boolean)
2. A preview pane below headers/attachments
3. Optional toggling via keybinding

## Current Workarounds
- Press 'v' to view content then switch back to check attachments
- Use external editor with $edit_headers
- No way to see both simultaneously in native compose view

## Environment
- NeoMutt version: 20240425
- Terminal: xfce4-terminal 0.8.10 (Xfce 4.16)

**Comment by flatcap** [comment]
Yep!  Good idea...  (How are your C skills? ;-)

Someone suggested the same on IRC about a year ago.
Back then, it might have been tough; now it should be do-able.
(In Mutt it would be a nightmare to implement)

First, NeoMutt has nested Windows, making it easy to show/hide a Window dynamically.

The next useful NeoMutt features are the Function Dispatchers.
They separate _Functions_ from _Windows_.

The tricky bit is the Pager itself.
It's still a mess, way too complicated to embed somewhere else.
However, we just need a Simple Pager -- nothing fancy, just page-able text.
A lot could be quickly cut'n'pasted.

---

**How would it work?**

- Config variable / Function to toggle visibility.
- Most emails won't have many attachments, so the Pager could be greedy and use all the remaining space.
- If there are lots of attachments, we could limit their space, like `$pager_index_lines`
- The "focus" would remain on the Attachment list, but <kbd>\<PageUp\></kbd>, <kbd>\<PageDown\></kbd> could be redirected to the Pager.

---

**Volunteers Needed**

NeoMutt doesn't have many developers and I'm permanently busy fixing and improving things.
However...

If anyone reading this has a some free time and some C coding skills, I will make time to Mentor.
I'm always happy to help others help NeoMutt :-)

Comment below, or find us on IRC: `#neomutt` on `irc.libera.chat` ([web client](https://kiwiirc.com/nextclient/irc.libera.chat/#neomutt))

Thanks! :heart:

---

**Current Compose Layout**
<img src="https://raw.githubusercontent.com/neomutt/gfx/main/screenshots/window/dlg-compose.svg">

**Comment by edi9999** [comment]
Hello @flatcap ,

Thank you so much for giving already so many details about how to fix the problem

I haven't done any C for about 7 years and it was tough for me, I guess it would take me way too much time to do this.

**Comment by flatcap** [comment]
No worries; I had to ask :-)

**Comment by flatcap** [comment]
Hmm...  We'll need some way to visually separate it from the other Windows.
If we were to put the preview _immediately_ beneath the Attachment List, we'd probably need another Bar (one-liner Window).
Or colours!

<img src="https://raw.githubusercontent.com/neomutt/gfx/refs/heads/main/screenshots/screenshot/dlg-compose-100.png">

**Comment by roccoblues** [comment]
Actually I'll try to put the preview between the headers and the attachments. For me that feels more natural:

```
[ help bar]
To:
From:
[ preview separator (whatever that'll be) ]
Hi Flatcap,

check out this cat image!

Cheers,
Dennis
[ Attacchment Bar ]
* cat.png
```

**Comment by edi9999** [comment]
Yes, that seems the most natural to me too

**Comment by roccoblues** [comment]
I started working on this here: https://github.com/neomutt/neomutt/pull/4437

**Comment by flatcap** [comment]
I've had a play with @roccoblues' PR and had a think.
As always, I've gone too far :-)
Some of my ideas are relevant, some more tangential!

Firstly, wow!
It works, it looks good.

## Configuration

Either:
- `set compose_preview      = yes`
- `set compose_show_preview = yes`

I think it should be enabled by default.
Most users won't read the release notes and never hear about our new features.

Do we want to support any Pager config?

- `$allow_ansi` -- Allow ANSI color codes in rich text messages
- `$markers` -- Display a '+' at the beginning of wrapped lines in the pager
- `$pager_context` -- Number of lines of overlap when changing pages in the pager
- `$smart_wrap` -- Wrap text at word boundaries
- `$tilde` -- Display '~' in the pager after the end of the email
- `$wrap` -- Width to wrap text in the pager

## Layout

Few users will have an 80x24 Terminal.
Whatever the size of Terminal, however many Attachments they have,
the default layout of Envelope, Preview and Attachments should be pleasing.

If there's enough space, neither the Preview nor the Attachments should be limited.

Otherwise, we probably want to set a maximum number of Attachments, or a minimum number of Preview rows.

- `"$compose_preview_min_rows"`
- `"$compose_attach_max_rows"`

If the Terminal is very short, perhaps we could hide the Preview, or just let the Attachments get clipped.

We should probably think of some way to test the possible layouts.

**Advanced Idea**

Make Page-Up/Down act on the entire Dialog.

The Dialog would comprise: Envelope, Preview, Attachments.
Each would use as many rows as they needed, possibly more rows than the screen had.
Page-Up/Down would move the set of { Envelope, Preview, Attachments } up and down.
(I have no idea how to implement this :-)

## Status Bars / Feedback

If the Preview displays a long email, it would be good to show some feedback on the position, e.g. "15%"

We could add this to the Compose Bar, but it's a bit far away from the Preview.
It might be better to upgrade the "Attachments" Simple Bar to a formatted Bar.
e.g. `|3 Attachments                  25%|`

This would require us to measure the email text (or count the lines).

We've already got `$compose_format` and use `$attach_format`.
It would probably have to be the unwieldy: `$compose_attach_status_format`

**Advanced Idea**

Create a Scrollbar Window.
This would be 1 character wide Window placed to the right of the Preview (or the Pager, etc).
This would be a simple, passive, Window listening to Notifications from the Preview.

## Functions / Bindings

Here's a list of all the Functions we _could_ implement.
This would allow the user independent control of the Preview.

We could bind Page-Up/Down by default.

Adding Search Functions would add complexity to the positioning of the text.
(also see Colours, below)

| Function                    | Opcode                       |
| :-------------------------- | :--------------------------- |
| `<preview-page-up>`         | `OP_PREVIEW_PAGE_UP`         |
| `<preview-page-down>`       | `OP_PREVIEW_PAGE_DOWN`       |
| `<preview-half-up>`         | `OP_PREVIEW_HALF_UP`         |
| `<preview-half-down>`       | `OP_PREVIEW_HALF_DOWN`       |
| `<preview-line-up>`         | `OP_PREVIEW_LINE_UP`         |
| `<preview-line-down>`       | `OP_PREVIEW_LINE_DOWN`       |
| `<preview-top>`             | `OP_PREVIEW_TOP`             |
| `<preview-bottom>`          | `OP_PREVIEW_BOTTOM`          |
| `<preview-search>`          | `OP_PREVIEW_SEARCH`          |
| `<preview-search-next>`     | `OP_PREVIEW_SEARCH_NEXT`     |
| `<preview-search-opposite>` | `OP_PREVIEW_SEARCH_OPPOSITE` |
| `<preview-search-toggle>`   | `OP_PREVIEW_SEARCH_TOGGLE`   |
| `<preview-toggle>`          | `OP_PREVIEW_TOGGLE`          |

**Advanced Idea**

NeoMutt supports an idea of a 'focussed' Window.

This would allow us to reuse a basic function like `<page-up>`,
whose behaviour would be determined by the Window it acted in.
Set Focus to the Attachment Window, `<page-up>` affects the Attachments.

## Colours

Currently, Compose only colours the:

- Envelope Headers region, e.g. `Bcc:`
- Security labels, e.g. `Encrypt`

The whole of Compose is also affected by some other colours:

- `normal` - Default colour for all of Neomutt
- `status` - Default colour for Status Bars

This means that the Preview Window needs a colour observer.

One way to save some space, would be to eliminate the Preview Bar
and instead colour the Preview, and/or the entire Envelope region.
A subtle difference in background colour would be enough to make it stand out.

The Preview is monochrome, which makes it nice and simple.
Applying all the layers of colour is what makes the Pager so complicated.

If we implement `<search>` and friends, we'd probably need to support `color search`.
Anything more than that, e.g. `color body`, would need Pager 2.0.

## Events / Notifications

The Preview Window can be affected by the following Notifications:

- Colour `MT_COLOR_NORMAL`
- Window
  - `NT_WINDOW_STATE` (visibility, resized)
  - `NT_WINDOW_DELETE` (shutdown)
- Email `NT_EMAIL` (edited)

**Note**: Editing the message can affect everything:

- The message itself
- Attachments, by the `attach:` keyword
- Security, by the `pgp:` keyword

## Problems

- Attachments take up one more row than they need
  (There's always a blank line)

- Only the last Attachments is visible
  After adding lots of Attachments, the window is the right size, but only the last Attachments is visible.
  `<previous-entry>`, `<next-entry>` fixes the view.

- Page Up / Down need a minimum of 1 row!
  If there are **lots** of Attachments, the Preview Window becomes small.
  Page Up / Down stop working.
  They should probably move `(Page Size - 1)` rows (giving a 1 line overlap)

## Testing

Test behaviour of:

- Plain text
- Unicode text
- Embedded ANSI escape sequences
- ^H overtype sequences
- Emojis
- Text wrapping
- URLs

**Comment by roccoblues** [comment]
> I've had a play with @roccoblues' PR and had a think. As always, I've gone too far :-) Some of my ideas are relevant, some more tangential!

Thanks for the detailed feedback!


> I think it should be enabled by default.

agree
 

> Do we want to support any Pager config?
> 
>     * `$allow_ansi` -- Allow ANSI color codes in rich text messages
>     * `$markers` -- Display a '+' at the beginning of wrapped lines in the pager
>     * `$pager_context` -- Number of lines of overlap when changing pages in the pager
>     * `$smart_wrap` -- Wrap text at word boundaries
>     * `$tilde` -- Display '~' in the pager after the end of the email
>     * `$wrap` -- Width to wrap text in the pager

If possible I'd like to start basic. I don't think the preview window needs to be a full pager. It's purpose is to give you a quick preview/reminder of what you're about to send. It's not the default way to view a message. We can always iterate and even use the preview window as a Pager 2.0 testing ground.

Only the wrapping is something I'm wondering about. Currently the lines just get clipped at the end which isn't very nice. But on the other hand also not the end of the world.


> Whatever the size of Terminal, however many Attachments they have, the default layout of Envelope, Preview and Attachments should be pleasing.

agree


> `"$compose_preview_min_rows"`
> If the Terminal is very short, perhaps we could hide the Preview

I like this.


> Make Page-Up/Down act on the entire Dialog.

I really don't like this. 😄 It would be a completely new UX for Neomutt. Just for the Compose View.
 

> If the Preview displays a long email, it would be good to show some feedback on the position, e.g. "15%"

agree

> We could add this to the Compose Bar, but it's a bit far away from the Preview. It might be better to upgrade the "Attachments" Simple Bar to a formatted Bar. e.g. `|3 Attachments 25%|`

sounds good, although it makes the code more complicated because we need to share more state between the windows.

> Create a Scrollbar Window. This would be 1 character wide Window placed to the right of the Preview (or the Pager, etc). This would be a simple, passive, Window listening to Notifications from the Preview.

That'd be nice! Maybe I'll have a play with it.


> Here's a list of all the Functions we _could_ implement. This would allow the user independent control of the Preview.

yeah, I think adding dedicated functions to make the keybindings configurable is good. For example my Macbook doesn't have dedicated `PAGEUP`/`PAGEDOWN`, I'd probably just `CTRL-K`/`CTRL-J`. However before we go crazy with things like search - this is just a message preview. How often do we expect users to interact with it? I think 99% of the time you'll just hit "send".


> NeoMutt supports an idea of a 'focussed' Window.

I also though of that and in principle I'd really like it. E.g. hit `TAB` to cycle through envelope, preview, attachments and use the same keybindings for interaction.
But it's again a new UX for Neomutt. We don't have that anywhere else I think.


> the Preview Window needs a colour observer.

ack


> One way to save some space, would be to eliminate the Preview Bar and instead colour the Preview, and/or the entire Envelope region. A subtle difference in background colour would be enough to make it stand out.

Interesting idea, I'll have a play with it.


>     * Attachments take up one more row than they need
>       (There's always a blank line)

That was actually on purpose because I didn't like how it looked without the empty line. Easy to fix.

>     * Only the last Attachments is visible
>       After adding lots of Attachments, the window is the right size, but only the last Attachments is visible.
>       `<previous-entry>`, `<next-entry>` fixes the view.

thanks, noted

>     * Page Up / Down need a minimum of 1 row!
>       If there are **lots** of Attachments, the Preview Window becomes small.
>       Page Up / Down stop working.
>       They should probably move `(Page Size - 1)` rows (giving a 1 line overlap)

thanks, noted

**Comment by roccoblues** [comment]
Now, to not get lost in coding the perfect solution. I'd be nice to come up with a minimal list of features still missing before we release this. I'll go first: 😏 

* all bugs fixed (ok, that is a given but I still wanted to note it down)
* configurable keybindings: page and line scrolling
* hide preview if there isn't enough space
* some indication that a long email can be scrolled down
* basic text wrapping (now sure about this one)

@flatcap , @gahr, @edi9999 thoughts?

**Comment by flatcap** [comment]
That sounds good.
The basic operation will add value for most users.

> not get lost in coding the perfect solution

hehe, sorry for the information overload :-)

> some indication that a long email can be scrolled down
> although it makes the code more complicated because we need to share more state between the windows.

true, but you've already added `win_preview` to `ComposeSharedData`, so the info is already available.
Adding `%p` to the end of `$compose` would be _ok_.

tbh, we could live without the %age for v1.0.
The user has **just** written the email; they probably remember the contents :-)

> basic text wrapping

A simple way would be to use `mutt_wstr_trunc()`.
You give it a maximum number of screen **columns** and it tells you how many **bytes** of characters will fit.
Note: wrapping text may affect your Page-Up/Down calculations.

---

There's no rush for the next release, but I reckon we should merge early.
Asking our dev-ml to try out devel branches is a waste of time.
Let's force it on them and see what they don't like :-)

**Comment by flatcap** [comment]
> > Create a Scrollbar Window.

> That'd be nice! Maybe I'll have a play with it.

Feel free to open a discussion.
[Some rough ideas and diagrams](https://raw.githubusercontent.com/neomutt/flatcap-brain-dump/refs/heads/main/paging/paging.txt)

**Comment by edi9999** [comment]
> * all bugs fixed (ok, that is a given but I still wanted to note it down)
> * configurable keybindings: page and line scrolling
> * hide preview if there isn't enough space
> * some indication that a long email can be scrolled down
> * basic text wrapping (not sure about this one)

Looks good to me !

It makes sense that this lands without an option as most users probably want this feature.

**Comment by edi9999** [comment]
I've just tested this locally and it works well for my usecase as well.

One thing that was a bit difficult at first is that there is no space (no empty line) between the header "Preview" and the start of the message "Hello Jack".

At some point, I tried to add an attachment (jpg image), and then hitting Ctrl-J would no more scroll to the bottom, but instead would open the image itself.

I don't know if it is possible to bind another keybinding by default that would work even if the "cursor" is inside the "attachment list" box.
