### ISSUE TITLE
Memory corruption after using getaddrinfo_a()

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#453]
This is the result of a **lot** of testing over two days. (I have run neomutt over 100,000 times.)

I found that the problem:

- corrupts several global strings (maybe not at the same time)
  - Tempdir (`$tmpdir`)
  - SmtpUrl (`$smtp_url`)
- affects strings that we have malloc'd
  - writes 0xFFFFFFFE (4 bytes) over the beginning
  - only seems to affect the start of strings
- is intermittent
- is caused by the hostname lookup
  - dependent on `getaddrinfo_a()`
  - only the async version
- is strongly influenced by timing
- is probably the cause of #438 (Fedora builds broken).
- seems to be IMAP-dependent

I started investigating #438 in a minimal VM and managed to repeat the problem occasionally (a few percent of the runs).  I started running running `mutt -e 'exec exit'` in blocks of 1000 to make the problem reoccur.

The OP reported that running `mutt -d2` "fixed" the problem.  I found that the problem still occurred, but less frequently.  Then the problem stopped happening.  For the rest of the night, I couldn't make it happen.

Next day, it started happening again.  Same setup.  Whatever was causing the problem was in the latest code and strongly timing-dependent.  I narrowed it down to `getaddrinfo_a()`.

The problem can be "fixed", by:

- getting `getdnsdomainname()` to return immediately (without doing anything)
- disabling the use of `getaddrinfo_a()`
- changing `GAI_NOWAIT` to `GAI_WAIT`
- adding `127.0.0.1 myhost.example.com` to `/etc/hosts`
  (so that the hostname lookup is instantaneous)

I tried altering the `timeout` variable (making it much smaller or larger), but I didn't manage to get any reliable results.

By adding a lot of `printf()` debugging, I managed to find one place where `Tempdir` was being corrupted.  In `tls_negotiate()` the call to `gnutls_handshake()` caused the corruption.

I *think* that the problem may be caused by someone else doing a `getaddrinfo()` lookup, but I can't imagine how that would cause random string corruption.

/cc @sileht

**Comment by sileht** [comment]
Thanks for all the investigations,

On Sun, Mar 05, 2017 at 05:52:39AM -0800, Richard Russon wrote:
>This is the result of a **lot** of testing over two days. (I have run neomutt over 100,000 times.)
>
>The problem can be "fixed", by:
>
>- changing `GAI_NOWAIT` to `GAI_WAIT`

This make the call of gai_suspend useless, because get_addrinfo_a() don't
return until the dns resolution is finish, making the original bug we
try to fix not fixed.

I have looked at the code again, and how get_addrinfo_a() work I think I
got the thing.

We call gai_suspend with a timeout, and if we don't get the answer on
time. we FREE(&reqs[0]). But the reqs are still registered from the glibc
point of view, because we don't call gai_cancel when gai_error() return
EAI_INPROGRESS.

Then when the dns request finish and corrupt memory we thought
freed, because glibc write the answer at &reqs[0].

I will propose a fix to call gai_cancel(), when it's needed.

-- 
Mehdi Abaakouk
mail: sileht@sileht.net
irc: sileht
