### ISSUE TITLE
Stop asking for "Exit Mutt?"

### ISSUE THREAD

**Issue by tdehaeze** [neomutt/neomutt#468]
Hello,

I would like to know if there is a way to setup a default behaviour when I use `Ctrl-C` ? It always ask me 'Exit Mutt ? ([yes], no)' and it's quite annoying...

For `q` and `x` I used `set quit` in my conf file. But I couldn't find it for `Ctrl-C`.

Thanks

**Comment by flatcap** [comment]
Of all the keystrokes, <kbd>Ctrl-C</kbd> **is** handled differently.
It generates a signal which we can use to interrupt lengthy processes.

A simple change we _could_ make is to follow Vim's behaviour - don't quit, but tell the user how to quit:
`Type  :quit<Enter>  to exit Vim`
`Press 'q' to exit NeoMutt`

The 'q' would have to be looked up in the user's keybindings, of course.

**Comment by guyzmo** [comment]
I agree and vote for that change of behaviour. I have so many times quit mutt with harm by mistake.

Actually, another good idea would be to have a third smart choice for <kbd>x</kbd>/<kbd>q</kbd>: when the index is dirty (e.g. there are mails marked as to be deleted, but actually are not), ask `Index not synced, are you sure you want to quit?` otherwise just quit.

**Comment by flatcap** [comment]
One other thought...

If mutt can't find a mapping to exit, then <kbd>Ctrl-C</kbd> should ask "Exit Mutt?"
Otherwise these mappings would make it rather hard to leave mutt:
```
bind index q noop
bind index x noop
bind index : noop
```

**Comment by flatcap** [comment]
Sorry, this enhancement didn't attract someone to write some code.
This issue will now be closed, but listed on the [Closed Discussions](https://www.neomutt.org/dev/discussions) page.

**Comment by tdehaeze** [comment]
I just realized that I can use `C-g` instead of `C-c` and it does not ask "Exit Mutt"!
So, problem solved.
