### ISSUE TITLE
IMAP fails to authenticate

### ISSUE THREAD

**Issue by gahr** [neomutt/neomutt#479]
Please investigate the problem reported here:
http://mailman.neomutt.org/pipermail/neomutt-users-neomutt.org/2017-March/000099.html

**Comment by gahr** [comment]
Useful info:

- password is 24 characters long
- password contains "a lot of special character like /{}[]#"
- a simpler password has been reported to work
- auth method is SASL PLAIN

**Comment by guyzmo** [comment]
for the sake of testing, in https://github.com/neomutt/neomutt/pull/408#discussion_r101645082 @EdwardBetts wrote an Imap mockup, so it should help in testing issues with some special password characters mishandled.

**Comment by guyzmo** [comment]
following up a discussion on the channel where an user `andi-` has reported a similar issue than the OP:

```
<andi-> I just changed one of my smtp passwords that I source via set stmp_pass = `pass show ...`. The new password contains a ` and mutt tries to execute/interpret the text within the password /o\ Is there a workaround for that besides avoiding backticks in my random pw gen?
```

it makes me wonder whether it's not an IMAP related issue, but rather a shell substitution issue. I just ran a test which goes as follows:

```bash
% cat > fubar.sh << EOF
echo '`touch /tmp/fubar`'
EOF
% chmod +x fubar.sh
% cat > muttrc << EOF
set my_var=`./fubar.sh`
EOF
% ls -l /tmp/fubar
ls: cannot access '/tmp/fubar': No such file or directory
% mutt -F muttrc -B
% ls -l /tmp/fubar
-rw------- 1 guyzmo guyzmo 0 Mar 20 14:38 /tmp/fubar
```

what that shows is that stdout of the commands within muttrc's backticks are being passed to the shell as stdin, instead of being directly taken by mutt. That would mean side effects of all sorts (think of using `;` or `!` in your password…

**Comment by gahr** [comment]
Oh, so the problem is not with IMAP password, but with backtick expansion. This is *not* a bug, but a documented feature. Please use single quotes to avoid such expansion.
