### ISSUE TITLE
mutt resets certain terminal colors if ~/.muttrc is present

### ISSUE THREAD

**Issue by BonarBeavis** [neomutt/neomutt#518]
This is copied from [Bug 1366867 – mutt resets certain terminal colors if ~/.muttrc is present](https://bugzilla.redhat.com/show_bug.cgi?id=1366867)

Description of problem:
I use a base16 colorscheme[0] which defines custom colors for positions 16 through 21 in the 256 color palette.  When running mutt with the ~/.muttrc file existing (i.e. pretty much always), these colors are reset to their default values -- shades of blue.  Strangely this doesn't happen if the rc file doesn't exist.

This means that these colors appear very different in both mutt itself and the text editor when composing messages, which is fairly annoying.

Version-Release number of selected component (if applicable):
mutt-1.6.2-1.fc24.x86_64
xterm-323-1.fc24.x86_64

How reproducible:
Always.

Steps to Reproduce:
I'll use the base16 scripts here:

0. Run the following in xterm.
1. Make sure ~/.muttrc exists. (can be empty)
2. $ git clone https://github.com/chriskempson/base16-shell.git
3. $ sh base16-shell/scripts/base16-eighties.sh
4. $ sh base16-shell/colortest
5. Note that color16-color21 are NOT blue.
6. $ mutt
7. Exit mutt.
8. Repeat step 4.  Note the colors are blue now.
9. (Re)move your ~/.muttrc file and repeat steps 3, 4, 5, 6 and 7.  The
   colors should stay unchanged.

Actual results:
My terminal palette gets messed up every time I run mutt.

Expected results:
My terminal palette stays unchanged.

Additional info:
I also tried this in st and urxvt and neither of those suffered from this bug.  I guess it's caused by some escape sequence mutt prints that only xterm understands.  I also have a Gentoo system here and running its
mail-client/mutt-1.6.2 in Fedora's xterm doesn't change my palette.

[0] https://github.com/chriskempson/base16-shell

**Comment by flatcap** [comment]
Wow, that's great bug.  It also happens in Gnome Terminal and Tilix (both libvte-based).

When setting up its colours, mutt overwrites the existing palette colours.
Then, when `refresh()` is called, ncurses emits `^[]104^G` resetting the terminal's palette.

The bug is present in: mutt-1.5.23, mutt-1.5.24, mutt-1.6.0, mutt-1.6.1, mutt-1.6.2, mutt-1.7.0, mutt-1.7.1, mutt-1.7.2, mutt-1.8.0, mutt-1.8.1 -- and hence all of the neomutt versions.  As far as I can tell mutt has always behaved this way.

Clearly this is fixable -- plenty of curses programs respect the palette.
Unfortunately, the colour handling in mutt is pretty complex and it would be an immense job.

If anyone wants to take on this task, I'll happily mentor them, but I'm not going to do it.  Sorry.

**Comment by nobrowser** [comment]
I would have never caught this bug because I always run mutt in a dedicated terminal.

I may consider adopting this - need to look at existing code first.

**Comment by flatcap** [comment]
I'm closing this as "unfixable", for now.
Some day in the distant future, we'll rewrite the colour code and this will be fixed.

**Comment by ibutra** [comment]
Does there at least exist a workaround for this?

**Comment by AvianY** [comment]
I am using pywal to generate coloors and this changes everything... really annoying. The workaround by jacklenox works for now.

**Comment by balachia** [comment]
Another workaround (that seems to work for me in 10 minutes of testing in fish) is to set TERM to something other than xterm, e.g. screen-256color. This avoids the 'overhead' of tmux.

`TERM=screen-256color neomutt` preserves terminal colors for me.

**Comment by deepPhong** [comment]
I've just added an alias in my .zshrc (add it to your .bashrc if you're using bash) file with the following line, based on the above workaround : 
`alias neomutt="TERM=screen-256color neomutt"`
