### ISSUE TITLE
autoreconf -fi fails on versions newer than 20170306

### ISSUE THREAD

**Issue by Vaelatern** [neomutt/neomutt#546]
This issue also came out on test builds of the development version, but it seems to have made it through to the final release.

When runnign `autoreconf -fi` the following is output:
```
/usr/bin/autopoint: line 485: /usr/share/gettext/archive.dir.tar.xz: No such file or directory
tar: This does not look like a tar archive
tar: gettext-0.17: Not found in archive
tar: Exiting with failure status due to previous errors
autopoint: *** infrastructure files for version 0.17 not found; this is autopoint from GNU gettext-tools 0.19.8.1
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```

I'm probably just missing something obvious here, but would welcome assistance.

**Comment by gahr** [comment]
I conjecture stale files. Could you please run a `git clean -Xf` before `./prepare` and see whether it fixes things?

**Comment by flatcap** [comment]
> This issue also came out on test builds of the development version,

Please tell us in future.

> `autoreconf -fi`

I don't think it'll make a difference, but I don't think you need '-f' (force)

> /usr/bin/autopoint: line 485: /usr/share/gettext/archive.dir.tar.xz: No such file or directory

`archive.dir.tar.xz` (autopoint looks for .gz and .bz2 also) contains a set of m4 files for each version of gettext.  In Fedora this file is in package 'gettext-common-devel'.

Since the last release, these files are no longer distributed and are now taken from the build environment.

**Comment by Vaelatern** [comment]
This now works better. I installed `gettext-devel` and now can build the package.

My apologies for not warning you of the build failure in the development release.
