### ISSUE TITLE
need help setting up auto_view

### ISSUE THREAD

**Issue by 0-wiz-0** [neomutt/neomutt#555]
When switching from neomutt-201703* to 20170421, I noticed that attachments of the type
````
Type: text/x-diff; charset=us-ascii, Encoding: binary
````
are not viewed automatically any longer.
I would like that back. how can I configure neomutt to do that?
I've added `text/x-diff` to `auto_view` and `.mailcap`, but that's not sufficient.

From `.mailcap`
````
text/x-diff;                    less
````

From `.muttrc`:
````
auto_view text/x-diff text/html
````

**Comment by 0-wiz-0** [comment]
To perhaps make it clearer: in the March version, they were shown inline, just below the text of the email; now I have to press v+cursor-down+enter to see them and q+q to go back, so 5 key presses more than before.

**Comment by sileht** [comment]
I think this is due to https://github.com/neomutt/neomutt/pull/449.

We remove all assumption that all text/* are human readable. Now neomutt needs a mailcap entry with
'copiousoutput' option.

You can put in your mailcap: `text/x-diff ;cat "%s"; copiousoutput` to make it works.
   
Personally I don't have such entry by default for text/x-diff in the system mailcap (debian strech).

**Comment by 0-wiz-0** [comment]
A slightly different syntax of what you proposed works for me:
````
text/x-diff;                    cat %s; copiousoutput
````
This should be documented, then this issue can be closed from my PoV.
Thanks for the help!

**Comment by somini** [comment]
You can use wildcards too.

With a mailcap:
```
text/*; cat; copiousoutput
```
You will restore the old assumption that "text/*" are human-readable.
