### ISSUE TITLE
signing of release tarballs

### ISSUE THREAD

**Issue by EmilePouget** [neomutt/neomutt#563]
Would it be possible for the release handling person (flatcap?) to create an release signing GPG/PGP key, so that future releases of neomutt can be signed?
Sometimes you include hashsums, sometimes you don't, and for me as a packager it's good to check wether the digital signature matches what I have just downloaded. I would notice mismatches later through systems provided by Guix, but yes:
signed releases would be good.

**Comment by flatcap** [comment]
For the most part this is already done (though poorly documented).
Missing checksum files are due to human error during the release process.

The NeoMutt signing key exists and I've signed every **release** commit in git.
The public key is attached to my GitHub account which means that [all the releases](https://github.com/neomutt/neomutt/releases) are accompanied by a "Verified" marker.

The NeoMutt signing key is: 
- `86C2397270DD7A561263CA4E5FAF0A6EE7371805`
- Richard Russon (NeoMutt) <rich@flatcap.org>

It's signed by my key, which is in the strong set:
- `69AD1D636AC292E820658C16EBC150E4B5DA63DF`
- Richard Russon (flatcap) <rich@flatcap.org>

Both keys are available on keyservers, or insecurely [from our website](https://www.neomutt.org/person/flatcap).

My key can be downloaded securely using [DANE](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities) ([instructions](https://flatcap.org/id/))

Finally, I've just been through all the releases and made sure they also have a SHA256 CHECKSUM file.  I'll try not to forget in future.  These files are of the form:
- neomutt-YYYYMMDD-CHECKSUM
- mutt-X.Y.Z-CHECKSUM

**Comment by EmilePouget** [comment]
Thanks!

Okay I wasn't aware of this feature of Github, I was looking for detached signature files.

**Comment by flatcap** [comment]
I've created a [page about signing](https://www.neomutt.org/dev/signing)
