### ISSUE TITLE
Translation shown in PGP menu but have to use from the plain version

### ISSUE THREAD

**Issue by riesebie** [neomutt/neomutt#593]
Have build dd499e12 for testing. If I want to encrypt a message I
get the translated menu according to my locales de_DE-utf8. 
But I have to use the letters from the plain version, i.e (c)lear 
instead of (u)nverschl. Don't know where to look in the code.

**Comment by flatcap** [comment]
The strings start in the code in English:
- [ncrypt/crypt_gpgme.c](https://github.com/neomutt/neomutt/blob/master/ncrypt/crypt_gpgme.c#L4580)
- [ncrypt/pgp.c](https://github.com/neomutt/neomutt/blob/master/ncrypt/pgp.c#L1651)
- [ncrypt/smime.c](https://github.com/neomutt/neomutt/blob/master/ncrypt/smime.c#L1984)

The translations are maintained in `po/*.po`, e.g. [`po/de.po`](https://github.com/neomutt/neomutt/blob/master/po/de.po#L4774)
These files are compiled into `*.gmo` files which are distributed with the build.

At runtime, neomutt tries to lookup translations depending on your locale settings.

The crypto settings are slightly complicated because for each question string, there is a translated answer string:
- "S/MIME (s)ign, sign (a)s, (p)gp, (c)lear, or (o)ppenc mode off? "
- "sapfco"

To work correctly, they both need to be translated.

To update the translations, you can [follow the old instructions](https://www.neomutt.org/dev/translate-strings), or try out our [POEditor account](https://poeditor.com/projects/view?id=96369).

The translations get merged into master just before a new release.

**Comment by flatcap** [comment]
Fixed by: 9ceb846
