### ISSUE TITLE
Deprecate muttrc synonyms?

### ISSUE THREAD

**Issue by flatcap** [neomutt/neomutt#596]
There are 24 synonyms (alternate names) for muttrc config.
None of them have been documented in the last 10 years.

Many of them were created as synonyms and never existed as real options.

**Should we**:
- **Leave them** (in case they're still being used)
- **Warn the user** for an X-month period
- **Delete them** immediately

**Synonyms since the initial revision (19 years ago)**:
- **edit_hdrs** (edit_headers)
- **forw_decode** (forward_decode)
- **forw_decrypt** (forward_decrypt)
- **forw_format** (forward_format)
- **forw_quote** (forward_quote)
- **hdr_format** (index_format)
- **indent_str** (indent_string)
- **mime_fwd** (mime_forward)
- **msg_format** (message_format)
- **post_indent_str** (post_indent_string)
- **print_cmd** (print_command)

**Created 1999, then became synonyms in 2002-2005**:
- **envelope_from** (use_envelope_from)
- **pgp_autoencrypt** (crypt_autoencrypt)
- **pgp_autosign** (crypt_autosign)
- **pgp_auto_traditional** (pgp_replyinline)
- **pgp_create_traditional** (pgp_autoinline)
- **pgp_replyencrypt** (crypt_replyencrypt)
- **pgp_replysign** (crypt_replysign)
- **pgp_replysignencrypted** (crypt_replysignencrypted)
- **pgp_verify_sig** (crypt_verify_sig)
- **smime_sign_as** (smime_default_key)

**Only existed as synonyms since their creation 4 years ago**:
- **xterm_icon** (ts_icon_format)
- **xterm_set_titles** (ts_enabled)
- **xterm_title** (ts_status_format)

**Comment by somini** [comment]
Most of those look like borderline leftover debug code. I say nuke 'em, over 10 years of undocumented behaviour seems safe enough.

**Comment by guiniol** [comment]
I'd be for warning users for a few releases. I think I've seen a few of the `pgp_*` in dotfiles

**Comment by Hasimir** [comment]
The pgp_* ones definitely need to stay or otherwise have a *very* long warning period.  There will definitely be a lot of people with those settings in their muttrc files as standard.

My recent-ish (relatively speaking) return to mutt still meant ressurrecting and then modifying my old muttrc files from years ago and those files are *filled* with these references.  A quick look revealed this:

	bash-4.4$ egrep "^set pgp" ~/.muttrc | wc -l
		   6
	bash-4.4$ egrep "^#set pgp" ~/.muttrc | wc -l
		   2
	bash-4.4$ egrep "^# set pgp" ~/.muttrc | wc -l
		   0
	bash-4.4$ egrep "^set pgp" -r ~/.mutt/ | wc -l
		 114
	bash-4.4$ egrep "^#set pgp" -r ~/.mutt/ | wc -l
		  19
	bash-4.4$ egrep "^# set pgp" -r ~/.mutt/ | wc -l
		  36
	bash-4.4$ 

That includes some archives and a bunch of alternative configurations, but I know I'm not the only one.  There'll be plenty of others floating around, including pretty much anyone who remembers the first Crypto Wars.

Now sure, I can fix mine since I've seen this, but there will be *plenty* of others who won't know until suddenly their crypto stops working.

**Comment by Hasimir** [comment]
Also, there are a lot more pgp_* options than there are crypt_ options.  If these few are deprecated and then people just change all the pgp references to crypt, it'll still break things badly.  So unless all those other pgp_* options are being reimplemented or updated as crypt_*, I suspect that this bit at least will create more problems than it solves.

Oh, BTW, yes I do have config in my muttrc files which use pgp_* settings that are not available as crypt_* at all.

**Comment by flatcap** [comment]
Thanks for your input @Hasimir, but nothing's going away.

The **8 pgp names** (listed in my first post) are **linked to crypt options** (the real documented options).
The **pgp names**, which I plan to remove, have **never been documented** by mutt.

The remaining 33 pgp options aren't being touched.

**Comment by Hasimir** [comment]
Good to know, but don't be so sure about them never being documented.  At least a couple of them have been documented somewhere by May, 2005.  Specifically `pgp_verify_sig` and `pgp_autosign` (via a reference to `nopgp_autosign`) since I've got them in old muttrc files from back then.

That config even precedes my shift to GPG, so most of it deals with calling pgp6.rc.  The last config file from the time is from 2007, but the PGP sections hadn't changed and that's about when a job change took me to an employer with Thunderbird as the standard MUA and it was just easier to use that for everything.

With this return to the fold I unearthed config and docs from somewhere enough to set this:

	# set pgp_strict_enc            # use Q-P encoding when needed for PGP
	set pgp_replyencrypt=yes        # Encrypt when replying to encrypted messages.
	set pgp_replysignencrypted=yes  # Sign when replying to encrypted messages.
	set pgp_show_unusable="no"      # Don't display unusable keys.
	set pgp_sort_keys="keyid"       # Sort keys by key ID
	set pgp_replysign=yes           # Sign when replying to signed messages.
	# set pgp_timeout=7200          # Forget the PGP passphrase after an hour.
	set pgp_verify_sig=yes          # don't automatically verify message signatures

Of which these "undocumented" ones managed to materialise:

	set pgp_replyencrypt=yes        # Encrypt when replying to encrypted messages.
	set pgp_replysignencrypted=yes  # Sign when replying to encrypted messages.
	set pgp_replysign=yes           # Sign when replying to signed messages.
	set pgp_verify_sig=yes          # don't automatically verify message signatures

I certainly wasn't trawling through the source code looking for obscure settings just for the sake of it.  Plus if I found them then others will have too.

Anyway that's five of the eight undocumented settings documented enough to appear in a configuration that was setup at the beginning of last year.  Statistically that doesn't look so promising for the last three either, but I can neither confirm nor deny the use of them.

**Comment by nobrowser** [comment]
FWIW, I used the xterm_ ones until a couple of weeks ago.  I used to show unread message count and unread mailbox count in the title, but then I decided to stop any such dynamic manipulation of titles, out of paranoia brought on by [this thread](http://openwall.com/lists/oss-security/2017/05/01/13).  So, luckily now there is one fewer user of the obsolete variables :-)

**Comment by flatcap** [comment]
Thanks everyone.
So the simple solution is for me to "correct" the internet, then remove the options ;-)

Three steps, it is then:
- Notification
- Warning
- Removal

I'll send out a notification a couple of weeks before a stable release.

Currently, we're producing about 1 stable release per month.
Are 3 months / 3 releases worth of warnings, enough?

**Comment by Hasimir** [comment]
On Sun, Jun 04, 2017 at 05:35:40AM -0700, Richard Russon wrote:
> Thanks everyone.
>
> So the simple solution is for me to "correct" the internet,

Heheh, good luck with *that*.

> then remove the options ;-)

I've done a little more poking around and I believe I know where all
of the more recent additions of those aliases have entered the
picture:

	$PREFIX/share/doc/mutt/samples/sample.muttrc
	$PREFIX/share/doc/mutt/samples/sample.muttrc-tlr

The first is an old copy of Michael Elkins' muttrc and the second is a
copy of Thomas Roessler's muttrc.  Which explains why undocumented
aliases would still surface and spread since otherwise those samples
are very detailed and certainly good for getting a lot of decent
settings in place quickly.

> Three steps, it is then:
> - Notification
> - Warning
> - Removal

Given those muttrc samples have been distributed with every release of
Mutt as well as Neomutt and it is going to collect people shifting
from the original project to this one, this might be one of the few
times where proposing a change to the samples be sent back upstream
before the change is made.  Otherwise every time someone switching
from mutt to neomutt after the change who has cripped from those
samples is going to get caught out.

> I'll send out a notification a couple of weeks before a stable release.
> 
> Currently, we're producing about 1 stable release per month.
> Are 3 months / 3 releases worth of warnings, enough?

Er ... no comment ...

**Comment by nobrowser** [comment]
@Hasimir  : My 2+ years in mutt-users tells me this change would never be accepted upstream.

Nonetheless, I think the change should be made in neomutt, and I agree with @flatcap proposed deprecation schedule.

**Comment by toogley** [comment]
@kevin8t8 @xdgc what are your opinions about this issue and the proposed solution by @flatcap?

**Comment by Hasimir** [comment]
On Mon, Jun 05, 2017 at 04:39:04PM -0700, Ian Zimmerman wrote:
>
> @Hasimir : My 2+ years in mutt-users tells me this change would
> never be accepted upstream.

Well, that's going to be ... special.

> Nonetheless, I think the change should be made in neomutt, and I
> agree with @flatcap proposed deprecation schedule.

Better make sure you've all got a default response template ready for
the inevitably unending "I just switched to Neomutt and now foo
doesn't work."

It'll be like the original Terminator movie: "it absolutely will not
stop until you are dead."

Still, if you're ready for that, go for it.

**Comment by toogley** [comment]
I think the critique of @Hasimir is very serious. I also think we should make a document somewhere describing the differences of neomutt and mutt. I doubt we can get around introducing incompatiblities to mutt, and when that happens (or maybe it has already happen?) we need to make sure the users know about that.

**Comment by flatcap** [comment]
@toogley 
> differences of neomutt and mutt

I'm starting to put together a doc for this.

**Comment by flatcap** [comment]
A complete diff between Mutt and NeoMutt: https://www.neomutt.org/changes/
