### ISSUE TITLE
notmuch: listing all unread tags

### ISSUE THREAD

**Issue by anarcat** [neomutt/neomutt#628]
one key feature of notmuch-emacs is the welcome screen, which seems to be missing from mutt-kz. i use it a lot to deal with massive amounts of mails... it looks like this right now here:

![emacs welcome screen](https://cloud.githubusercontent.com/assets/796623/14258375/3dca249a-fa70-11e5-9b6f-698d7b70ab9d.png)

i know i can set the equivalent of "saved searches" through the virtual-mailboxes command. however, i'd like to see the equivalent of the rest of the notmuch-hello page, which list all tags that have unread messages with the number of messages next to the tag.

i would have expected the `y` key to lead to that, for example.

any tips on how to do this?

i was wondering if the `change-folder` command could be patched for that, or if some auto-completion scheme could be abused here... for example, maybe the `vfolder-from-query` command could behave similarly to `change-folder` and allow using `?` in macros to autocomplete. for example, i have this shortcut here that was very useful before i started using notmuch:

```
y                            M <change-folder>?<toggle-mailboxes>     show incoming mailboxes list
```

it would show me all folders i needed to look at...

i found something similar posted on the mutt-kz mailing list here:

https://lists.fedoraproject.org/pipermail/mutt-kz/2013-May/000167.html

could it be the start of something that would do something here? :)

(Note: this is a copy of https://github.com/karelzak/mutt-kz/issues/104, reported against the original mutt-kz)

**Comment by toogley** [comment]
> which list all tags that have unread messages with the number of messages next to the tag.

I don't know what you mean with "the numbers of messages next to the tag", because the above screen does only show one number (the unread tag, i guess)

I'm not sure, but i guess you could define a virtual mailbox for each tag. Then, the sidebar should show you for each tag the unread messages. (well that depends on your configuration)

**Comment by anarcat** [comment]
i do mean the number of unread messages.

i know i could hardcode a list of virtual mailboxes for every tag that exists, but tags are volatile in nature: they come in and out of existence dynamically. i don't want to have to regenerate my mutt config every time i add a tag! also, the emacs screen doesn't show the tags that have no unread messages, which the sidebar doesn't do either.

**Comment by guyzmo** [comment]
The mailbox list screen is not the right fit for that, because it's based on the mechanism of listing existing mailboxes, so it would defeat the purpose of that feature.

I understand and agree it's not a "sidebar" usecase. It shall be a proper and independant "screen". But I don't think it should be added as a new patch in neomutt.

- You could maybe write a script that you bind to a macro (maybe based on fzf) that will do such listing, and return the mailbox to open?
- Or maybe, could we explore what kind of new lua API we could build to create a custom screen that will expose what you're suggesting?

**Comment by flatcap** [comment]
A reasonable alternative is to create a summary page (see #162)

- What do you want to see on the page?
- What NotMuch commands are necessary?
- Are they expensive (time-consuming)?
- Do you want the information to be user-configurable?

And the final question:

- Are you going to do the work?

We have lots of great ideas... but few coders.
But we'll be happy to mentor volunteers.

**Comment by flatcap** [comment]
Moving this to the long-term wish list.
