### ISSUE TITLE
Switch default for tmpdir to /var/tmp

### ISSUE THREAD

**Issue by aradici** [neomutt/neomutt#657]
This bug has a long-running issue in Debian and I've decided to patch it starting from the next release because it makes sense to have the tmpdir set to /var/tmp as per FHS. The main reason for it is that the computer/laptop can reboot while you are writing a mail and if you are using /tmp as default storage then you will lose the mail

Full context on http://bugs.debian.org/530584
There are also the required patches to make it happen

This was also reported upstream 8 years ago and met with resistance (http://bugs.mutt.org/3236)

**Comment by flatcap** [comment]
On many modern systems `/tmp` is tmpfs, so I agree that `/var/tmp` is a better choice for partial emails.
I'll put it to a quick vote amongst the reviewers.

**Comment by somini** [comment]
I think a better location is the user cache, since partial emails are user-specific.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
So `$XDG_CACHE_HOME/mutt/messages`, falling back to `~/.cache/mutt/messages/`.
I set this in my muttrc, but we should make sure to `mkdir -p $XDG_CACHE_HOME/mutt/messages` first.

There's preliminary support for the XDG spec, to load the muttrc file.
https://github.com/neomutt/neomutt/blob/eebf72008a790dc3214d89beeea4daf815c2b5bc/muttlib.c#L74

**Comment by flatcap** [comment]
Ah.  I nearly mentioned `$XDG_CACHE_HOME`

@mkoskar and I were discussing (on IRC) the `source` command being relative and which other variables should be relative to the user's `muttrc`.  If we find `muttrc` in an XDG dir we should probably consider changing quite a few defaults.  Discussion needed.

**Comment by mkoskar** [comment]
Since @flatcap draw my attention here, I have few points.

1) @aradici ``tmpdir`` is most likely used for some other sorts of things not only as compose location so I'm not sure just setting it outside of ``/tmp`` is a good idea; actually it's discussed towards the end of original bugreport suggesting separate configuration value

2) @somini I guess according to XDG it would be ``.local/share/mutt/...`` better no? At least I understand ``.cache`` as something that is purely transient e.g., header cache

3) @flatcap RE: our discussion, I've realized I can do smt. like ``source $MUTT_HOME/file`` having set it outside of mutt (``setenv`` wouldn't cut it), or just regular ``set my_var``

**Comment by somini** [comment]
@mkoskar I never though about system failure while I was writing email, when I leave mails halfway i just postpone them and mutt moves them to the `drafts` directory. I think cache is fine, but `$XDG_SHARE_DIR` is not incorrect either.
I vote for another mutt option `compose_dir` or something.

`tmpdir` is used for tons of temporary files, some having to do with messages, some with internal mutt screens. It's also used to view attachments and store copious output for attachments.

**Comment by somini** [comment]
This is where mutt creates a new email temporary file:
https://github.com/neomutt/neomutt/blob/master/send.c#L1429

`mutt_mktemp` is a macro that references other macro that calls `_mutt_mktemp`!

**Comment by d-k-c** [comment]
What are these patches doing that `set tmpdir = /var/tmp` in the system-wide config file cannot do?

As it was said before, tmpdir is used not only for messages being composed, but for many other stuff as well, so changing that default value (again, is it necessary to change the _default_ value of a variable you can override?) must be done with care.

Yes, it would be nice to save the mails being composed in permanent storage, but I don't think it's worth the trouble or the extra option for now.

**Comment by somini** [comment]
I think the point is to split all locations so that they can be placed in the correct location. Instead of stuffing everything in the temporary directory.

**Comment by flatcap** [comment]
Apologies to aradici for hijacking his issue... :-)

Notes:
1. We could do with an audit of all the files that mutt creates:
    - Partially written emails
    - Header/Message cache
    - Text displayed in pager, e.g. Help
    - Copies of attachments
1. Some files might want saving (protecting from loss), many won't
    - Many of the temporary files are created and immediately deleted which means it doesn't matter where they live
1. We don't want to add any more config (if we can possibly avoid it)
    - Some more config files should probably allow relative paths:
      `alias_file`, `certificate_file` ?
    - We should probably distinguish (in `init.h`) between:
      - Variables that must be a file
      - Variables that represent a mailbox (_could_ be a file)
    - We can probably set some defaults if the user's `muttrc` is in the XDG dir

**Comment by nobrowser** [comment]
If you change the location for emails being composed, it will break some setups, including mine.

Why? Because my editor startup code includes a rule linking the filename pattern to the editor mode I want set automatically when opening the file.

Of course, this would be trivial for me to fix by adjusting the pattern, but given how much weight we give in other issues to not breaking configs, I thought I would mention it.

**Comment by roccoblues** [comment]
Trying to cleanup some older issues here. Can anyone comment if this is still an issue in the latest version? Thanks!

**Comment by ossilator** [comment]
if no related new config setting was added (of which there is no sign here), then this very much still is a valid issue. this is something you can easily check yourself ...

**Comment by protist** [comment]
This is still an issue for me. I agree that incoming attachments and drafts should be saved in different locations. Personally I'd prefer somewhere in `/home/user` than `/var/tmp`, but at the very least the config should be split into (at least) two.
