### ISSUE TITLE
new_mail_command/terminal-notifier blocks UI

### ISSUE THREAD

**Issue by andreas-bulling** [neomutt/neomutt#659]
Hi,

I've been using neomutt in combination with terminal-notifier for a long time on OSX (homebrew) without problems. Some time ago (I, unfortunately, don't remember after which update this first occurred) it stopped working: The notification is shown but the UI is "blocked" afterwards, i.e. I can't give any input to neomutt and have to close the whole terminal.

I am using terminal-notifier v1.8.0, and neomutt stable 20170609, HEAD.

This is the configuration option:
`set new_mail_command="terminal-notifier -title '%v' -subtitle 'New Mail in %f' -message '%n new messages, %u unread.' -activate 'com.apple.Terminal'"`

**Comment by flatcap** [comment]
Hmm...  I've just tested versions: 2017-05-26, 2017-06-02, 2017-06-09 and HEAD and all of them work for me in Linux with gnome-terminal.  My new-mail script wrote the date to a file and set the terminal's title using an escape sequence.

Please can you check a few things...
- When you manually run the command in a terminal, does it return?
- What happens when you change the command to something simple?
  e.g. a script that writes the date to a file?

**Comment by ElDeveloper** [comment]
I just tried this (in NeoMutt 20170609-29-71984f, terminal-notifier
1.6.0) and it seems to be working fine for me, this is what I have set
new_mail_command to:
new_mail_command="terminal-notifier -title '%v' -subtitle 'New Mail in %f' -message '%n new messages, %u unread.' -activate 'com.googlecode.iterm2' &"

**Comment by SantiagoTorres** [comment]
Hmm, could it be due to the `&` at the end of your command?

**Comment by andreas-bulling** [comment]
@SantiagoTorres well, actually, I didn't have a `&` at the end. I now added it and notifications seems to work (again). I am pretty sure, though, that there must have been a change that broke this as it did without before. But anyway - at least it works now ;)
