### ISSUE TITLE
Impossible to delete attachments of a mail within a notmuch vfolder

### ISSUE THREAD

**Issue by guyzmo** [neomutt/neomutt#673]
* Expected behavior

I got a mail with some html as text/plain part, which is painful as it gets displayed as raw html. I then decide to delete that attachment, and the mail should end up with only one part in the alternative (or no alternative at all).

 * Actual behavior

When you delete the attachment, it gets marked as `d`, but when you hit `$` it hangs and never persists the change.

 * Steps to reproduce

1. hit `v` on a mail
2. select the attachment you want to delete
3. hit `d` on that attachment
4. get back to the index
5. hit `$` to persist the changes

**Comment by scottkosty** [comment]
@guyzmo do you know if this ever used to work?

**Comment by Austin-Ray** [comment]
I've taken another look at this issue. Tracing the issue leads to the `notmuch` backend's `mx_msg_open_new(...)` implementation or lack thereof. 

The current control flow is 
1. `mx_mbox_sync()`
2. `nm_mbox_sync()`
3. `maildir_sync_message()`
4. `mh_rewrite_message()`
5. `mx_msg_open_new()` (error code due to lack of implementation)

We have two options:
- Implement `mx_msg_open_new()` (not sure if that's possible with `notmuch`)
- Figure out some way to prevent deleting attachments (set attachments read-only?)

@flatcap Thoughts?
