### ISSUE TITLE
`change-vfolder` doesn't work anymore

### ISSUE THREAD

**Issue by guiniol** [neomutt/neomutt#683]
The first bad commit seems to be 1116748c6e52bdf8c4c0b457f4a7a26346dc3b30 "drop VirtIncoming"

# Setup
1. Define a virtual mailbox e.g. 
   `virtual-mailboxes "inbox" "notmuch://?query=tag:inbox and NOT tag:archive"`
2. Add a macro to open that virtual mailbox (not required but makes it easier) e.g.
   `macro index X '<change-vfolder>inbox<enter>'`

# Expected behaviour
The virtual inbox is opened

# Actual behaviour
Error message `inbox is not a mailbox.`

**Comment by dsdeiz** [comment]
I am experiencing this as well. One thing I noticed is that it looks like `change-vfolder` seems to like URI now instead of virtual mailboxes. An example is `macro index X '<change-vfolder>notmuch://?query=tag:inbox'`. It also doesn't seem to like spaces in the URIs e.g. `macro index X '<change-vfolder>notmuch://?query=tag:inbox and NOT tag:archive'`.

Right now my `folder-hook`s don't work.

**Comment by esovetkin** [comment]
I have created a pull request  #695  that fixes this issue

**Comment by flatcap** [comment]
Thanks for the fix @esovetkin!  Merged.
