### ISSUE TITLE
notmuch: modify-labels not work in a regular mailbox

### ISSUE THREAD

**Issue by randomizedthinking** [neomutt/neomutt#742]
* **feature requests**

    Enable `modify-labels` under regular mailboxes, rather only under virtual folders.

    * Why do you not like the current state?

        The current implementation of `modify-labels` to add notmuch tags only works under virtual-folders. It makes tagging emails almost impossible for a traditional mutt user like me. Ideally, a user should be able to add tags anywhere he/she wants.

    * What would you like to see to change?

        Add a simplified flow in `OP_MAIN_MODIFY_LABELS` to process `modify-labels` for regular mailboxes. Nothing fancy is needed... just apply tags.

        I am not familiar with mutt internals. But if someone is willing to help in terms of showing how the work should be done, I can draft some codes for this task. Regards.

**Comment by gahr** [comment]
When you mention "regular mailboxes", do you mean mbox, maildir, imap, ...?
The problem is that there is no consistent mechanism to store tags in those, and not even the concept of tagging in most (or all) of them.
Imap support flags, which is kind of application specific, mbox does not support tagging short of modifying an email's headers, maildir's support for tagging is also very vendor specific with different implementations handling tags in different ways.

**Comment by randomizedthinking** [comment]
I mean mbox, maildir, imap for regular mailboxes -- I should have used regular folder if it is clearer to you.

Here, the function `modify-labels` is a notmuch concept which is to apply some labels to a specific message.  `notmuch` designed its way to store labels information in a local xapian database for quick access, so there is no issue on how to store such information with specific mailbox implementation.

The issue is that the current implmentation of `modify-labels` is only allowed in a virtual folder. When type '`' in a regular mailbox, mutt will simply display "No virtual folder, aborting". I believe it is an implementation limitation rather than actual constraint.

**Comment by randomizedthinking** [comment]
There is a similar request to enhance `entire-thread`, but seems no one is interested to implement it: https://github.com/neomutt/neomutt/issues/105.

On the other hand, `modify-labels` is more essential.

**Comment by gahr** [comment]
Oh, it's still notmuch-backed. Sorry I didn't get that part.

**Comment by m2habert** [comment]
>  in a regular mailbox, mutt will simply display "No virtual folder, aborting". 

I'm having a hard time figuring out the logistics of neomutt and "family"... I tried out the example:

`macro index A "<modify-labels-then-hide>-inbox\n" "modify"`  in a regular folder (had no clue <mod-label> was for vfolder only)

and I don't even get @randomizedthinking 's  somewhat clear error message; I get:

`Key is not bound`

¿Is that supposed to happen?

**Comment by flatcap** [comment]
@m2habert Hmm... the macro you've used is for the 'index' only.
If you're in the pager, viewing an email, the macro won't work.
You could try: `macro index,pager A ...`

**Comment by flatcap** [comment]
@randomizedthinking 
It's a reasonable idea, I'm just not sure how we'd do it.

Notmuch is implemented as a mailbox and the mailboxes are isolated from each other.
If I open a Maildir mailbox, it's unaware of IMAP, or Notmuch, etc.
Worse still, the Notmuch database won't be read **until** I open a Notmuch mailbox.

There are two solutions for this problem.  One trivial, the other complicated.

1. Create a virtual mailbox for each Maildir directory.
  I'm not a Notmuch expert (I don't what the query would look like)
  I think this clumsy idea would probably work for you

1. Separate the Notmuch database code from the Notmuch mailbox code.
  If we had a separate Notmuch object in the NeoMutt code, then we could pass it requests like: "please tag this file".
  This would be a **lot** of work and I'm not sure it'd be worth it.

**Comment by westernmagic** [comment]
> 1. Create a virtual mailbox for each Maildir directory.
> I'm not a Notmuch expert (I don't know what the query would look like)
> I think this clumsy idea would probably work for you

This is the route I chose. See my lua function [here](https://github.com/neomutt/neomutt/issues/1029#issue-290229074)

**Comment by schuam** [comment]
I know this issue is quite old and has been closed years ago. I still thought, I'd ask if anyone ever thought about implementing the feature that @randomizedthinking requested. I've been interested in used NeoMutt for a while now, but exactly this missing feature is keeping me from doing so, which is a pity, because NeoMutt seems to be a very cool program.

I also played around with @flatcap's first suggestion, but that comes with some inconvinent implications (deleting, moving, copying email is not that easy). So, being able to tag emails with notmuch in a maildir folder would be really nice.

I had a quick look into the source code. At first I thought all that needs to be done is replicating the functionality of the functions **nm_tags_edit** and **nm_tags_commit** for maildir, which didn't look to complicated to do, but this might have been a little naiv (not sure yet). I hope to find the time to look further into it.

Is issue #2541 going into this direction? So far, I don't know enought about the inner workings of the whole program to really understand it.
