### ISSUE TITLE
Mail into the future are not displayed (by default)

### ISSUE THREAD

**Issue by ferriff** [neomutt/neomutt#748]
Hi, I believe the behaviour one would wish for this line with the default search

   https://github.com/neomutt/neomutt/blob/e5d5de50095131b68c7c74f80e579def2ab6ad91/mutt_notmuch.c#L571

is to have the upper limit on the date open, i.e. `date:%d%s..` instead of `date:%d%s..now`.
It happened to me that a printer with wrong time settings sent me a document scan in the future ;) And it took me a funny while to notice it and manually get to the email by explicitly specifying an open end date.

I don't see any drawback in having an open end date, but being relatively new to the notmuch extension of neoMutt I let long time experts judge my 2 cents.

Cheers,
Federico

**Comment by ferriff** [comment]
Hi, just checking whether this is being discussed.
It seems to me a pretty immediate yes/no matter, with possibly a large favour for "yes", as it does not break the usual behaviour, it should only improve it.
Thanks and cheers,
Federico

**Comment by ferriff** [comment]
Hi, can you give feedback on why you closed the issue? I see that the master still has the unmodified code. The solution I proposed seems to improve the default behaviour with no side effects. Perhaps I just missed a devel branch where this has been implemented?
BTW, the same issues happened to me in other circumstances.
Thanks,
Federico

**Comment by flatcap** [comment]
Hi @ferriff 
Sorry for closing this unexpectedly.
Having hundreds of open issues (and no developers) becomes overwhelming at times, so sometimes I feel the need to kill lots of them.

Your change looks sensible to me, but I'm not a Notmuch user, so I can't be certain that it won't cause problems.

There are quite a few project members who **are** Notmuch users, but despite repeated efforts, I can't get any of them to help with Notmuch issues.

**Comment by ferriff** [comment]
Hi @flatcap , no problem, thanks for reopening it.
Hopefully some members will find 10 minutes to look at this (I honestly don't believe it requires more). I am open to discuss and help, if need be, but unfortunately I do not feel expert enough to sign this off myself, despite seeming trivial.

**Comment by Austin-Ray** [comment]
Since no notmuch user has weighed in, I feel obligated to.

@flatcap The proposed change should work. I've added the change and nothing appeared to break, but I'll continue testing. I do not believe this should cause any issue.

To quote `man notmuch-search-terms`
> Open-ended ranges are supported (since Xapian 1.2.1), i.e. it's possible to specify date:..\<until\> or date:\<since\>.. to not limit the start or end  time,  respectively.

However, the manual does warn about earlier versions of Xapian.

> Pre-1.2.1 Xapian does not report an error on open ended ranges, but it does not work as expected either.

Version 1.2.1 was released in 2010[0]. It is possible that this change could interfere with some users' notmuch usage who use very old packages. However, the likelihood seems small. RHEL 6 has version 1.2.7 [1] and Debian 8 has version 1.2.19 [2]. Would it be reasonable to insist a Neomutt user use packages from this decade?

[0] https://xapian.org/docs/Search-Xapian-1.2.24.0/Changes (You'll have to scroll down)
[1] https://dl.fedoraproject.org/pub/epel/6/x86_64/Packages/x/
[2] https://packages.debian.org/search?searchon=sourcenames&keywords=xapian-core

**Comment by flatcap** [comment]
> I've added the change and nothing appeared to break, but I'll continue testing.
> I do not believe this should cause any issue.

Thanks, that's exactly what I needed to hear :-)

> Version 1.2.1 was released in 2010[0]

That's old.
At some point, I need to draw a line in the sand and declare some version: unsupported.
I think we can discount users from this long ago.

**Comment by Austin-Ray** [comment]
@ferriff I pushed your change to branch `devel/issue/748`if you would like to test with me. I don't foresee any issues as the documentation is pretty clear about the matter, but you can never be too careful.

**Comment by Austin-Ray** [comment]
#1323 changed the window to be open-ended per the suggested edit in this issue.
