### ISSUE TITLE
Replace mutt_mktemp() with mkstemp()

### ISSUE THREAD

**Issue by nobrowser** [neomutt/neomutt#960]
Ultimately all the ways in mutt to create a temporary file come down to `mutt_mktemp_full()` in `muttlib.c`.  The varying part of the name that function creates, not counting totally predictable things like the PID, is a 64 bit random number.  That is less randomness than I have in freaking _shell scripts_, by using the `mktemp(1)` program with a suffix of 12 Xs (roughly 6*12 = 72 bits), as the Turtle Book [1] recommends.
Shouldn't we use the libc interfaces for making temporary files, which are similar to `mktemp(1)` and thus allow for more randomness?

[1] Classic Shell Scripting by Robbins & Beebe, O'Reilly Media 2005.  See pages 274-278.

**Comment by gahr** [comment]
One potential issue is that mktemp is legacy in POSIX 2001 and is not mentioned in 2008. The newer variants mkstemp and mkdtemp do not exist in POSIX-2001.

**Comment by flatcap** [comment]
> mkstemp

Actually, this **does** exist in POSIX-2001 (and 2008).
http://pubs.opengroup.org/onlinepubs/009695399/functions/mkstemp.html

As for why we're not using it... who knows!
There's a lot of filesystem code in NeoMutt that works around problems that probably don't exist any more.

Would you like to make us a proposal?

**Comment by gahr** [comment]
I stand corrected - shall we turn this issue into "switch to using mkstemp" ?

**Comment by flatcap** [comment]
There are nearly 100 calls to `mutt_mktemp()`.
Some of NeoMutt's temporary files are immediately deleted (just an open handle is kept).
There may be more common behaviour that can be refactored.

**Comment by nobrowser** [comment]
Well, hmm.  Is there an assumption that the files will be created in a safe private directory?  The fact that `mutt_mktemp()` just constructs the name and leaves the caller to actually `open()` it suggests that there is, because otherwise we suffer from the classic _symlink-to-passwd_ vulnerability.  OTOH `/tmp` is the ultimate default, and it is not safe this way.  So I am confused.  Either this is not worth doing (we're already safe), or we have a much bigger problem than just the form of the name.

**Comment by flatcap** [comment]
> Is there an assumption that the files will be created in a safe private directory?

Yes.  We'll still create the directory.  We'll just let `mkstemp()` do the 'random' bit.

> suffer from the classic symlink-to-passwd vulnerability

Possibly for the situation where we have a single db file in a cache dir that we don't own.
Mutt sets the umask to `077` on startup to mitigate any problems.

> Either this is not worth doing (we're already safe)

It's worth doing because all the duplicated code makes it hard to maintain and test.

**Comment by flatcap** [comment]
> I would feel much safer if there was only one code path for the creation

Absolutely.  Once the function has `mkstemp()`, we need to pull in much of the surrounding code (completely abstracting the temp file).

> So, we're both right, I guess :-P

Phew :-)

**Comment by flatcap** [comment]
@jelly
Are you still interesting in working on this?
Need some help?
Or just busy with real life?

**Comment by jelly** [comment]
I'm busy, trying to work on it tonight. I believe the whole function should be changed? Since mutt_mktemp_full just generates a "random" string, I believe we want it to call mkstemp. So to change mutt_mktemp into something along these lines:

```
char tempfile[_POSIX_PATH_MAX];
size_t n = snprintf(tempfile, sizeof(tempfile), "%s/neomutt-XXXXXXXXXXXXXX",
                NONULL(Tmpdir));
if (n < 0)
  mutt_debug("snptinf failed")

fd = mkstemp(tempfile)) == -1;
fp = fdopen(fd, "w")
return fp;
```

Which would involve a lot of refactoring.

BTW, I've also found another occurrence of a custom mkstemp-a-like in mh.c
```
snprintf(path, _POSIX_PATH_MAX, "%s/.mutt-%s-%d-%" PRIu64, dest->path,
NONULL(ShortHostname), (int) getpid(), mutt_rand64());
```

**Comment by gahr** [comment]
Except `n < 0` is always false ;)

**Comment by jelly** [comment]
Ah true, bytes written so it shouldn't write 0 :)

**Comment by jelly** [comment]
I'v unassigned since I probably won't have time soon, if I do I don't mind doing duplicate work.

**Comment by wcurry** [comment]
I'm taking a look at this.

**Comment by flatcap** [comment]
@wcurry 
I've just had a another look code...

Currently, `mutt_mktemp()` which calls `mutt_mktemp_full()` is a string function.
It generates a complicated name, which most of the callers immediately `fopen()`.

I suggest we start with a new function which calls `mkstemp()` and then migrate the callers one by one.

The new function will create a temporary file, delete it and return an open handle.
The filename should begin with 'neomutt' and live in `$tmpdir`.

This should simplify a **lot** of the callers.

Some other functions, notably in the crypt code, have two functions, one which creates and writes to the file, and a second that reads, then deletes it.  These can be refactored to use a `FILE*` pointer.

I suggest you:
- Have a look at a bunch of the callers
- Create a new 'temp' function
- Convert one of the callers
- Create a Pull Request

Then we can plan the rest.
Thanks.

<sub>(This issue may be **easy** to fix, but it's also **big**!)</sub>

**Comment by mjsir911** [comment]
I'm not exactly sure about the portability of `tmpfile()`, but have we considered using it in `mutt_file_mkstemp_full` instead of `mkstemp()`?. `tmpfile()` almost does everything we need to do in `mutt_file_mkstemp_full`, including unlinking the file after file pointer is accessed.

```diff
diff --git a/mutt/file.c b/mutt/file.c
index 6cd7313e..6a883118 100644
--- a/mutt/file.c
+++ b/mutt/file.c
@@ -862,25 +862,9 @@ int mutt_file_mkdir(const char *path, mode_t mode)
  */
 FILE *mutt_file_mkstemp_full(const char *file, int line, const char *func)
 {
-  char name[PATH_MAX];
+  FILE *fp = tmpfile();
 
-  int n = snprintf(name, sizeof(name), "%s/neomutt-XXXXXX", NONULL(Tmpdir));
-  if (n < 0)
-    return NULL;
-
-  int fd = mkstemp(name);
-  if (fd == -1)
-    return NULL;
-
-  FILE *fp = fdopen(fd, "w+");
-
-  if ((unlink(name) != 0) && (errno != ENOENT))
-  {
-    mutt_file_fclose(&fp);
-    return NULL;
-  }
-
-  MuttLogger(0, file, line, func, 1, "created temp file '%s'\n", name);
+  MuttLogger(0, file, line, func, 1, "created temp file");
   return fp;
 }
 ```

**Comment by flatcap** [comment]
`tmpfile()` is defined in POSIX.1-2001 which is our minimum requirement,
but it doesn't let us specify where the temp files go.

My docs say:

> The  standard  does not specify the directory that tmpfile() will use

I suppose it doesn't matter.

**Comment by nobrowser** [comment]
1. I wouldn't like the files created in an insecure location.
2. I depend on the path to set mode in external editor, so having control over it is valuable.

So, I vote against this change.

**Comment by mjsir911** [comment]
Regarding point 2, the current implementation of `mutt_file_mkstemp_full` deletes the file from the filesystem almost as soon as it is created, just keeping the file pointer (but not the actual file). 

And as for point 1, I think security is definitely a concern and [tmpfile does look at the TMPDIR environment variable](https://stackoverflow.com/a/1965116/6381767), but I'm not sure how much the location of an orphaned file pointer actually matters.

You've raised good points, I still think this change is worth it but more thought needs to be put into this.

**Comment by nobrowser** [comment]
Hi.  Does that mean this neomutt function is not used for outgoing message composition?  If it isn't, I withdraw objection 2, of course.

If TMPDIR is not set, what is the default location?  A few months ago there was a longish thread on the oss-security mailing list about the folly of using /tmp and such for files that are completely private to one user.

neomutt could set TMPDIR itself, but I think the interfaces for changing your own environment (as opposed to execing a new program with a modified one) are less than universally portable.

**Comment by mjsir911** [comment]
The old function, `mutt_mktemp()` ***is*** used for outgoing message composition, having that file exist based on your mutt tmpdir configuration. The new function `mutt_file_mkstemp_full()` does not have a file exist in the filesystem, and just returns a file pointer. This is the biggest reason all uses of `mutt_mktemp()` can't be replaced with `mutt_file_mkstemp_full()`.

If `TMPDIR` is not set the default location is `/tmp`. You are correct in that `/tmp` is not secure for single-user-readable files, but *these are not files*, just file pointers to files that did once exist insecurely

Now I'm not sure if the permissions still apply to these file pointers, and I can't readily find anything saying one way or the other.

Some alternatives that are also not perfect:
* `O_TMPFILE`: linux-only, probably not portable enough
* `TMPDIR` environment variable: I was mistaken, some implementations of `tmpfile()` use TMPDIR, but [this is not guaranteed](http://www.openwall.com/lists/oss-security/2017/11/06/12)

All in all, it seems [there is plenty of discussion about the security of tmpfile()](https://en.wikipedia.org/wiki/Talk%3ATmpfile#Removal_of_dubious_section_about_supposed_security_vulnerabilities), so I'm willing to put this proposal on hold because the benefit is *extremely* minimal.

**Comment by flatcap** [comment]
All the easy replacements have been done.
The remainder will need other refactoring work first.
