### ISSUE TITLE
Build error on master branch (commit 6559d43807687eedff6ded1d89c53a510db83adb 'Fix reference to neomuttrc')

### ISSUE THREAD

**Issue by changbindu** [neomutt/neomutt#972]
neomutt$ make
( echo '#include "config.h"'; echo '#include "mutt.h"'; \
echo '#include "address.h"'; echo '#include "lib/list.h"'; \
echo '#include "lib/buffer.h"'; echo '#include "parameter.h"'; \
echo '#include "body.h"'; echo '#include "envelope.h"'; \
echo '#include "header.h"';) | cc -E -g -O2 -std=c99 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D__EXTENSIONS__ -I/usr/include -I/usr/include/lua5.3  -DNCURSES_WIDECHAR -I. -I. -Wall  - | \
sh ./hcache/hcachever.sh hcache/hcversion.h
**<stdin>:4:22: fatal error: lib/list.h: No such file or directory**
compilation terminated.
make: *** No rule to make target 'headers.c', needed by 'headers.o'.  Stop.

Seems lib/list.h was moved to mutt/list.h?

**Comment by justinvasel** [comment]
I encountered a similar issue earlier today. For me it was due to the move similar to the one you mentioned. The name changes leave some old files laying around if you don't have a clean build.

This solution did the trick for me:
- make distclean
- rm *.Po (not sure if this was strictly necessary, but I did it)
- reconfigure
- make

**Comment by changbindu** [comment]
yeah, it works.  I just 'make clean' and reconfigure.

**Comment by justinvasel** [comment]
Great! Don't forget to close this issue if it's resolved for you :)
