### ISSUE TITLE
[Regression] Cannot send mail with PGP sign/encrypt; fails with `gpg: conflicting commands`

### ISSUE THREAD

**Issue by protist** [neomutt/neomutt#998]
* Expected behavior: sign and encrypt outgoing mail.
* Actual behavior: sending fails. After attempting to `send-message` from the `Compose` window, the error message is shown: `gpg: conflicting commands`.
* Steps to reproduce: sign and encrypt outgoing mail (PGP/MIME), then attempt to send.
* Used program versions: neomutt 20171208-1 (bug not present in 20171013-2)
* Operating System and its version: Arch Linux (up-to-date)

Additional details
-----
The following security modes fail:
* Sign, Encrypt (PGP/MIME) (OppEnc mode)
* Sign, Encrypt (PGP/MIME)

The following security modes work:
* Encrypt (PGP/MIME) (OppEnc mode)
* Encrypt (PGP/MIME)
* Sign (PGP/MIME)

PGP, so possibly related to bug #991?

**Comment by gahr** [comment]
Are you using GPGME? If not, could the changes introduced by #949 to the gpg.rc file be related?

**Comment by protist** [comment]
I'm not 100% if I'm using gpgme, but I do have it installed. I also have the following set:
```
pgp_use_gpg_agent = yes
source /usr/share/doc/neomutt/samples/gpg.rc
```

I tried reverting the `gpg.rc` file to the version from neomutt 20171013-2, and that fixes the problem. I also tried reverting the following line alone, which also worked.
```
--- gpg.rc.factory_default	2017-12-14 21:13:47.907719361 +1100
+++ gpg.rc	2017-12-14 21:20:37.208184794 +1100
@@ -68,7 +68,7 @@
 # 
 # set pgp_encrypt_sign_command="/usr/lib/neomutt/pgpewrap gpg-2comp %?p?--passphrase-fd 0? -v --batch --output - --encrypt --sign %?a?-u %a? --armor --always-trust -- -r %r -- %f"
 #
-set pgp_encrypt_sign_command="/usr/lib/neomutt/pgpewrap gpg %?p?--pinentry-mode loopback --passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - %?a?--local-user %a? --armor -- --recipient %r -- --sign --encrypt %f"
+set pgp_encrypt_sign_command="/usr/lib/neomutt/pgpewrap gpg %?p?--passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - --encrypt --sign %?a?-u %a? --armor --always-trust -- -r %r -- %f"
 
 # Import a key into the public key ring
 #
```

**Comment by gahr** [comment]
@libBletchley can you please comment on this one? Is there anything wrong with the new command?

**Comment by a3nm** [comment]
I'm also seeing this problem with NeoMutt 20171215 from Debian (20171215+dfsg.1-1).

**Comment by libBletchley** [comment]
Sorry for the slow reply.. I sometimes don't get e-mails for threads I'm subscribed, and I have no idea why I just got @a3nm's msg in email but not @gahr's.

Anyway, I just sent a signed and encrypted PGP/MIME msg to a protonmail user, and it all looks fine on my end.. no errors.  This was on Debian's neomutt version 20170113, and with the following encrypt+sign command:

`set pgp_encrypt_sign_command="/usr/lib/mutt/pgpewrap /usr/bin/gpg %?p?--pinentry-mode loopback --passphrase-fd 0? --batch --quiet --no-verbose --textmode --output - %?a?--local-user %a? --armor --always-trust -- --recipient %r -- --sign --encrypt %f"`

**Comment by libBletchley** [comment]
I just tried the same with this version:

NeoMutt 20171027-42-ad8712

and a red error msg flashed by very quickly.  I think it said something like "not available in this gpg".  But the mutt-stored version of what was sent looks fine (encrypted and signed), and my mail server shows that it was sent.

**Comment by protist** [comment]
I notice that your command from [this comment](https://github.com/neomutt/neomutt/issues/998#issuecomment-355585656) is actually a little different to the shipped version, in that `--always-trust` has been added. I tried your command (after fixing the path `s/mutt/neomutt/`), but that still fails for me.

Also, I'm using the latest NeoMutt, i.e. 20171215.

**Comment by makoshark** [comment]
I think the issue is that `--sign --encrypt` in after the second `--` which it should be before the first one. Making that change to the two places where this issue was introduced seems to fix the issue on my system. I've uploaded a patch and pull request.

**Comment by protist** [comment]
@makoshark Yes, that works fine now! Thank you.

Also, I'm not sure if I should just open up a new issue or not, but I've been also having trouble with encryption only, without signing. It works fine for keys that have trust=`ultimate`, but fails for trust=`fully` or `marginal`. If I try to send mail, I get the following error:
```
gpg: <key hash>: There is no assurance this key belongs to the named user
gpg: /home/protist/.mutt/tmp/neomutt-protist-home-<random-string> encryption failed: Unusable public key
```
This problem was in the original shipped `gpg.rc`, i.e.
```
set pgp_encrypt_only_command="/usr/lib/neomutt/pgpewrap gpg --batch --quiet --no-verbose --output - --textmode --armor -- --recipient %r -- --encrypt %f"
```
but also in @makoshark's changed version, i.e.
```
set pgp_encrypt_only_command="/usr/lib/neomutt/pgpewrap gpg --batch --quiet --no-verbose --output - --textmode --armor --encrypt -- --recipient %r -- %f"
```
The previously shipped version works fine
```
set pgp_encrypt_only_command="/usr/lib/neomutt/pgpewrap gpg --batch --quiet --no-verbose --output - --encrypt --textmode --armor --always-trust -- -r %r -- %f"
```

**Comment by makoshark** [comment]
I suspect this is just a function of the `--always-trust` option which is present in the old line but not in the new one. I think I'd prefer that mutt not require this behavior.

If you want to trust all keys, you can adding `trust-model always` to your `~/.gnupg/gpg.conf` configuration file.

**Comment by protist** [comment]
If I put back `--always-trust`, then it works again.

I'm by no means an expert, but my [understanding](https://gpgtools.tenderapp.com/kb/faq/what-is-ownertrust-trust-levels-explained) [is that](https://security.stackexchange.com/questions/41208/what-is-the-exact-meaning-of-this-gpg-output-regarding-trust) only your own keys have ultimate trust? If I'm encrypting an email to someone else, then this implies that their trust level would be lower than `ultimate`?

**Comment by makoshark** [comment]
@protist, there are many different ways folks like to handle trust in GPG. I have mine so that a key I don't know with signatures from 2 marginally or one fully trusted key count as "trusted." Anything else I want to look at it.

The point is that I don't think it's mutt's business to force `always-trust` on people that don't want to use that trust model or have specified a different trust model in their `gpg.conf`. If you want that, you can just add the line I suggested above to your `gpg.conf` and there will be no need to add `--always-trust` to your mutt `gpg.rc`.

**Comment by a3nm** [comment]
For reference, the corresponding pull request, which fixes this problem for me, is https://github.com/neomutt/neomutt/pull/1023

**Comment by libBletchley** [comment]
@protist 
> I notice that your command from this comment is actually a little different to the shipped version, in that --always-trust has been added. I tried your command (after fixing the path s/mutt/neomutt/), but that still fails for me.

I have `--always-trust` in my personal config, but as @makoshark says it's not proper to have that in the repository.  I removed it because it's a personal choice whether to relax the trust.

@makoshark 
> I think the issue is that --sign --encrypt in after the second -- which it should be before the first one. Making that change to the two places where this issue was introduced seems to fix the issue on my system. I've uploaded a patch and pull request.

I moved it to the end because that is the syntax rules according to the gpg man page.  Notice that `--recipient` is listed as under "Key related options".  An "option" goes before a command.

GPG is often lenient about mixing up the order, but I think I've seen pitfalls where a gpg CLI fails if not conforming to the sequence.  So I was sure to make the sequence compliant in case a future gpg change would cause it to break for the improperly ordered cases.

That said, I'm not sure why the correct order fails for you and not me, but the fix probably needs to go in gpg.

**Comment by libBletchley** [comment]
GPG bug report opened:

https://dev.gnupg.org/T3751

**Comment by makoshark** [comment]
I'm pretty sure the problem I was running into is not with GPG but with `pgpewrap`. The error is being caused because moving two options after the final `--` causes the first of the two options to be duplicated. This causes two `--sign` options to be included.

If you replace `gpg` with `echo` in your calls to `pgpewrap` it's pretty easy to see the behavior and figure out why it's happening.

**Comment by libBletchley** [comment]
@makoshark 

You're right, I overlooked that.  The two `--sign` commands indeed cause the `gpg: conflicting commands`.

The GPG man page is also still wrong.  And furthermore, there's actually a bug in pgpwrap itself.  I recall now that I struggled with it, and after more testing it seems there is no way to make pgpwrap work correctly when there are more than two tokens following the `--` terminating delimiter.

So to enumerate the bugs:

1. GPG man page incorrectly identifies `--recipient` as an _option_ as opposed to an _argument_, thus  leading me to introduce a bug.
1. pgpwrap duplicates tokens it shouldn't when a terminating delimiter is followed by more than two tokens.
1. The `gpg.rc` file I submitted triggered the pgpwrap bug, and simultaneously incorrectly ordered the `--recipient` ahead of the commands.

The pgpwrap bug doesn't need to be fixed now that `gpg.rc` has been fixed, strictly speaking, we only needed to fix one of the two -- as long as no one ever tries to put more than two tokens after the terminating delimiter in the future.

**Comment by a3nm** [comment]
Thanks for investigating the pgpewrap issues!

Coming back to https://github.com/neomutt/neomutt/issues/998#issuecomment-358072944 (though maybe this should be a different issue): my experience seems to be that, for untrusted keys, neomutt asks for confirmation before using the key (i.e., "ID has undefined validity. Do you really want to use the key? ([no]/yes)"). If you say "yes" here, but you don't specify `--always-trust` in gpg, then the gpg encryption command will fail ("Unusable public key"), because of the `--batch`.

So it seems to me that putting `--always-trust` in this gpg command is not intended to force a particular trust model on users. It's intended to give users the possibility of using an untrusted key at all (after accepting the confirmation prompt from neomutt). Am I right?

**Comment by makoshark** [comment]
@a3nm: Being willing to encrypt to an untrusted key without prompting *is* a trust model. GPG calls that trust model `always`.

The program asking you is not GPG, not neomutt. This is because both (a) the GPG you have installed is configured (perhaps by the default settings of your operating system?) to not encrypt to keys without user intervention unless they have some level of trust, and (b) the key you are trying to use does not reach that level of trust. That is what the trust model does.

Somebody once uploaded a GPG key with my name and email to the public key servers. Despite the fact that the key had no signatures and had never been verified by anybody, people who had that key and used `--always-trust` would encrypt an email to me that, in fact, could be read by someone else. That's why I don't use `--always-trust`. I *want* GPG to fail until I've taken some step to either ensure that key I am using is in fact controlled by the person I'm emailing (through signatures in the web of trust or verification through some other means). If I need to override this, I would like to override this by hand.

If you want to use `--always-trust`, you can go ahead and add `trust-model always` to your `.gnupg/gpg.conf`. That's your business and your choice. But neomutt has no business making that type of security decisions for users in a way that will override their existing security choices that they have encoded in *their* `.gnupg/gpg.conf`.

**Comment by a3nm** [comment]
Thanks @makoshark for your answer, but I'm not sure I understand it. I understand the GPG trust model, and the fact that the names and email addresses indicated on keys are not necessarily correct. My point was that there is a prompt asking about untrusted keys no matter whether you use `--always-trust` or not, and that without `--always-trust` there is a problem when you answer yes to the prompt.

The prompt that I am referring to is the following one, which I think is a prompt by mutt. I get it when I select an untrusted key:
![2018-01-27-144634_1920x1080_scrot](https://user-images.githubusercontent.com/843551/35472535-19a65578-0371-11e8-97f9-2c70039ba5c3.png)

I get this prompt no matter whether i put `--always-trust` for `pgp_encrypt_only_command` and `pgp_encrypt_sign_command` in my muttrc or not.

With `--always-trust`, I can either answer "no" and use a different key, or say "yes" and send the message anyway. This seems sensible to me.

Without `--always-trust`, I can answer "no", or I can answer "yes" and then mutt tries to send the message but `gpg` fails when trying to encrypt, with the error "Unusable public key", which is not especially explicit. To me, this behavior is worse than the one with `--always-trust`, no?

My understanding of why it makes sense to add `--always-trust` is that it tells gpg to ignore trust when doing the encryption, because the validity of keys has been checked earlier (and the user has been prompted about deciding to trust them or not.)

**Comment by darthdeus** [comment]
A question about putting `--encrypt` at the end. I noticed that the comments left in `gpg.rc` which have the `--always-trust` don't have it moved to the end, only the by default uncommented setting.
